scripts/release/utils.js
fix: release log generator for only pick up commit inside the packages
=> fix: release log generator for only pick up commit inside the package release

.github/workflows/pull-request-ci.yml, .github/workflows/release-develop.yml
Because we're currently generating `.temp` folder inside `scripts/webpack/build-element-scss/` after yarn build, the hash of the folder will not match since the `.temp/index.scss` file is different every time, thus causing cache couldn't be restored.
Fix that by using only `.js` files in` webpack` folder to calculate hash
=> fix: webpack pipeline cache not working in some cases

packages/graphql-server/serverless.yml
- Add `PLATFORM_API_BASE_URL` env in serverless deploy
=> chore: add PLATFORM_API_BASE_URL env to graphql server serverless deploy

packages/smb/src/constants/__tests__/error-messages.test.ts
chore: #516 fix smb app to structure as convention
=> chore: #516 fix smb app to structure as convention

packages/graphql-server/package.json
Run prettier after generating `schema.graphql`
=> chore: graphql server prettier after build:schema

packages/graphql-server/package.json
fix `cross-env` not working when chaining `&&`
=> fix: graphql server not detect process.env in local

packages/elements/package.json
Bump `@reapit/elements` v0.5.42
=> chore: bump elements version 0.5.42

.github/workflows/release-note-update.yml, package.json, scripts/document-update/get-release-and-create-pr.js, scripts/document-update/insert-at-line.js, scripts/document-update/map-package-path.js
fixes #599 
Flow:
1. Get `releaseTag` from `Github Action`
2. Extract `packageName` from `releaseTag`
3. Get release title, body, date from `releaseTag` using `Github API`
4. Format release note
5. Get `{ path, line }` object to `.md` file based on packageName (line is where content is inserted, this way, newer release notes always come first)
6. Insert release note to `path` at `line`
7. `git add -> git commit -> git push` (with `releaseTag` as branch name)
8. Create PR using `Github API`
=> chore: #599 include release note in gitbook

.github/workflows/release-production.yml, package.json, packages/elements/package.json, scripts/release/release-npm.js, scripts/release/utils.js, yarn.lock
- We need to capture the `release: edited` event, but it's not being triggered when authenticating with `GITHUB_TOKEN` . Use `GH_PAT` (personal access token) instead. As suggested in here:
https://help.github.com/en/actions/reference/events-that-trigger-workflows#triggering-new-workflows-using-a-personal-access-token
- Fix duplicated `_release` like [this](https://github.com/reapit/foundations/releases/tag/elements_v0.5.43) to avoid GitHub action being triggered 2 times
=> chore: fix edit release not trigger github action

packages/react-app-scaffolder/app/index.js, packages/react-app-scaffolder/app/templates/_config.example.json, packages/react-app-scaffolder/app/templates/_config.json, packages/react-app-scaffolder/app/templates/base-is-not-sass/src/scripts/webpack-dev.js, packages/react-app-scaffolder/app/templates/base-is-sass/src/scripts/webpack-dev.js, packages/react-app-scaffolder/app/templates/base/src/core/app.tsx, packages/react-app-scaffolder/app/templates/no-redux/src/context/__mocks__/mock-context.tsx, packages/react-app-scaffolder/app/templates/no-redux/src/core/private-route-wrapper.tsx, packages/react-app-scaffolder/app/templates/no-redux/src/hooks/use-auth.ts
Changes
- Add config to config.json of scaffolder
- Fix private route router
- Add isFetchSession for cognito flow
=> fix: #568 add more config to scaffolder and fix private route wrapper for check isFetching or not

package.json, yarn.lock
fixes #788 
Use `kind-of ^6.0.3` as people currently doing in here https://github.com/jonschlinkert/kind-of/pull/31
=> chore: #788 fix kind-of vulnerabilities

packages/react-app-scaffolder/app/templates/_package.json, packages/react-app-scaffolder/app/templates/base-is-not-sass/src/scripts/webpack-dev.js, packages/react-app-scaffolder/app/templates/base-is-not-sass/src/scripts/webpack-prod.js, packages/react-app-scaffolder/app/templates/base/src/core/app.tsx, packages/react-app-scaffolder/package.json, packages/web-components/src/search-widget/client/utils/__tests__/results-helpers.ts
fixes #837 
The `createGlobalStyle` function of `styled-component` is run at runtime, which means in browser, and our `index.css` file is ~11k lines, causing the browser to freeze
Changing to use `style-loader`, so that the CSS is processed at compile time
=> fix: #837 the react scaffolder extremely slow to compile

packages/elements/package.json
bump `@reapit/elements` version 0.5.51
=> chore: bump elements version 0.5.51

packages/marketplace/src/components/pages/__tests__/__snapshots__/register.tsx.snap, packages/marketplace/src/components/pages/register.tsx
=> fix: #902 Issue with text on after registering as a Developer

packages/web-components/src/common/utils/__tests__/get-server-headers.ts, packages/web-components/src/common/utils/get-server-headers.ts
fix: add api-version to earch widget components headers
=> fix: add api-version to earch widget components headers

packages/web-components/serverless.yml, packages/web-components/src/common/utils/__tests__/get-server-headers.ts, packages/web-components/src/common/utils/fetcher-server.ts, packages/web-components/src/common/utils/get-server-headers.ts, packages/web-components/src/search-widget/server/core/__tests__/index.ts, packages/web-components/src/search-widget/server/core/index.ts
Changes:
- Map header from requestContext to header of request
- Remove redundant headers when request to properties services
- Add logger
- Add more test
=> fix: map headers for requestContext from authorizer to header of lambda function

packages/elements/src/styles/components/layout.scss, packages/elements/src/styles/vendor/bulma-overrides.scss
fixes: #1067 
The problem happened because of multiple `overflow-y: scroll` in our css. 
(`bulma` -> `<AppNavContainer/>` -> `< FlexContainerBasic />`).
This fix would not break people that're currently using `<AppNavContainer />`
=> fix: #1067 fix double scroll bar issue

packages/elements/src/styles/vendor/bulma.scss
=> feat: #1120 elements headings font default fallback to roboto

.gitignore, package.json, scripts/utils/git-secrets.js, yarn.lock
Add pre-commit hook to scan for secrets before commit
1. GET AWS secrets from environment variables and `~/.aws/credentials`
2. Merge those secrets into one file (temporary file)
3. Register AWS provider for git-secrets using the file in step 2
4. Scan for secrets in staged files using `git secrets --scan`
5. Remove temporary file in step 2
=> chore: pre-commit secrets scanner

packages/elements/purify-options.js
fixes: #768
- [ x] Tests for the changes have been added (for bug fixes / features)
- [ x] Build (`yarn build`) was run locally and any changes were pushed
- [x ] Lint (`yarn lint`) has passed locally and any fixes were made for failures
- [x ] Test (`yarn test`) has passed locally and any fixes were made for failures
- [x ] Bugfix
- Goto: `https://dev.smb-app.reapit.cloud/Offices`
- Column `Office Email`, text is overflow 
Issue Number: #768 
- Goto: `https://dev.smb-app.reapit.cloud/Offices` (after merge master), or LOCAL ENV
- Column `Office Email`, text is not overflow
- [x ] No
Classes are purged by `purify-css` while building application using `webpack-sass-prod` …
=> fix: #768 - add spreadsheet classes to purify-css whitelist

packages/marketplace/src/components/ui/developer-analytics/cost-explorer/cost-explorer-component/cost-explorer-table.tsx, packages/marketplace/src/reducers/developer.ts
fixes:
Issue Number: #1392 
- Hide loader after successfully fetching data in analytics page
Before: 
After:
=> fix: #1392 Hide loader after finishing fetching data in analytics page

scripts/webpack/sw.js, scripts/webpack/webpack.base.prod.js
fixes: #1419
- create a branch, checkout to 9e834432 before sw got remove, to get the same env as people got service worker error
**make sure your service worker is working by:**
- put a button the page
- install event to call runtime.update function:
`import * as runtime from 'offline-plugin/runtime'`
`runtime.update()`
- build and start prod
- change some parts of the code and rebuild
- press button -> toast show up
- service worker is installed on dev tool -: `Application` tab -> `Service worker`
Issue Number: #1419
- Cherry pick commit in this branch to your created branch
- Rebuild the app
- Press button on the route created ^ -> no toast show up
- No service …
=> fix: #1419 service worker issue in production

packages/elements/src/components/Tile/__tests__/__snapshots__/index.tsx.snap, packages/elements/src/components/Tile/index.tsx, packages/marketplace/src/components/pages/installed-apps/__tests__/__snapshots__/installed-apps.test.tsx.snap, packages/marketplace/src/components/ui/__tests__/__snapshots__/app-list.tsx.snap, packages/marketplace/src/components/ui/app-list.tsx
fixes: #1442 
Issue Number: #1422 
- Fixed navigation
- Fixed `LeadPro` app (long text issue)
=> fix: #1422 IE bugs fix client portal

packages/elements/src/styles/vendor/pell.scss, packages/marketplace/src/components/pages/developer-submit-app/general-information-section.tsx, packages/marketplace/src/styles/pages/developer-submit-app.scss
fixes: #1518 
Issue Number: #1518
- Fix stretched description field by scrolling when overflow
=> fix: #1518 description stretching with long text

packages/elements/src/components/Map/__tests__/__snapshots__/index.tsx.snap, packages/elements/src/components/Map/__tests__/index.tsx, packages/elements/src/components/Map/index.tsx
fixes: #1629 
Issue Number: #1629 
- Change map for set default zoom and set center when no markers
- Change set default zoom to lower
=> fix: #1629 geo-diary should not zoom to low when no markers

packages/aml-checklist/package.json, packages/api-docs-lamda/package.json, packages/cognito-auth/package.json, packages/geo-diary-v2/package.json, packages/geo-diary/package.json, packages/graphql-server/package.json, packages/graphql-server/tsconfig.json, packages/lifetime-legal/package.json, packages/marketplace/package.json, packages/site-builder/package.json, packages/smb-onboarder/package.json, packages/web-components-config-server/package.json, packages/web-components-config-server/tsconfig.json, packages/web-components/package.json, packages/web-components/tsconfig.json, yarn.lock
Pull request checklist
fixes: #1748 
Issue Number: #1748 
- Remove unuse dependencies
- Add depencies use to package.json
=> fix: #1748 remove unuse dependencies and add use dependencies to package.json

packages/cognito-auth/src/__mocks__/cognito-session.ts, packages/cognito-auth/src/core/types.ts, packages/cognito-auth/src/utils/cognito.test.ts, packages/cognito-auth/src/utils/cognito.ts, packages/geo-diary-v2/src/context/__mocks__/mock-context.tsx, packages/marketplace/src/components/ui/developer-app-revision-modal/__test__/developer-app-revision-modal.test.tsx, packages/marketplace/src/constants/api.ts, packages/marketplace/src/core/__mocks__/store.ts, packages/marketplace/src/reducers/__stubs__/app-state.ts, packages/marketplace/src/sagas/__tests__/client.ts, packages/marketplace/src/sagas/__tests__/installed-apps.ts, packages/marketplace/src/sagas/__tests__/my-apps.ts, packages/marketplace/src/sagas/client.ts, packages/marketplace/src/sagas/installed-apps.ts, packages/marketplace/src/sagas/my-apps.ts, packages/marketplace/src/selector/__tests__/client.ts, packages/marketplace/src/selector/client.ts, packages/react-app-scaffolder/app/templates/apollo/src/context/__mocks__/mock-context.tsx, packages/site-builder/src/context/__mocks__/mock-context.tsx, packages/smb-onboarder/src/context/__mocks__/mock-context.ts
fixes: https://github.com/reapit/foundations/issues/1848
-
=> feat: #1848 filter app lists when using the marketplace in Developer Edition

packages/developer-portal/src/components/pages/register/__tests__/__snapshots__/register.test.tsx.snap, packages/developer-portal/src/components/pages/register/__tests__/register.test.tsx, packages/developer-portal/src/components/pages/register/register.tsx
fixes: #1917 
Issue Number: #1917 
- Remove unused code from register page in dev portal
=> feat: #1917 Remove unused code from register page in dev portal

packages/cognito-auth/package.json, packages/connect-session/package.json, packages/elements/package.json
fixes: #2032
Issue Number: #2032
- Include badges when releasing to npm
=> chore: #2032 elements & cognito-auth & connect-session badges broken

packages/cognito-auth/README.md, packages/connect-session/README.md, packages/elements/README.md, packages/elements/package.json, packages/web-components/README.md, packages/web-components/package.json
fixes: #2032 
Issue Number: #2032 
- Fix broken badges for npm packages
=> chore: #2032 NPM broken badges, use absolute paths instead

packages/developer-portal/src/components/pages/welcome/welcome.tsx
fixes: https://github.com/reapit/foundations/issues/2397
-
=> chore: #2397 Update 'Welcome Wizard' content in Developers Portal

packages/admin-portal/src/core/private-route-wrapper.tsx, packages/developer-portal/src/core/private-route-wrapper.tsx, packages/marketplace/src/core/private-route-wrapper.tsx, yarn.lock
fixes: #2451 
Issue Number: #2451 
- Land on page not found
=> fix: #2451 land on page not found bug

.github/workflows/release.yml, scripts/release/release.js, scripts/release/utils.js
fixes: #2519 
Issue Number: #2519 
- Remove old deployment scripts
=> chore: #2519 deprecated old script deploy dev

packages/developer-portal/src/components/ui/menu.tsx, packages/developer-portal/src/core/__tests__/__snapshots__/router.tsx.snap, packages/developer-portal/src/core/router.tsx, packages/developer-portal/src/services/developers.ts, yarn.lock
fixes: #2579 
Issue Number: #2579 
-
=> fix: #2579 unprotect routes

packages/events-service/src/controllers/automation/create.ts, packages/events-service/src/controllers/automation/delete.ts, packages/events-service/src/controllers/automation/get.ts, packages/events-service/src/controllers/automation/list.ts, packages/events-service/src/controllers/automation/update.ts, packages/events-service/src/controllers/event-status/create.ts, packages/events-service/src/controllers/event-status/get.ts, packages/events-service/src/controllers/event-status/list.ts, packages/events-service/src/controllers/event-status/update.ts, packages/events-service/src/controllers/event-status/upsert.ts, packages/events-service/src/controllers/event/create.ts, packages/events-service/src/controllers/event/list.ts, packages/events-service/src/types/http.status.enum.ts
Refactor to add http status code enum for human readable status codes on return from res.status etc. Checkout `packages/events-service/src/types/http.status.enum.ts`
Suggestion: 
Use exception classes and middlewares to reduce the need of duplicated conditions such as unauthorized responses. 
Example:
```ts
export class HttpException extends Error {
constructor(
readonly statusCode: HttpStatusCodeEnum = HttpStatusCodeEnum.INTERNAL_SERVER_ERROR,
readonly message?: string,
) {
super(message || statusCode.toString());
}
}
export class BadRequestException extends HttpException {
constructor(message?: string) { // Optional message for option of adding `validation errors`
super(HttpStatusCodeEnum.BAD_REQUEST, message || "Bad Request");
}
}
export class UnAuthorizedException extends …
```
=> refactor: added http status code enum for human readable status code returns 

packages/elements/package.json, packages/elements/src/components/searchable-dropdown/__tests__/__snapshots__/searchable-dropdown.test.tsx.snap, packages/elements/src/components/searchable-dropdown/searchable-dropdown.stories.mdx, packages/elements/src/components/searchable-dropdown/searchable-dropdown.tsx, packages/elements/src/storybook/changelog.stories.mdx
Created new function as the storybook one returns a static string if `NODE_ENV === 'test'` which in this case would log the warning again if used in the storybook context
fixes: #5774
=> fix: use random id for searchable dropdown item key

packages/admin-portal/src/components/pages/statistics/statistics.tsx
=> fix: #6210 removes pound sign as not encoded

packages/connect-session/README.md, packages/utils-nest/src/auth/token-provider.ts
=> fix: remove bearer prefix for auth

packages/rc-mfa-config/cdk-stack.ts, packages/ts-scripts/src/cdk/components/site.ts
Adds the ANZ r53 zone which DevOps can then delegate to to put it live.
Once they have we can uncomment the other lines in order to add it to the cloudfront dist
=> feat: rc-mfa-config anz deployment

packages/rc-mfa-config/src/components/active-authenticator/delete-authenticator.tsx, packages/rc-mfa-config/src/components/home/index.tsx, packages/rc-mfa-config/src/components/home/qr-code-verify.tsx, packages/rc-mfa-config/src/core/connect-session-native.tsx, packages/rc-mfa-config/src/core/connect-session.tsx
Feature flagged via a cookie set by RC so it won't affect anything until RC's updated to support the endpoint
=> fix: use native token for non-admin MFA requests

packages/cognito-custom-mail-lambda/serverless.yml
Instead of hooking it up ourselves, stops us trampling each other.
export name is "$stage-CognitoCustomMailerHandlerArn" e.g. "dev-CognitoCustomMailerHandlerArn" or "production-CognitoCustomMailerHandlerArn"
For #9896
=> fix: custom mailer - export function arn

packages/elements/src/components/nav/nav-responsive.tsx
This fixes a current issue where if you click "My Installed Apps" on the developer portal in production it takes you to the staging marketplace.
This is because developers.reapit.cloud contains "dev"
=> fix: elements app switcher - use prod url in prod

packages/elements/src/components/nav/nav-responsive.tsx, packages/elements/src/components/nav/nav.stories.mdx, packages/elements/src/storybook/changelog.stories.mdx, packages/marketplace/src/components/nav/nav.tsx, packages/marketplace/src/components/settings/settings-installed.tsx, packages/marketplace/src/utils/auth.ts, packages/payments-service/src/payment-receipt/__tests__/__snapshots__/provider.test.ts.snap, packages/payments-service/src/payment-receipt/template.ts, packages/payments-service/src/payment-request/__tests__/__snapshots__/provider.test.ts.snap, packages/payments-service/src/payment-request/template.ts
fixes: #10401 
fixes: #10396 
fixes: #9868 
fixes: #10314
=> feat: #10401 #10396 #9868 #10314 elements release fixes

packages/developer-portal/src/components/apps/new/__tests__/__snapshots__/helper-content.test.tsx.snap, packages/developer-portal/src/components/apps/new/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/new/helper-content.tsx, packages/ts-scripts/src/vite/base-vite.js
Resolves issue with tiny video thumbnail by forcing component to fill the available space. Issue was due to the svg element having a height of 1em when rendered. I'm not entirely sure where this was coming from, but the PR resolves the issue as shown below. The PR also alters one of the vite server properties which I had to adjust to get the application to run locally on my windows machine (using Ubuntu WSL). Without knowing the ecosystem very well I don't know if there'll be any adverse effects to changing this (I suspect not, given developers on Macs use localhost anyway), but please consider this change when reviewing.
fixes: #10942
=> fix: resolves issue with small video thumbnails in helper content

packages/admin-portal/package.json
To force new deployment to alter oauth client id
=> chore: bump admin-portal version

packages/data-warehouse/src/components/network/ip-table.tsx
Noticed during testing, the wrong pagination property is being used to determine the total number of pages which gives weird behaviour in the UI
=> fix: #11924 use correct pagination property

packages/data-warehouse/src/components/accounts/__tests__/__snapshots__/account-provision-modal.test.tsx.snap, packages/data-warehouse/src/components/accounts/account-provision-modal.tsx, packages/data-warehouse/src/types/accounts.ts
- User will now be forced to enter email address for all data warehouse accounts so we have someone to contact if we detect odd activity or other reasons
- Fixes issue with text fields overlapping each other
New modal:
=> feat: rplt-135 capture user email address when provisioning data warehouse user accounts

packages/api-key-service/src/api-keys/api-key-provider.ts
Long story short. Am deploying this to the api-key service just in case someone is using it. It's very unlikely anyone is but just in case! Before I go and tear the resources down on poduction
=> chore: deprecate warn for api-key-service

packages/developer-portal/src/components/apps/edit/__tests__/__snapshots__/app-listing-tab.test.tsx.snap, packages/developer-portal/src/components/apps/edit/form-schema/form-fields.ts, packages/developer-portal/src/components/apps/edit/form-schema/validation-schema.ts, packages/developer-portal/src/components/apps/new/__tests__/__snapshots__/helper-content.test.tsx.snap, packages/developer-portal/src/components/apps/new/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/new/config.tsx, packages/developer-portal/src/components/apps/new/helper-content.tsx, packages/developer-portal/src/components/apps/new/index.tsx, packages/utils-common/src/validators/__tests__/index.test.ts, packages/utils-common/src/validators/index.ts
Allows developers to use http://dev.reapit addresses in their app configurations to allow workaround to localhost consent prompt with Auth0
=> feat: rplt-512 allow dev.reapit unsecured domains to be registered against auth flow apps

packages/cognito-custom-mail-lambda/package.json
Removes automatic deployment of cognito custom mailer script as this is only required for ANZ for a short period
=> chore: deprecate devops-release

packages/developer-portal/src/components/apps/new/__tests__/__snapshots__/helper-content.test.tsx.snap, packages/developer-portal/src/components/apps/new/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/new/helper-content.tsx, packages/developer-portal/src/components/apps/new/index.tsx
- removes modal that popped up when registering a new app advising about refresh token changes
- updates wizard text to call out refresh token behaviour and points user to docs
Example
=> chore: rplt-623 remove token rotation modal and update wizard text

packages/deployment-service/src/entities/pipeline.entity.ts, packages/deployment-service/src/events/pusher-provider.test.ts, packages/deployment-service/src/events/pusher-provider.ts
In developer-portal. Pusher events are being consumed without serialisation which is resulting in repositories values being changed from a number to a string as a string from the database is returned as a number when making requests with http
=> feat: added serialisation to pusher events

packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-controls.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-deployments-table.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-new.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/dns/__tests__/__snapshots__/dns-steps.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/dns/dns-settings-page.tsx, packages/developer-portal/src/components/apps/pipeline/dns/dns-uki-success-modal.tsx, packages/developer-portal/src/components/apps/pipeline/pipeline-configure/pipeline-configure.tsx, packages/developer-portal/src/components/apps/pipeline/pipeline-controls.tsx, packages/developer-portal/src/components/apps/pipeline/pipeline-environment.tsx, packages/developer-portal/src/utils/date-time.ts
This PR introduces a number of minor tweaks to the look and feel of the IaaS pages in the Developer Portal:
1) DateTimes now displayed in 24hr format. It's a bit weird seeing "02:10:00" when it was done in the afternoon:
2) A number of wording adjustments. Trying to drop the use of "we" and so on to make it read a bit more professionally
3) Hides the Deploy and Delete Pipeline buttons when you're not on the Deployment tab
4) Reworks the Custom DNS tab to:
- Separate the DNS information for certification validation and cloudfront forwarding. Includes helper text above each section
- Adds Copy functionality for each part of each DNS record so it's easy for developers to copy the values shown on screen
5) Adds more descriptive text to the Configure and Environment Variables tabs
=> feat: iaas ui tweaks

packages/marketplace-management/src/components/pages/__tests__/__snapshots__/marketplace-app.test.tsx.snap, packages/marketplace-management/src/components/ui/apps/__tests__/__snapshots__/app-pricing-permissions-section.test.tsx.snap, packages/marketplace-management/src/components/ui/apps/app-pricing-permissions-section.tsx, packages/marketplace/src/components/apps-detail/__tests__/__snapshots__/app-install-modal.test.tsx.snap, packages/marketplace/src/components/apps-detail/__tests__/__snapshots__/apps-detail.test.tsx.snap, packages/marketplace/src/components/apps-detail/__tests__/__snapshots__/index.test.tsx.snap, packages/marketplace/src/components/apps-detail/app-install-modal.tsx, packages/marketplace/src/components/apps-detail/apps-detail.tsx
- resolves issue with links not being opened in user's default browser when in desktop mode
=> fix: rplt-624 switch to desktop links so that AgencyCloud pops the urls in a new browser window

packages/admin-portal/src/components/installations/index.tsx
feat: no longer include office group query string parameter on installations table. it slows the request down considerably  and the data returned when that parameter is included is not used
=> feat: rplt-898 no longer include office group query string parameter

packages/admin-portal/src/components/installations/__tests__/__snapshots__/index.test.tsx.snap, packages/admin-portal/src/components/installations/index.tsx
- adds a status filter to the installations table. it's often the case that terminated installations are irrelevant
@HollyJoyPhillips can you tag the ticket please once you've logged it
=> feat: add status filter to installations table

packages/admin-portal/src/components/installations/__tests__/__snapshots__/index.test.tsx.snap, packages/admin-portal/src/components/installations/index.tsx
Fixes RPLT-1025
- When querying installations by customer, office group installations will now be returned
=> fix: rplt-1025 include office group data when filtering installations by client

packages/developer-portal/index.html
- switch out chatbase initialization script so we aren't wanting browsers to execute inline scripts
=> fix: rplt-948 dont use inline script when initializing chatbase

packages/developer-portal/src/components/analytics/page/__tests__/__snapshots__/controls.test.tsx.snap, packages/developer-portal/src/components/analytics/page/controls.tsx
- Client and App lists will now be sorted alphabetically before rendering to provide a better experience trying to find certain apps
=> feat: rplt-1043 sort lists on analytics tab alphabetically

packages/rc-mfa-config/src/components/admin/__tests__/__snapshots__/index.test.tsx.snap, packages/rc-mfa-config/src/components/admin/index.tsx
- Removes organisation name from user list to prevent confusion to users managing users across organisations
fixes: #RPLT-1122
=> feat: rplt-1122 remove organisation name from user list

.github/workflows/release-prod.yml
- Updates github token permissions so that version bump commit can be written without needing to use a PAT
=> ci: update token permissions in production workflow

packages/cognito-custom-mail-lambda/src/mailer/custom-mailer.ts
- Detect/set email URL for MMI
- Also restore code relating to AgentPoint email URL, which must have been applied directly on the deployed Lambda
fixes: #n/a
=> chore: Update custom mailer URL handling for MMI and AgentPoint
