- packages/graphql-server/tsconfig.json
- packages/react-app-scaffolder/app/templates/_eslintrc.js
- packages/react-app-scaffolder/app/templates/_package.json
- packages/react-app-scaffolder/app/templates/_prettierrc.js
- packages/react-app-scaffolder/app/templates/base-is-not-sass/src/components/pages/__styles__/login.ts
- packages/react-app-scaffolder/app/templates/no-redux/src/components/pages/__tests__/authenticated.tsx
- packages/react-app-scaffolder/app/templates/no-redux/src/components/pages/__tests__/login.tsx
- packages/react-app-scaffolder/app/templates/no-redux/src/context/__tests__/auth-context.tsx
- packages/react-app-scaffolder/app/templates/no-redux/src/context/index.tsx
- packages/react-app-scaffolder/app/templates/redux/src/components/hocs/__tests__/route-fetcher.tsx
- packages/react-app-scaffolder/app/templates/redux/src/components/hocs/route-fetcher.tsx
- packages/react-app-scaffolder/app/templates/redux/src/components/pages/authenticated.tsx
- packages/react-app-scaffolder/app/templates/redux/src/components/pages/login.tsx
- packages/react-app-scaffolder/app/templates/redux/src/core/private-route-wrapper.tsx
- packages/react-app-scaffolder/app/templates/redux/src/reducers/__tests__/auth.ts
- packages/react-app-scaffolder/app/templates/redux/src/sagas/__tests__/authenticated.ts
- packages/react-app-scaffolder/app/templates/redux/src/utils/actions.ts
- packages/react-app-scaffolder/app/templates/redux/src/utils/route-dispatcher.ts
- packages/react-app-scaffolder/package.json
> fix: app scaffolder liniting issues

- packages/marketplace/src/utils/form/__tests__/submit-app.ts
- packages/marketplace/src/utils/form/submit-app.ts
> fix: #380 validation for submit app

- scripts/logger/sentry-logger.ts
> fix: #381 add extra info in sentry logger

- package.json
- scripts/logger/sentry-logger.ts
- yarn.lock
> fix: #381 Add polyfill for cross browser compatibility for sentry

- .github/workflows/release-develop.yml
fixes #125 
Need this to use cache across our PRs
https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#matching-a-cache-key
> chore: #125 reuse webpack cache across branches

- packages/graphql-server/src/app.ts
- packages/graphql-server/src/index.ts
- packages/graphql-server/src/logger/logger.ts
fix: handler context for lambda apollo server
> fix: handler context for lambda apollo server

- packages/graphql-server/src/resolvers/identity-check/__tests__/api.test.ts
- packages/graphql-server/src/resolvers/identity-check/__tests__/resolvers.test.ts
- packages/graphql-server/src/resolvers/identity-check/__tests__/services.test.ts
- packages/graphql-server/src/resolvers/identity-check/api.ts
- packages/graphql-server/src/resolvers/identity-check/identity-check.d.ts
- packages/graphql-server/src/resolvers/identity-check/resolvers.ts
- packages/graphql-server/src/resolvers/identity-check/services.ts
refactor: move typings for identity-check to identity-check.d.ts
> refactor: move typings for identity-check to identity-check.d.ts

- packages/marketplace/src/components/pages/__tests__/swagger.tsx
- packages/marketplace/src/components/pages/swagger.tsx
> fix: apply all headers to swagger request

- packages/smb/src/components/pages/login/login.tsx
- packages/smb/src/core/private-route-wrapper.tsx
> feat: #34 login page need to redirect to reapit connect

- packages/elements/package.json
ci: #519 remove concurrently on build prod of elements
> ci: #519 remove concurrently on build prod of elements

- packages/elements/package.json
- scripts/webpack/constants.js
fix: path resolve for reapit config
> fix: path resolve for reapit config

- packages/aml-checklist/src/components/pages/__tests__/__snapshots__/login.tsx.snap
- packages/aml-checklist/src/components/pages/login.tsx
- packages/elements/.storybook/config.js
- packages/elements/.storybook/webpack.config.js
- packages/geo-diary/src/components/pages/__tests__/__snapshots__/login.tsx.snap
- packages/geo-diary/src/components/pages/login.tsx
- packages/lifetime-legal/src/components/pages/__tests__/__snapshots__/login.tsx.snap
- packages/lifetime-legal/src/components/pages/login.tsx
- packages/marketplace/src/components/pages/__tests__/__snapshots__/login.tsx.snap
- packages/marketplace/src/components/pages/login.tsx
- packages/smb/src/components/pages/login/__tests__/__snapshots__/login.test.tsx.snap
- packages/smb/src/components/pages/login/login.tsx
- scripts/release/utils.js
- scripts/webpack/webpack.base.dev.js
- scripts/webpack/webpack.base.prod.js
- scripts/webpack/webpack.sass.dev.js
> feature: #550 add app version to login page

- packages/graphql-server/src/index.ts
> fix: cors on apollo-server

- packages/graphql-server/nodemon.json
- packages/graphql-server/package.json
- packages/graphql-server/src/__tests__/app.test.ts
- packages/graphql-server/src/app.ts
- packages/graphql-server/src/errors/__tests__/errors.test.ts
- packages/graphql-server/src/errors/errors.ts
- packages/graphql-server/src/index.ts
- packages/graphql-server/src/resolvers/appointments/api.ts
- packages/graphql-server/src/resolvers/appointments/appointments.d.ts
- packages/graphql-server/src/resolvers/areas/api.ts
- packages/graphql-server/src/resolvers/areas/areas.d.ts
- packages/graphql-server/src/resolvers/contacts/api.ts
- packages/graphql-server/src/resolvers/contacts/contacts.d.ts
- packages/graphql-server/src/resolvers/identity-checks/api.ts
- packages/graphql-server/src/resolvers/identity-checks/identity-checks.d.ts
- packages/graphql-server/src/resolvers/negotiators/api.ts
- packages/graphql-server/src/resolvers/negotiators/negotiators.d.ts
- packages/graphql-server/src/resolvers/offices/api.ts
- packages/graphql-server/src/resolvers/offices/offices.d.ts
- packages/graphql-server/src/utils/__tests__/axios-instances.test.ts
- packages/graphql-server/src/utils/__tests__/get-id-from-create-headers.test.ts
- packages/graphql-server/src/utils/__tests__/handle-error.test.ts
- packages/graphql-server/src/utils/axios-instances.ts
- packages/graphql-server/src/utils/get-id-from-create-headers.ts
- packages/graphql-server/src/utils/handle-error.ts
- packages/graphql-server/tsconfig.json
- yarn.lock
Relate #567 #549 
Changes:
Migrate fetcher to axios to request to other services
Add handleError function for reusable
> feat: #567 create mutation should return object instead of true or false and add handleError to return correctly

- packages/aml-checklist/src/components/ui/__tests__/__snapshots__/aml-progressbar.tsx.snap
- packages/aml-checklist/src/components/ui/aml-progressbar.tsx
> fix: #573 - Update the CSS to address header issue in AML

- package.json
- yarn.lock
> chore: #625 fix security vulnerabilities

- packages/elements/src/components/Checkbox/checkbox.stories.tsx
fix: #609 unable to select mutiple checkbox
> fix: #609 unable to select mutiple checkbox

- scripts/webpack/webpack.sass.dev.js
> chore: fix webpack config

- packages/react-app-scaffolder/app/templates/_package.json
- packages/react-app-scaffolder/app/templates/base-is-foundation/tsconfig.json
- packages/react-app-scaffolder/app/templates/base/src/core/index.tsx
- packages/smb/src/core/index.tsx
- packages/smb/tsconfig.json
> fix: #422 - Re-add internal scaffold option on CLI to App Scaffolder

- packages/elements/src/components/Alert/index.tsx
> chore: #649 export alerttype from elements

- packages/cognito-auth/package.json
- packages/react-app-scaffolder/app/templates/_package.json
Changes:
- Release script for cognito-auth
- Fix error on scaffolder
> fix: #568 fix react scaffolder bug

- .eslintrc.js
- packages/marketplace/src/core/index.tsx
- packages/marketplace/src/scripts/chat-bot.js
- packages/marketplace/src/types/global.d.ts
Changes
- Migrate process.env.CHAT_BOT_APP_ID to window.reapit.config.chatbotAppId
> fix: #681 bug after migrate config marketplace

- packages/web-components/package.json
- packages/web-components/serverless.yml
- packages/web-components/src/scripts/build-prod.js
- packages/web-components/src/scripts/rollup.config.search-widget.js
- packages/web-components/webpack.config.js
Changes:
- Add deploy pipeline for serverless
- Add deploy pipeline for search widget
> feat: #124 pipeline web components

- .github/auto_assign.yml
chore: add leXuanNha to reviewer list
> chore: add leXuanNha to reviewer list

- packages/web-components/public/index.html
fix: #124 script for run web components in local
> fix: #124 script for run web components in local

- packages/geo-diary/src/sagas/api.ts
fix: #698 issue appointment does not have propertyId
> fix: #698 issue appointment does not have propertyId

- packages/elements/package.json
> chore: bump elements version 0.5.44

- .github/workflows/release-note-update.yml
> chore: fix update doc pipeline

- packages/aml-checklist/src/components/pages/__tests__/__snapshots__/client-search.tsx.snap
- packages/aml-checklist/src/components/pages/client-search.tsx
- packages/aml-checklist/src/core/index.tsx
- packages/aml-checklist/src/types/global.d.ts
> fix: #700 - Update the 'Desktop Search' URL to use the correct App ID

- packages/web-components-config-server/serverless.yml
Changes
- serverless.yml to add event trigger lambda server to any http
> fix: #655 serverless web component config deployment

- packages/aml-checklist/src/core/private-route.tsx
> fix: aml app should not redirect if already on correct route

- packages/elements/src/components/DynamicLinks/utils.ts
Correct check window.__REAPIT_MARKETPLACE_GLOBALS__ writable logic
> fix: #739 correct logic

- packages/marketplace/package.json
- packages/marketplace/src/components/ui/__tests__/__snapshots__/app-detail.tsx.snap
- packages/marketplace/src/components/ui/__tests__/app-detail.tsx
- packages/marketplace/src/components/ui/app-detail.tsx
- yarn.lock
Changes
- UI for view api key of web components and tests
> feat: #741 ui for view api key of web componentts

- packages/marketplace/src/components/pages/__tests__/__snapshots__/developer-submit-app.tsx.snap
- packages/marketplace/src/components/ui/__tests__/__snapshots__/admin-approval-modal.tsx.snap
- packages/marketplace/src/components/ui/__tests__/__snapshots__/app-detail.tsx.snap
- packages/marketplace/src/components/ui/__tests__/__snapshots__/developer-app-modal.tsx.snap
- packages/marketplace/src/components/ui/__tests__/app-detail.tsx
- packages/marketplace/src/components/ui/app-detail-modal/__tests__/__snapshots__/app-detail-inner.tsx.snap
- packages/marketplace/src/components/ui/app-detail.tsx
- packages/marketplace/src/components/ui/app-revision-comparision/__tests__/__snapshots__/app-revision-comparision.tsx.snap
- packages/marketplace/src/components/ui/developer-app-revision-modal/__test__/__snapshots__/developer-app-revision-modal.test.tsx.snap
- packages/marketplace/src/reducers/app-detail.ts
- packages/marketplace/src/sagas/__stubs__/app-detail.ts
- packages/marketplace/src/sagas/__tests__/app-detail.ts
- packages/marketplace/src/sagas/app-detail.ts
Changes
- Add fetchApiKey for installtion apps
- Add test for fetchApiKey sagas
> feat: #741 integrate api for view api key when app installed

- packages/marketplace/src/components/ui/analytics/detailed/filter-bar/__test__/__snapshots__/filter-bar.test.tsx.snap
- packages/marketplace/src/components/ui/analytics/detailed/filter-bar/__test__/filter-bar.test.tsx
- packages/marketplace/src/components/ui/analytics/detailed/filter-bar/filter-bar.tsx
- packages/marketplace/src/constants/api.ts
- yarn.lock
> fix: adds sandbox as filter to analytics

- .github/auto_assign.yml
> chore: update reviewer

- packages/web-components/package.json
- packages/web-components/src/appointment-bookings/client/components/appointment-bookings.svelte
- packages/web-components/src/appointment-bookings/client/core/index.ts
- packages/web-components/src/common/styles/__tests__/__snapshots__/index.ts.snap
- packages/web-components/src/common/styles/theme.ts
- packages/web-components/src/search-widget/client/components/__tests__/__snapshots__/google-map.ts.snap
- packages/web-components/src/search-widget/client/components/__tests__/__snapshots__/property-detail.ts.snap
- packages/web-components/src/search-widget/client/components/__tests__/__snapshots__/search-widget.ts.snap
- packages/web-components/src/search-widget/client/components/google-map.svelte
- packages/web-components/src/search-widget/client/components/property-detail.svelte
- packages/web-components/src/search-widget/client/components/search-widget.svelte
- packages/web-components/src/search-widget/client/core/__tests__/__snapshots__/index.ts.snap
> feat: map slider

- packages/marketplace/src/core/__tests__/private-route-wrapper.tsx
- packages/marketplace/src/core/private-route-wrapper.tsx
> fix: #792 remove developer term and condition modal from private-router-wrapper

- packages/marketplace/src/components/pages/login.tsx
- packages/marketplace/src/styles/pages/login.scss
- yarn.lock
> chore: #889 markerplace login button is misaligned

- packages/marketplace/src/components/ui/__tests__/terms-and-conditions-modal/__snapshots__/schedule2.tsx.snap
- packages/marketplace/src/components/ui/terms-and-conditions-modal/schedule2.tsx
- packages/marketplace/src/components/ui/terms-and-conditions-modal/term-and-conditions.tsx
- packages/marketplace/src/styles/blocks/term-and-conditions-modal.scss
Hotfix for Beta, fees don't apply
> fix: t and c update

- packages/cognito-auth/README.md
> fix: cognito auth readme

- packages/web-components/package.json
fix: deploy pipeline release prod for web-components
> fix: deploy pipeline release prod for web-components

- packages/demo-site/package.json
fix: pipeline deploy demo-site
> fix: pipeline deploy demo-site

- packages/web-components/serverless.yml
fix: move api behind authorizers for web-components
> fix: move api behind authorizers for web-components

- packages/web-components/serverless.yml
chore: deploy search widget behind gateway
> chore: deploy search widget behind gateway

- .github/workflows/release-develop.yml
- .github/workflows/release-production.yml
- packages/web-components-config-server/serverless.yml
- packages/web-components/serverless.yml
chore: add env SLS_DEBUG for serverless debugging
> chore: add env SLS_DEBUG for serverless debugging

- package.json
- packages/marketplace/src/tests/cypress/fixtures/routes.ts
- packages/marketplace/src/tests/cypress/hooks/login.ts
- packages/marketplace/src/tests/cypress/integration/flow-admin-search-app.test.ts
- packages/marketplace/src/tests/cypress/integration/flow-filter-app-by-name-and-category.test.ts
- packages/marketplace/src/tests/cypress/integration/flow-submit-app-happy-path.test.ts
- yarn.lock
For some reasons, cypress sometime cannot catch login request inside promise in CI env, remove it
> fix: #122 Admin login e2e test

- .github/workflows/clear-cache.yml
Changes
- Add cron job to clean github job runner cache
> fix: ci cache problem by yarn.lock

- packages/marketplace/src/components/pages/__tests__/__snapshots__/admin-apps.tsx.snap
- packages/marketplace/src/components/pages/admin-apps.tsx
#957 As an ‘Admin’, I want to search for App Registrations by date in the Admin Portal
> feat: #957  search App Registrations by date in the Admin Portal

- packages/marketplace/src/tests/cypress/integration/flow-filter-app-by-name-and-category.test.ts
> fix: #939 fix e2e tests

- packages/cognito-auth/package.json
bump `@reapit/cognito-auth` v2.1.3
> chore: bump cognito-auth 2.1.3

- .github/workflows/release-develop.yml
- .github/workflows/release-production.yml
> chore: temporary disable e2e test

- packages/elements/src/components/SelectBox/__tests__/index.tsx
- packages/elements/src/components/SelectBox/index.tsx
- packages/elements/src/components/SelectBox/select-box.stories.tsx
- packages/marketplace/src/components/pages/__tests__/__snapshots__/developer-webhooks.tsx.snap
- packages/marketplace/src/components/pages/__tests__/developer-webhooks.tsx
- packages/marketplace/src/components/pages/developer-webhooks.tsx
- packages/marketplace/src/components/ui/menu.tsx
- packages/marketplace/src/constants/routes.ts
- packages/marketplace/src/core/__tests__/__snapshots__/router.tsx.snap
- packages/marketplace/src/core/router.tsx
> Feat #963: Implement Developer Webhooks page

- scripts/serverless-template-generator/README.md
- scripts/serverless-template-generator/cli.js
- scripts/serverless-template-generator/fullstack.ejs
- scripts/serverless-template-generator/lambda.ejs
- scripts/serverless-template-generator/webapp.ejs
- scripts/serverless-template-generator/webpack.config.ejs
resolve: issue #1010
- Add serverless.ejs for template
- Add webpack.config.ejs for template
- Add CLI script to generate template
> feat: #1010 add lambda service template generator

- packages/marketplace/src/components/ui/__tests__/terms-and-conditions-modal/__snapshots__/consumption-cost-methodology-table.tsx.snap
- packages/marketplace/src/components/ui/__tests__/terms-and-conditions-modal/__snapshots__/schedule2.tsx.snap
- packages/marketplace/src/components/ui/terms-and-conditions-modal/consumption-cost-methodology-table.tsx
- packages/web-components/jest.config.js
- packages/web-components/src/appointment-bookings/client/components/__tests__/__snapshots__/date-time-picker.test.ts.snap
- packages/web-components/src/appointment-bookings/client/components/__tests__/__snapshots__/planner-step2.test.ts.snap
- packages/web-components/src/appointment-bookings/client/components/__tests__/__snapshots__/time-cell.test.ts.snap
- packages/web-components/src/appointment-bookings/client/components/__tests__/date-time-picker.test.ts
- packages/web-components/src/appointment-bookings/client/components/__tests__/time-cell.test.ts
- packages/web-components/src/scripts/jest-setup.js
ISSUE: #1068 
Changes
- Update Table Calculation of Total Consumption Cost in Term and Condition modal
- Update snapshot
> feat: #1068 update  calculation total cost table in term and condition

- packages/geo-diary/src/constants/api.ts
fix: #1071 
Changes
- Change api-version for geo-diary
> fix: #1071 change api-version to correct one 2020-01-31

- packages/marketplace/src/components/ui/analytics/billing/__test__/__snapshots__/billing-tab.test.tsx.snap
- packages/marketplace/src/components/ui/analytics/billing/billing-tab.tsx
- packages/marketplace/src/components/ui/analytics/billing/service-chart/__tests__/__snapshots__/service-chart.test.tsx.snap
- packages/marketplace/src/components/ui/analytics/billing/service-chart/__tests__/service-chart.test.tsx
- packages/marketplace/src/components/ui/analytics/billing/service-chart/index.ts
- packages/marketplace/src/components/ui/analytics/billing/service-chart/service-chart.tsx
- packages/marketplace/src/styles/pages/analytics.scss
feat: #1073
Changes
- Add mock up UI for billing tab
> feat: #1073 create bar chart developer portal

- packages/marketplace/src/components/ui/analytics/billing/service-chart/__tests__/__snapshots__/service-chart.test.tsx.snap
- packages/marketplace/src/components/ui/analytics/billing/service-chart/service-chart.tsx
> feat: #1073 add axis label for service chart

- packages/marketplace/src/sagas/__tests__/submit-revision.ts
- packages/marketplace/src/sagas/submit-revision.ts
fix: #1066 
Changes
- Add upload helpers for image5
- Fix test
> fix: #1066 show image 5 for app revision submit

- packages/elements/src/components/SelectBox/index.tsx
Revert wrong classname placement of selectbox component in that belong to commit "fix: #693 - increase webhooks page dropdown size, and load developer apps data (#1095)"
> fix: #639 - selectbox styles

- packages/geo-diary/src/components/common/appointment-detail/appointment-detail.tsx
> fix: #1051 remove agencycloud link geo-diary

- packages/graphql-server/src/schema.graphql
- packages/web-components/src/appointment-bookings/client/components/__tests__/__snapshots__/appointment-bookings.test.ts.snap
- packages/web-components/src/appointment-bookings/client/components/__tests__/__snapshots__/form-step1.test.ts.snap
- packages/web-components/src/appointment-bookings/client/components/appointment-bookings.svelte
- packages/web-components/src/appointment-bookings/client/components/form-step1.svelte
- packages/web-components/src/appointment-bookings/client/core/store/form-store.ts
- packages/web-components/src/appointment-bookings/client/core/theme.ts
> fix: #1046 Updates required to the Book a Valuation first step modal

- packages/react-app-scaffolder/app/templates/base/src/constants/api.ts
- packages/react-app-scaffolder/package.json
fix: #1072
Changes:
- Change to correct api version
- Bump version
> fix: #1072 react scaffolder should use correct api version

- packages/marketplace/src/components/pages/__tests__/__snapshots__/login.tsx.snap
- packages/marketplace/src/components/pages/login.tsx
> fix: #1121 remove login type tab from marketplace's login page

- packages/marketplace/src/components/ui/__tests__/__snapshots__/webhook-edit-modal.tsx.snap
- packages/marketplace/src/components/ui/__tests__/webhook-edit-modal.tsx
- packages/marketplace/src/components/ui/webhook-edit-modal.tsx
feat: #1164
Changes
- modify generateCustomerOptions for return correct value
> feat: #1164 add SBOX to customer of subscription drop down

- scripts/release/release-dev.js
resolve #1217
Changes
- Config cloudfont cache
- Revert delete assert on S3 bucket when deploy dev env
> fix: #1217 config cloudfront cache to avoid chunk load error

- packages/marketplace/src/actions/__tests__/developer.ts
- packages/marketplace/src/components/ui/developer-analytics/billing/cost-explorer/__test__/cost-explorer.test.tsx
- packages/marketplace/src/components/ui/developer-analytics/billing/cost-explorer/cost-explorer.tsx
- packages/marketplace/src/components/ui/developer-analytics/detailed/filter-bar/__test__/__snapshots__/default-filter-group.test.tsx.snap
- packages/marketplace/src/components/ui/developer-analytics/detailed/filter-bar/default-filter-group.tsx
- packages/marketplace/src/sagas/__tests__/developer.ts
- packages/marketplace/src/services/__tests__/billings.ts
- packages/marketplace/src/services/billings.ts
Issue https://github.com/reapit/foundations/issues/1229
> fix: Error when loading the billings page in the Developers Portal

- scripts/release/release-dev.js
resolve #1217
Changes
- AWS cli to sync repo with cache control to 365 days
> fix: #1217 aws sync to S3 with cache control

- packages/marketplace/src/styles/blocks/app-list.scss
Fix css issue in client manage app page
> fix: css issue in client manage app

- scripts/release/release-dev.js
Changes
- remove recursive opts
> ci: fix sync cli not found --recursive opts

- packages/marketplace/src/components/ui/developer-analytics/billing/transaction-history/__test__/__snapshots__/transaction-history.test.tsx.snap
- packages/marketplace/src/components/ui/developer-analytics/billing/transaction-history/__test__/transaction-history.test.tsx
- packages/marketplace/src/components/ui/developer-analytics/billing/transaction-history/transaction-history.tsx
> fix: #1143 transaction history billing csv download link format is incorrect

- packages/web-components/serverless.yml
fixes #1106 
Add `reapit-customer` as a header in web component config
> fix: fix web component cors headers

- packages/marketplace/src/components/pages/developer-submit-app.tsx
Update HTMLEditor placeholder in marketplace
> fix: update placeholder html description

- packages/react-app-scaffolder/app/templates/_package.json
- packages/react-app-scaffolder/package.json
> fix: #1258 - react scaffolder fail to compile

- scripts/release/release-dev.js
Changes
- Add delete from remote bucket repo
- Change from sync to cp to s3 cli
> fix: change from cp to S3 instead of sync

- .github/pull_request_template.md
- .github/workflows/pr-lint.yml
fixes: #1230 
Issue Number: #1230 
Currently, we don't have a convention for creating Pull Request
- Add PR linter Github action to check for PR title format (PR will be auto closed if the PR title is in the wrong format)
- Add PR template for PR description
**Guide for PR title, description & commit message when merging into master:**
- The commit message should follow the convention [here](https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional#type-enum) (the same as before)
- PR title should be in the following format: `<type>: <#issuenumber(optional)> <description>`
For example:
- `feat: #1203 Pull Request description …
> feat: #1230 Add Pull Request description template

- .github/workflows/check-production-alive-cronjob.yml
- .github/workflows/pull-request-ci.yml
- package.json
- packages/aml-checklist/package.json
- packages/cloud-alert/cypress.json
- packages/cloud-alert/cypress/fixtures/data.json
- packages/cloud-alert/cypress/integration/__snapshots__/marketplace.test.ts.snap
- packages/cloud-alert/cypress/integration/aml-checklist.test.ts
- packages/cloud-alert/cypress/integration/geo-diary.test.ts
- packages/cloud-alert/cypress/integration/life-time-legal.test.ts
- packages/cloud-alert/cypress/integration/marketplace.test.ts
- packages/cloud-alert/cypress/plugins/cy-ts-preprocessor.js
- packages/cloud-alert/cypress/plugins/index.js
- packages/cloud-alert/cypress/support/commands.ts
- packages/cloud-alert/cypress/support/constants.ts
- packages/cloud-alert/cypress/support/index.d.ts
- packages/cloud-alert/cypress/support/index.ts
- packages/cloud-alert/cypress/tsconfig.json
- packages/cloud-alert/package.json
- packages/cloud-alert/tsconfig.json
- packages/geo-diary/package.json
- packages/lifetime-legal/package.json
- packages/marketplace/package.json
- packages/smb-onboarder/package.json
- yarn.lock
resolve #1221 
Changes
- Add cypress request cronjob for apps each 30 mins
- Add push notification to cloud-sentry channel if failed
- Clean up un-use cli
> feat: #1221 add cloud alert for production env web apps

- scripts/release/release-dev.js
fixes: #1217 
Issue Number: #1217 
- Copy script will exclude index.html and sw.js for caching from S3
> ci: #1217 fix aws cp command to exclude sw.js and index.html for caching

- packages/marketplace/src/components/pages/__tests__/__snapshots__/developer-webhooks.tsx.snap
- packages/marketplace/src/components/pages/developer-webhooks.tsx
- packages/marketplace/src/components/ui/__tests__/__snapshots__/webhook-test-modal.tsx.snap
- packages/marketplace/src/components/ui/webhook-edit-modal.tsx
- packages/marketplace/src/components/ui/webhook-test-modal.tsx
fixes: https://github.com/reapit/foundations/issues/1277
-
> chore: #1277 Update wording on the Webhooks page in the Developers Portal

- packages/elements/src/components/CameraImageInput/index.tsx
- packages/elements/src/components/FileInput/file-input.stories.tsx
- packages/elements/src/components/FileInput/index.tsx
fixes: https://github.com/reapit/foundations/issues/964
- When fileinput has file, click on file name will be open  file-choser again.
- If user provides `onFilenameClick ` prop, user can handle the file name click callback
> chore: #964 Update file input component to make filename clickable

- packages/marketplace/src/components/pages/client-app-detail/__test__/__snapshots__/app-content.test.tsx.snap
- packages/marketplace/src/components/pages/client-app-detail/__test__/__snapshots__/client-app-detail.test.tsx.snap
- packages/marketplace/src/components/pages/client-app-detail/__test__/app-content.test.tsx
- packages/marketplace/src/components/pages/client-app-detail/__test__/app-header.text.tsx
- packages/marketplace/src/components/pages/client-app-detail/__test__/client-app-detail.test.tsx
- packages/marketplace/src/components/pages/client-app-detail/app-content.tsx
- packages/marketplace/src/components/pages/client-app-detail/app-header.tsx
- packages/marketplace/src/components/pages/client-app-detail/client-app-detail.tsx
- packages/marketplace/src/components/ui/client-app-detail/__test__/__snapshots__/client-app-uninstall-confirmation.test.tsx.snap
- packages/marketplace/src/components/ui/client-app-detail/client-app-uninstall-confirmation.tsx
- packages/marketplace/src/components/ui/developer-analytics/cost-explorer/cost-explorer-component/cost-explorer.tsx
- packages/marketplace/src/reducers/client/app-detail.ts
- packages/marketplace/src/sagas/apps/__test__/apps.test.ts
- packages/marketplace/src/sagas/apps/apps.ts
- packages/marketplace/src/services/__tests__/apps.test.ts
- packages/marketplace/src/services/apps.ts
- packages/marketplace/src/styles/pages/client-app-detail.scss
> fix: #1225 ui for mobile client side app

- packages/elements/package.json
> chore: bump elements version 0.5.57

- packages/marketplace/src/components/pages/__tests__/__snapshots__/developer-webhooks.tsx.snap
- packages/marketplace/src/components/pages/developer-webhooks.tsx
- packages/marketplace/src/components/ui/__tests__/__snapshots__/webhook-test-modal.tsx.snap
- packages/marketplace/src/components/ui/developer-analytics/cost-explorer/cost-explorer-component/cost-explorer-table.tsx
- packages/marketplace/src/components/ui/webhook-edit-modal.tsx
- packages/marketplace/src/components/ui/webhook-test-modal.tsx
fixes: #1300 
Issue Number: #1300 
- Text and links are updated in webhooks page and add/edit/ing webhook modal
- Fix a spelling error on the cost explorer page
> fix: #1300 Update text and links on developer webhooks page

- packages/elements/src/styles/vendor/bulma-overrides.scss
- packages/marketplace/src/components/pages/authentication/__test__/__snapshots__/authentication.test.tsx.snap
- packages/marketplace/src/components/pages/authentication/authentication.tsx
- packages/marketplace/src/components/pages/login.tsx
- packages/marketplace/src/core/__tests__/__snapshots__/router.tsx.snap
- packages/marketplace/src/core/__tests__/private-route.tsx
- packages/marketplace/src/core/private-route.tsx
- packages/marketplace/src/core/router.tsx
- packages/marketplace/src/sagas/developer.ts
- packages/marketplace/src/utils/__tests__/auth-route.ts
- packages/marketplace/src/utils/__tests__/route-dispatcher.ts
- packages/marketplace/src/utils/auth-route.ts
- packages/marketplace/src/utils/route-dispatcher.ts
fixes: #1290 
Issue Number: #1290 
- Redirecting from Client portal to Developer login and vice versa will now throw any error message
- Authentication modal UIs are updated with headers
- Links in authentication modals are highlighted with bold text and blue color
> fix: #1290 Fix issues with logging into dev and client portal

- packages/marketplace/src/components/ui/__tests__/__snapshots__/sandbox-pop-up.tsx.snap
- packages/marketplace/src/components/ui/__tests__/sandbox-pop-up.tsx
- packages/marketplace/src/components/ui/sandbox-pop-up.tsx
- packages/marketplace/src/styles/blocks/sandbox-pop-up.scss
fixes: https://github.com/reapit/foundations/issues/1292
-
> fix: #1292 fix Toast should be full width in desktop mode

- packages/web-components/package.json
- packages/web-components/scripts/start-dev.js
- packages/web-components/src/search-widget/server/serverless.yml
fixes: #1218
Issue Number: #1218 
- Fix this
> fix: #1218 fix service name not valid

- packages/web-components-config-server/serverless.yml
fixes: #1289 
Issue Number: #1289
- Deploy web-components-config-server to AWS
> chore: #1289 web-components-config-server deploy

- .github/pull_request_template.md
- .github/workflows/pr-lint.yml
No
Currently [WIP] PR will be auto-closed
Allow [WIP] in PR title.
E.g.
`[WIP] feat: #123 add feature abc`
> chore: allow [WIP] in PR title

- .gitignore
- package.json
- packages/elements/.storybook/webpack.config.js
- packages/elements/linaria.config.js
- packages/elements/package.json
- packages/elements/rollup.config.js
- packages/elements/src/components/Breadcrumb/breadcrumb.stories.tsx
- packages/elements/src/components/Breadcrumb/index.ts
- packages/elements/src/v2/src/components/breadcrumb/__styles__/styles.ts
- packages/elements/src/v2/src/components/breadcrumb/__tests__/__snapshots__/breadcrumb-item.test.tsx.snap
- packages/elements/src/v2/src/components/breadcrumb/__tests__/__snapshots__/breadcrumb-separator.test.tsx.snap
- packages/elements/src/v2/src/components/breadcrumb/__tests__/__snapshots__/breadcrumb.test.tsx.snap
- packages/elements/src/v2/src/components/breadcrumb/__tests__/breadcrumb-item.test.tsx
- packages/elements/src/v2/src/components/breadcrumb/__tests__/breadcrumb-separator.test.tsx
- packages/elements/src/v2/src/components/breadcrumb/__tests__/breadcrumb.test.tsx
- packages/elements/src/v2/src/components/breadcrumb/breadcrumb-item.tsx
- packages/elements/src/v2/src/components/breadcrumb/breadcrumb-separator.tsx
- packages/elements/src/v2/src/components/breadcrumb/breadcrumb.tsx
- packages/elements/src/v2/src/components/breadcrumb/index.ts
- packages/elements/src/v2/src/components/index.ts
- scripts/jest/jest-setup.js
- yarn.lock
fixes: #1274 
Issue Number: #1274 
- Add breadcrumb components
- Add stories book for breadcrumb
- Add config for linaria
- Add classnames for styles check
> feat: #1274 create breadcrumb components

- packages/elements/src/v2/src/components/breadcrumb/__styles__/styles.ts
- packages/elements/src/v2/src/components/breadcrumb/__tests__/__snapshots__/breadcrumb-item.test.tsx.snap
- packages/elements/src/v2/src/components/breadcrumb/__tests__/__snapshots__/breadcrumb.test.tsx.snap
- packages/elements/src/v2/src/components/breadcrumb/__tests__/breadcrumb-item.test.tsx
- packages/elements/src/v2/src/components/breadcrumb/breadcrumb-item.tsx
- packages/elements/src/v2/src/components/breadcrumb/breadcrumb.tsx
- scripts/webpack/webpack.base.dev.js
- scripts/webpack/webpack.base.prod.js
- scripts/webpack/webpack.sass.dev.js
fixes: #1274 
- [] Feature
- [] Code style update (formatting, renaming)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] Documentation content changes
- [] Other (please describe):
Issue Number: #1274 
- Add config for linaria
- [] Yes
> chore: #1274 add MiniCssExtractPlugin to prod and dev webpack

- packages/web-components-config-server/serverless.yml
fixes: #1289
Issue Number: #1289 
- Enable CORS for web components config server
> fix: #1289 enable cors web-components-config-server

- packages/web-components/scripts/rollup.config.login.js
> chore: Add loginWithReapit button rollup config

- packages/aml-checklist/src/services/__tests__/documents.ts
- packages/aml-checklist/src/services/documents.ts
fixes: https://github.com/reapit/foundations/issues/964
-
> fix: #964 add extension for download file

- scripts/webpack/webpack.sass.dev.js
fixes: #1274 
- [] Feature
- [] Code style update (formatting, renaming)
- [] Refactoring (no functional changes, no api changes)
- [] Build related changes
- [] Documentation content changes
- [] Other (please describe):
- 
Issue Number: #1274 
- Change webpack.sass.dev.js to add mini css extract loader before css-loader
- [] Yes
> fix: #1274 fix mini css extract error on dev

- .github/pull_request_template.md
No
If not checked, the checkboxes will be as below
Remove whitespace from checkboxes in template
Sorry @willmcvay we cannot remove whitespaces from template because it will break markdown syntax
> chore: fix whitespace in pr template

- packages/elements/src/styles/components/layout.scss
> fix: fix client app page css issue

- packages/web-components/src/appointment-planner/server/serverless.yml
> chore: Update planner bucket name

- packages/elements/src/components/Layout/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components/Layout/index.tsx
- packages/marketplace/src/components/pages/__tests__/__snapshots__/client-welcome.tsx.snap
- packages/marketplace/src/components/pages/__tests__/__snapshots__/developer-help.test.tsx.snap
- packages/marketplace/src/components/pages/__tests__/__snapshots__/elements.tsx.snap
- packages/marketplace/src/components/pages/__tests__/__snapshots__/login.test.tsx.snap
- packages/marketplace/src/components/pages/admin-approvals/__tests__/__snapshots__/admin-approvals.test.tsx.snap
- packages/marketplace/src/components/pages/elements.tsx
- packages/smb-onboarder/src/components/pages/login/__tests__/__snapshots__/login.test.tsx.snap
- packages/smb-onboarder/src/components/pages/negotiators/__tests__/__snapshots__/negotiators.test.tsx.snap
- packages/smb-onboarder/src/components/pages/offices/__tests__/__snapshots__/offices.tsx.snap
- packages/smb-onboarder/src/core/__tests__/__snapshots__/private-route-wrapper.tsx.snap
Add an optional prop `isFullHeight` to `<FlexContainerBasic>` component
> fix: fix element page on mobile

- packages/elements/src/components/Breadcrumb/breadcrumb.stories.tsx
fixes: #1274
Issue Number: #1274
- Add styles for breadcrumb component icon in storybook
> fix: #1274 breadcrumb style in elements storybook

- packages/marketplace/src/core/__tests__/__snapshots__/app.tsx.snap
- packages/marketplace/src/core/app.tsx
- scripts/webpack/webpack.base.prod.js
fixes: #
- Service worker installed: master branch -> build app -> `yarn start:prod` -> dev tool -> application tab ->service worker
- Service worker remove: current branch `chore/remove-offline-service-worker-from-marker-place` -> build app -> `yarn start:prod` -> dev tool -> application tab ->service worker
-
> chore: remove offline plugin + offline service worker of marketplace

- packages/marketplace/src/components/pages/client-app-detail/client-app-detail.tsx
fixes: #1206 
Issue Number: #1206 
- [] Yes
> fix: #1206 install uninstall button

- packages/cognito-auth/src/session/remove-session.test.ts
- packages/cognito-auth/src/session/remove-session.ts
- packages/cognito-auth/src/utils/cognito.test.ts
- packages/cognito-auth/src/utils/cognito.ts
- packages/marketplace/src/core/__tests__/__snapshots__/private-route.tsx.snap
- packages/marketplace/src/core/__tests__/private-route.tsx
- packages/marketplace/src/core/private-route.tsx
- scripts/jest/jest.config.js
fixes: #
- Fix for fetch token in route-fetcher
> fix: hot fix for private route

- packages/cognito-auth/package.json
fixes: #
- Bump version and hot fix cognito-auth
> chore: bump version cognito auth

- scripts/release/release-dev.js
- scripts/release/release-prod.js
fixes: #
Issue Number: #1390 
- Will not throw any error log about missing sourcemaps in dev and prod
> fix: #1390 sourcemaps not loaded in dev and prod

- packages/elements/src/components/DatePicker/index.tsx
- packages/elements/src/components/Table/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components/Table/index.tsx
- packages/elements/src/components/ToastMessage/__tests__/index.tsx
- packages/elements/src/components/ToastMessage/index.tsx
- packages/marketplace/src/components/pages/admin-apps/__tests__/__snapshots__/admin-apps.test.tsx.snap
> fix: #1391 Fix warning error which display in marketplace

- packages/marketplace/src/core/__tests__/private-route.tsx
- packages/marketplace/src/core/private-route.tsx
fixes: #1381 
- Hotfixes a routing regression in Admin area
- Admin routing working as expected
> fix: #1381 hotfix on admin routing

- packages/marketplace/src/components/pages/login.tsx
fixes: #1424
Issue Number: #1424
-
> fix: #1424 Admin Portal landing page issue

- packages/marketplace/src/components/hocs/__tests__/route-fetcher.tsx
- packages/marketplace/src/components/hocs/route-fetcher.tsx
- packages/marketplace/src/components/ui/developer-analytics/cost-explorer/transaction-history/__test__/__snapshots__/transaction-history.test.tsx.snap
- packages/marketplace/src/components/ui/developer-analytics/cost-explorer/transaction-history/transaction-history.tsx
- packages/marketplace/src/components/ui/sandbox-pop-up.tsx
fixes: https://github.com/reapit/foundations/issues/1391
-
> fix: #1391 fix marketplace warning error

- packages/web-components/scripts/start-dev.js
- packages/web-components/src/appointment-planner-component/server/api/__tests__/get-appointment-slots.ts
- packages/web-components/src/appointment-planner-component/server/api/get-appointment-slots.ts
- packages/web-components/src/appointment-planner-component/server/serverless.yml
fixes: https://github.com/reapit/foundations/issues/1222
-
> chore: #1222 Update env variables for appointment planner

- packages/marketplace/src/components/ui/app-installations/__tests__/__snapshots__/confirm-uninstall.tsx.snap
- packages/marketplace/src/components/ui/app-installations/confirm-uninstall.tsx
fixes: https://github.com/reapit/foundations/issues/1354
-
> chore: #1354 Update the confirm uninstall modal style

- packages/marketplace/src/styles/blocks/categories-list.scss
fixes: #1371
Issue Number: #1371
-
> fix: #1371 filtering-mobile-and-ui-issues-on-browse-apps

- .github/workflows/release-note.yml
fixes: #1333 
- Add NPM_TOKEN to release-note workflows and remove REAPIT_ENV in workflows files
> ci: #1333 update env for release-tag

- packages/marketplace/src/components/hocs/route-fetcher.tsx
> fix: #1474 fix Route Fetcher not fetch when switch page

- packages/marketplace/src/components/ui/app-installations/__tests__/__snapshots__/confirm-uninstall.tsx.snap
- packages/marketplace/src/components/ui/app-installations/confirm-uninstall.tsx
fixes: https://github.com/reapit/foundations/issues/1354
-
> chore: #1343 Update confirm uninstall modal style

- .github/workflows/release-tag.yml
fixes: #1333 
Issue Number: #1333  
- Change install isomorphic-fetch
> fix: #1333 add isomorphic-fetch for release-tag

- .github/workflows/release-note.yml
- .github/workflows/release.yml
- packages/web-components/package.json
- packages/web-components/scripts/release-serverless.js
- scripts/release/release.js
- scripts/release/utils.js
> fix: #1333 create tag and release note dependencies

- .github/workflows/check-production-alive-cronjob.yml
- .github/workflows/foundation-ts-definition-cronjob.yml
- .github/workflows/pr-ci.yml
- .github/workflows/release-note-update.yml
- .github/workflows/release-note.yml
- .github/workflows/release-tag.yml
- .github/workflows/release.yml
- packages/deploy-slack-bot/src/index.ts
- scripts/document-update/get-release-and-create-pr.js
- scripts/document-update/map-package-path.js
- scripts/release/generate-release-note.js
fixes: #1333
Changes
- Add update flow for slackbot command
> ci: #1333 add update doc flow for slack bot command

- .github/workflows/pr-lint.yml
No
PRs created by Snyk are auto closed
Allo Snyk PR
> chore: allow snyk PR

- .github/workflows/release-note-update.yml
- packages/deploy-slack-bot/src/index.ts
- scripts/document-update/get-release-and-create-pr.js
- scripts/release/update-release-note.js
fixes: #1333 
- Update release note scripts
> ci: #1333 update release note ci

- packages/marketplace/src/components/pages/admin-dev-management/__tests__/admin-dev-management.test.tsx
- packages/marketplace/src/components/pages/admin-dev-management/admin-dev-management.tsx
- packages/marketplace/src/constants/routes.ts
- packages/marketplace/src/core/__tests__/__snapshots__/router.tsx.snap
- packages/marketplace/src/core/router.tsx
- packages/marketplace/src/utils/route-dispatcher.ts
fixes: #1506 
Issue Number: #1506 
http://g.recordit.co/uoEzdiFnfc.gif
- Can change page for developer
- Can filter developer
Changes
- Pagination for developer management
- Change to query params
> fix: #1506 pagination  for developer management

- packages/aml-checklist/src/components/ui/modal/__tests__/__snapshots__/report.tsx.snap
- packages/elements/package.json
- yarn.lock
fixes: #
Issue Number: #1422 
- Marketplace's production build is working on IE again
> fix: #1422 Fix IE crashing issues due to google-maps-loader

- packages/cognito-auth/jest.config.js
- packages/cognito-auth/package.json
- packages/cognito-auth/tsdx.config.js
- packages/elements/jest.config.js
- packages/elements/package.json
- packages/elements/rollup.config.js
- packages/elements/src/index.tsx
- packages/elements/tsdx.config.js
- yarn.lock
fixes: #1393 
Issue Number: #1393 
- Linaria styles are missing from NPM deployed package
- Linaria styles now included in elements index.css
> fix: #1393 fixes rollup config for elements so linaria styles are exported

- .github/workflows/release-note-update.yml
- .github/workflows/release-note.yml
- .github/workflows/release-tag.yml
- scripts/document-update/get-release-and-create-pr.js
- scripts/release/upload-artifact.js
fixes: #1333
- fix update document
> fix: #1333 ci for update doc

- .github/workflows/check-production-alive-cronjob.yml
- packages/cloud-alert/cypress/integration/aml-checklist.test.ts
- packages/cloud-alert/cypress/integration/geo-diary.test.ts
- packages/cloud-alert/cypress/integration/life-time-legal.test.ts
- packages/cloud-alert/cypress/integration/marketplace.test.ts
- scripts/release/utils.js
Changes
- Add environment for condition check
fixes: #1333
- Add condition check for pipeline when deploy specific package
> ci: #1333 add condition check for cypress test

- packages/elements/src/components/ImageInput/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components/ImageInput/index.tsx
- packages/elements/src/utils/validators/validate-require.ts
- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/developer-submit-app.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/general-information-section.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/general-information-section.tsx
fixes: #1494 #1497
Issue Number: #1494 #1497
- Name of the app is required
- Only allow support upload image in ImageInput component
I update 2 tickets in the same PR because just small validate bug in the same page 
1. #1494 `[Submit App] Should not allow containing space in "name" field`
2.  #1497 `[Submit App] Should not allow to upload file is not image (.doc, .txt, .xslx)`
> fix: #1494 #1497 fix some validate bugs on submit app page

- .github/auto_assign.yml
fixes: #1472
Issue Number: #1472
-
> chore: #1472 improve PR auto assign

- packages/cloud-alert/README.md
- packages/cloud-alert/cypress.json
- packages/cloud-alert/cypress/fixtures/search-widget/properties.json
- packages/cloud-alert/cypress/fixtures/search-widget/property-images.json
- packages/cloud-alert/cypress/fixtures/search-widget/property.json
- packages/cloud-alert/cypress/integration/search-widget.test.ts
fixes: #1287 
Issue Number: #1287 
Changes
- Add automation ping for web components
- Add fixture
> feat: #1287 automation ping for search-widget

- packages/marketplace/src/components/pages/client-app-detail/__test__/__snapshots__/app-content.test.tsx.snap
- packages/marketplace/src/components/pages/client-app-detail/__test__/__snapshots__/aside.test.tsx.snap
- packages/marketplace/src/components/pages/client-app-detail/__test__/__snapshots__/client-app-detail.test.tsx.snap
- packages/marketplace/src/components/pages/client-app-detail/__test__/__snapshots__/contact-developer-section.tsx.snap
- packages/marketplace/src/components/pages/client-app-detail/__test__/contact-developer-section.tsx
- packages/marketplace/src/components/pages/client-app-detail/app-content.tsx
- packages/marketplace/src/components/pages/client-app-detail/aside.tsx
- packages/marketplace/src/components/pages/client-app-detail/client-app-detail.tsx
- packages/marketplace/src/components/pages/client-app-detail/contact-developer-section.tsx
- packages/marketplace/src/components/pages/client-app-detail/reuse.tsx
- packages/marketplace/src/components/pages/developer-app-detail/app-detail/render-with-header.tsx
- packages/marketplace/src/styles/pages/client-app-detail.scss
fixes: https://github.com/reapit/foundations/issues/1463
-
> feat: #1463 Create modal to display App contact details

- .github/auto_assign.yml
fixes: #1472
Issue Number: #1472
-
> chore: #1472 update numberOfReviewers

- packages/elements/src/styles/vendor/bulma-overrides.scss
- packages/marketplace/src/components/pages/api-docs.tsx
- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/developer-submit-app.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/developer-submit-app.tsx
- packages/marketplace/src/components/ui/__tests__/__snapshots__/unsupport-brower.tsx.snap
- packages/marketplace/src/components/ui/__tests__/unsupport-brower.tsx
- packages/marketplace/src/components/ui/unsupport-brower.tsx
- packages/marketplace/src/styles/pages/developer-submit-app.scss
- packages/marketplace/src/utils/__tests__/brower.ts
- packages/marketplace/src/utils/brower.ts
fixes: https://github.com/reapit/foundations/issues/1421
-
> fix: #1421 fix developer portal UI bugs

- packages/aml-checklist/src/components/ui/modal/__tests__/__snapshots__/update-status.tsx.snap
- packages/aml-checklist/src/components/ui/modal/update-status.tsx
- packages/aml-checklist/src/styles/pages/checklist-detail.scss
fixes: #1425 
Issue Number: see this comment
https://github.com/reapit/foundations/issues/1425#issuecomment-638781771
> fix: #1425 update button in mobile

- packages/marketplace/src/components/ui/__tests__/terms-and-conditions-modal/__snapshots__/consumption-cost-types-table.tsx.snap
- packages/marketplace/src/components/ui/__tests__/terms-and-conditions-modal/__snapshots__/schedule2.tsx.snap
- packages/marketplace/src/components/ui/terms-and-conditions-modal/consumption-cost-types-table.tsx
fixes: #1504
Issue Number: #1504
-
> chore: #1504 update T&C text

- packages/graphql-server/package.json
- scripts/release/release-dev.js
- scripts/release/utils.js
fixes: #1333 
- Remove delete scripts when deploy
> fix: #1333 remove delete script in pipeline

- packages/marketplace/src/styles/blocks/client-app-header.scss
fixes: #
Issue Number: #1468 
- Client app detail standalone page title issues are fixed
Before:
After:
> fix: #1468 Fix client standalone app page title issues

- packages/marketplace/src/components/pages/client-app-detail/__test__/__snapshots__/app-content.test.tsx.snap
- packages/marketplace/src/components/pages/client-app-detail/__test__/__snapshots__/client-app-detail.test.tsx.snap
- packages/marketplace/src/components/pages/client-app-detail/app-content.tsx
- packages/marketplace/src/components/pages/client-app-detail/client-app-detail.tsx
fixes: https://github.com/reapit/foundations/issues/1499
-
Before 
After
> chore: #1499 Move contact developer button above back to apps button

- packages/cloud-alert/cypress/integration/graphql-server.test.ts
fixes: #1287 
Issue Number: #1287 
- Disable ping graphql server
> fix: #1287 disable ping for graphql server

- packages/marketplace/src/components/pages/developer-app-detail/__test__/__snapshots__/aside.test.tsx.snap
- packages/marketplace/src/components/pages/developer-app-detail/__test__/aside.test.tsx
- packages/marketplace/src/components/pages/developer-app-detail/app-detail/app-content/app-content.tsx
- packages/marketplace/src/components/pages/developer-app-detail/aside.tsx
- packages/marketplace/src/components/pages/developer-app-detail/developer-app-detail.tsx
fixes: #1554 
Issue Number: #1554 
- Remove unuse code
- Add app name to aside delete modal
> fix: #1554 app name missing on delete modal

- packages/web-components/src/search-widget/client/components/__tests__/__snapshots__/search-form.ts.snap
- packages/web-components/src/search-widget/client/components/__tests__/__snapshots__/search-widget.ts.snap
- packages/web-components/src/search-widget/client/components/search-form.svelte
- Safari: advance search widget button
- Safari: advance search widget button
-
> fix: widget search css

- packages/marketplace/src/utils/__tests__/validate.ts
- packages/marketplace/src/utils/form/__tests__/submit-app.ts
- packages/marketplace/src/utils/form/submit-app.ts
- packages/marketplace/src/utils/validate.ts
fixes: https://github.com/reapit/foundations/issues/1553
-
> chore: #1496 validate telephone field

- packages/marketplace/src/components/pages/admin-dev-management/admin-dev-management.tsx
fixes: https://github.com/reapit/foundations/issues/1553
-
> chore: #1553 number order column should display on one line

- packages/marketplace/src/components/pages/client-app-detail/__test__/__snapshots__/client-app-detail.test.tsx.snap
- packages/marketplace/src/components/pages/client-app-detail/client-app-detail.tsx
- packages/marketplace/src/components/pages/login.tsx
- packages/marketplace/src/components/ui/client-app-detail/__test__/client-app-install-confirmation.test.tsx
- packages/marketplace/src/components/ui/client-app-detail/__test__/client-app-uninstall-confirmation.test.tsx
- packages/marketplace/src/components/ui/client-app-detail/client-app-install-confirmation.tsx
- packages/marketplace/src/components/ui/client-app-detail/client-app-uninstall-confirmation.tsx
- packages/marketplace/src/selector/__tests__/auth.ts
- packages/marketplace/src/selector/auth.ts
- packages/marketplace/src/utils/__tests__/router-helper.test.ts
- packages/marketplace/src/utils/auth-route.ts
- packages/marketplace/src/utils/mock-helper.ts
- packages/marketplace/src/utils/router-helper.ts
fixes: #
Issue Number: #1579 
- Fix issues that cause the desktop app not refreshing app list after uninstall/install an app
> fix: #1579 Desktop bugs on standalone app page

- packages/marketplace/src/utils/__tests__/validate.ts
- packages/marketplace/src/utils/form/__tests__/register.ts
- packages/marketplace/src/utils/form/register.ts
- packages/marketplace/src/utils/validate.ts
fixes: https://github.com/reapit/foundations/issues/1593
-
> fix: #1593 register full name should be filter input values

- packages/marketplace/src/components/ui/developer-invite-member-modal/developer-invite-member-modal.tsx
- packages/marketplace/src/styles/blocks/developer-invite-member.scss
fixes: #1343 comment
Issue Number: #1343
- Fixed as comment
> chore: #1343 update subtitle - developer invite modal

- packages/elements/purify-options.js
- packages/marketplace/src/components/ui/diff-render-html.tsx
- packages/marketplace/src/styles/blocks/diff-render-html.scss
> fix: #1587 - list white css purify to class render diff add

- packages/elements/src/styles/components/toast.scss
fixes: https://github.com/reapit/foundations/issues/1632
-
> fix: #1632 toast doesn't display on IE

- packages/elements/src/components/Breadcrumb/index.ts
- packages/elements/src/index.tsx
fixes: #1393
Issue Number: #1393
- Add export for index.tsx of elements
- Remove '@/v2'
> fix: #1393 resolve problem on elements

- packages/marketplace/src/styles/blocks/diff-render-html.scss
- packages/marketplace/src/styles/blocks/diff-viewer.scss
> fix: #1520 - field value overflow on marketplace diff viewer

- packages/elements/src/components/DropdownSelect/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components/DropdownSelect/index.tsx
- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/agency-cloud-integration-section.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/developer-submit-app.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/agency-cloud-integration-section.tsx
- packages/marketplace/src/components/ui/web-component-config-modal/__test__/__snapshots__/config-modal-inner.test.tsx.snap
fixes: #1585 
Issue Number: #1585 
- Fixed integration types position to its input field
`<DropdownSelect>` of elements has an additional props `fixedPosition: boolean`
> fix: #1585 fixed integration types

- scripts/release/release-dev.js
- scripts/release/utils.js
fixes: #
- Disable `cache-control` to avoid weird CSS bug on dev
Seems like some weird CSS bugs came from browser's caches, disable it
> chore: disable cache-control on dev & release

- packages/marketplace/src/utils/form/__tests__/register.ts
- packages/marketplace/src/utils/form/register.ts
fixes: #1628 
Issue Number: #1628 
Changes
- Add validate for telephone field in developer register form
- Add test case for validate telephone number
> fix: #1628 validate telephone number for developer register form

- packages/marketplace/src/utils/form/submit-app.ts
fixes: #1528 
Issue Number: #1528 
Changes
- Remove validation for customer id field
> fix: #1528  unable to submit private app without customer id

- packages/elements/src/components/TextArea/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components/TextArea/__tests__/index.tsx
- packages/elements/src/components/TextArea/index.tsx
- packages/elements/src/components/TextAreaEditor/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components/TextAreaEditor/__tests__/index.tsx
- packages/elements/src/components/TextAreaEditor/index.tsx
- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/developer-submit-app.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/general-information-section.test.tsx.snap
fixes: #1580 
Issue Number: #1580 
- Add required props for text area and textarea editor
> fix: #1580 add required label for text area and text description

- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/authentication-flow-section.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/developer-submit-app.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/general-information-section.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/permission-section.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/redirect-uri-section.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/upload-image-section.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/authentication-flow-section.tsx
- packages/marketplace/src/components/pages/developer-submit-app/general-information-section.tsx
- packages/marketplace/src/components/pages/developer-submit-app/permission-section.tsx
- packages/marketplace/src/components/pages/developer-submit-app/redirect-uri-section.tsx
- packages/marketplace/src/components/pages/developer-submit-app/upload-image-section.tsx
fixes: #1580 
Issue Number: #1580 
- Add asterisk for required fields on submit apps
> fix: #1580 submit app should have asterisk required field

- packages/marketplace/src/components/pages/settings/__tests__/__snapshots__/client-setting.tsx.snap
- packages/marketplace/src/components/pages/settings/client-setting.tsx
- packages/marketplace/src/components/pages/settings/developer-settings/forms/forms.tsx
fixes: https://github.com/reapit/foundations/issues/1421
-
> fix: #1421 fix logout button doesnt display in IE

- packages/cognito-auth/package.json
- packages/elements/package.json
- packages/react-app-scaffolder/package.json
- packages/web-components/package.json
fixes: #1393 
Issue Number: #1393 
- Bumping version number on all NPM packages having verified beta
> chore: #1393 bump version numbers of NPM packages to release

- packages/elements/src/components/Spreadsheet/utils.tsx
- yarn.lock
> chore: update yarn lock

- packages/marketplace/src/components/pages/admin-apps/admin-apps.tsx
- packages/marketplace/src/components/pages/admin-dev-management/admin-dev-management.tsx
fixes: #1646
Issue Number: #1646
> chore: #1646 admin portal update

- packages/marketplace/src/components/pages/settings/developer-settings/forms/__tests__/contact-information-form.test.tsx
- packages/marketplace/src/components/pages/settings/developer-settings/forms/contact-information-form.tsx
fixes: #1628 
Issue Number: #1628 
- Add validate for developer information form
> fix: #1628 should not allow fill text in telephone field

- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/developer-submit-app.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/general-information-section.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/general-information-section.tsx
fixes: #1580
Issue Number: #1580 
- Remove required for category field
> fix: #1580 remove validate required for category field in submit app

- packages/aml-checklist/src/components/ui/forms/__tests__/__snapshots__/identification.tsx.snap
- packages/aml-checklist/src/components/ui/forms/identification.tsx
- packages/elements/src/components/CameraImageInput/index.tsx
- packages/elements/src/components/FileInput/index.tsx
- packages/elements/src/styles/vendor/bulma-overrides.scss
- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/developer-submit-app.test.tsx.snap
fixes: #
Issue Number: #1591 
- Clicking outside the upload button will not open a file browsing window
> fix: #1591 Upload file button issues in AML checklist

- packages/marketplace/src/components/pages/admin-billing/__tests__/__snapshots__/admin-billing.test.tsx.snap
- packages/marketplace/src/components/pages/admin-billing/__tests__/admin-billing.test.tsx
- packages/marketplace/src/components/pages/admin-billing/admin-billing.tsx
- packages/marketplace/src/components/pages/admin-billing/index.ts
- packages/marketplace/src/components/ui/menu.tsx
- packages/marketplace/src/constants/routes.ts
- packages/marketplace/src/core/__tests__/__snapshots__/router.tsx.snap
- packages/marketplace/src/core/router.tsx
> feat: #1383 - create a new section in the admin portal billing

- packages/geo-diary/src/styles/pages/map.scss
> fix: #1577 - geo diary map control displayed incorectly

- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/developer-submit-app.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/redirect-uri-section.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/redirect-uri-section.tsx
fixes: #1528 
Issue Number: #1528
> fix: #1528 add more description for customer id field

- packages/web-components/scripts/README.md
fixes: #1676 
- Follow old instruction will result unable to make search widget searchable in dev, because missing step add token to the HTML file. 
- Follow new instruction will make search widget searchable
-
> fix: #1676 update web components readme add token to html after start dev

- packages/elements/src/components/Map/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components/Map/__tests__/index.tsx
- packages/elements/src/components/Map/index.tsx
fixes: #1629 
Issue Number: #1629 
- Add Default zoom for map
> fix: #1629 set default zoom for maps

- scripts/release/utils.js
fixes: #
- Add run cypress after deploy cypress
> ci: pipeline add and run test after deploy serverless

- scripts/release/utils.js
fixes: #1333
- FIx deployment process for serverless in web-components
> fix: #1333 pipeline deploy for web-components

- scripts/release/utils.js
fixes: #1333 
- Add run cypress test for web components
> ci: #1333 add run cypress test after deploy serverless for web components

- packages/elements/tsdx.config.js
- packages/marketplace/package.json
- scripts/webpack/exclude-packages.js
- scripts/webpack/webpack.base.prod.js
fixes: #1393
Issue Number: #1393 
- Babel transpile for linaria cx function
> fix: #1393 linaria issue on cx

- .github/workflows/release-note-update.yml
- .github/workflows/release-note.yml
- .github/workflows/release.yml
fixes: #1333
- Remove unuse code in pipeline
> fix: #1333 remove unuse code in pipeline

- packages/elements/src/utils/validators/validate-require.ts
fixes: https://github.com/reapit/foundations/issues/1727
-
> fix: #1727 fix Expiry Date field is showed error message when having data in it

- packages/foundations-ts-definitions/package.json
- packages/foundations-ts-definitions/scripts/fetch-marketplace-definition.js
- packages/foundations-ts-definitions/scripts/format-code.js
- packages/foundations-ts-definitions/types/index.ts
- packages/foundations-ts-definitions/types/marketplace-api-schema.ts
- packages/foundations-ts-definitions/types/marketplace-traffic-event-schema.ts
- packages/foundations-ts-definitions/types/platform-schema.ts
fixes: #1704
- Can't fetch definition
- Able to fetch definition, including traffic event
-
> fix: #1704 update ts def to include traffic event

- packages/api-docs-lamda/README.md
- packages/api-docs-lamda/jest.config.js
- packages/api-docs-lamda/package.json
- packages/api-docs-lamda/serverless.yml
- packages/api-docs-lamda/src/__tests__/index.test.ts
- packages/api-docs-lamda/src/index.ts
- packages/api-docs-lamda/tsconfig.json
- packages/api-docs-lamda/webpack.config.js
- packages/marketplace/src/constants/iframe-urls.ts
fixes: #1703 
Issue Number: #1703 
- Adds a proxy for requests to Gitbook so we can set X-Frame policy to allow docs in dev portal
> feat: #1703 adds lambda to proxy gitbook

- packages/api-docs-lamda/serverless.yml
fixes: #1703 
Issue Number: #1703 
- Allows wildcard linking so we can deep link to docs
> fix: #1703 resolve routing issue by allowing wildcard

- packages/marketplace/src/components/ui/__tests__/terms-and-conditions-modal/__snapshots__/consumption-cost-types-table.tsx.snap
- packages/marketplace/src/components/ui/__tests__/terms-and-conditions-modal/__snapshots__/schedule2.tsx.snap
- packages/marketplace/src/components/ui/terms-and-conditions-modal/consumption-cost-types-table.tsx
- packages/marketplace/src/components/ui/terms-and-conditions-modal/term-and-conditions.tsx
fixes: #1714
Issue Number: #1714 
- Update term and condition
- Update snapshot
> fix: #1714 update developer registration t and c

- packages/aml-checklist/src/components/ui/modal/profile/__tests__/__snapshots__/profile.tsx.snap
- packages/aml-checklist/src/components/ui/modal/profile/form-schema/validation-schema.ts
fixes: https://github.com/reapit/foundations/issues/1727
-
> fix: #1727 fix birthday field validation

- packages/marketplace/src/components/pages/settings/developer-settings/forms/__tests__/contact-information-form.test.tsx
- packages/marketplace/src/components/pages/settings/developer-settings/forms/contact-information-form.tsx
- packages/marketplace/src/constants/error-messages.ts
- packages/marketplace/src/utils/form/__tests__/developer-settings-contact-information.ts
- packages/marketplace/src/utils/form/__tests__/register.ts
- packages/marketplace/src/utils/form/developer-settings-contact-information.ts
- packages/marketplace/src/utils/form/register.ts
fixes: https://github.com/reapit/foundations/issues/1593
-
> fix: #1593 fix fullname field validation

- packages/geo-diary-v2/package.json
- packages/site-builder/package.json
fixes: #1411
Issue Number: #1411 
-
> fix: #1411 webpack build error on site builder and geo-diary-v2

- scripts/release/utils.js
> fix: release production foundation ts definition utils

- .github/workflows/check-production-alive-cronjob.yml
- .github/workflows/foundation-ts-definition-cronjob.yml
- .github/workflows/pr-ci.yml
- .github/workflows/release-dev.yml
- .github/workflows/release-note-update.yml
- .github/workflows/release-note.yml
- .github/workflows/release-tag.yml
- .github/workflows/release.yml
- package.json
- packages/aml-checklist/package.json
- packages/cognito-auth/package.json
- packages/cognito-custom-mail-lambda/package.json
- packages/elements/package.json
- packages/geo-diary-v2/package.json
- packages/geo-diary/package.json
- packages/graphql-server/package.json
- packages/lifetime-legal/package.json
- packages/marketplace/package.json
- packages/smb-onboarder/package.json
- packages/utils/package.json
- packages/web-components-config-server/package.json
- packages/web-components/package.json
fixes: #1748 
Issue Number: #1748 
- Improve speed of the pipeline by only run change packages
> ci: #1748 improve speed for pipeline

- .github/workflows/release-dev.yml
fixes: #1748 
- Bug fix when run release-dev on master
> fix: #1748 pipeline error when optimize

- packages/marketplace/src/components/ui/__tests__/__snapshots__/app-confirm-install.tsx.snap
- packages/marketplace/src/components/ui/__tests__/app-confirm-install.tsx
- packages/marketplace/src/components/ui/app-confirm-install.tsx
> refactor: #1325 Refactor app confirm install using react-redux hooks

- packages/marketplace/src/components/ui/developer-settings/billing/__tests__/__snapshots__/delete-confirm.test.tsx.snap
- packages/marketplace/src/components/ui/developer-settings/billing/__tests__/__snapshots__/subscriptions.test.tsx.snap
- packages/marketplace/src/components/ui/developer-settings/billing/delete-confirm.tsx
- packages/marketplace/src/components/ui/developer-settings/billing/subscriptions.tsx
fixes: #1718
Issue Number: #1718
> chore: #1718 update Confirm Cancellation modal title, subtext

- .browserslistrc
- package.json
- postcss.config.js
- scripts/webpack/webpack.config.dev.js
- scripts/webpack/webpack.config.prod.js
- yarn.lock
fixes: #1411 
Issue Number: #1411 
-
> fix: #1411 add post css for autoprefixer

- packages/cloud-alert/cypress/fixtures/web-components-config-server/web-components-config.json
> fix: pipeline alert error

- packages/marketplace/src/components/pages/admin-apps/__tests__/__snapshots__/admin-apps.test.tsx.snap
- packages/marketplace/src/components/ui/__tests__/__snapshots__/app-delete.tsx.snap
- packages/marketplace/src/components/ui/__tests__/app-delete.tsx
- packages/marketplace/src/components/ui/app-delete.tsx
- packages/marketplace/src/selector/__tests__/app-delete.test.ts
- packages/marketplace/src/selector/app-delete.ts
> refactor: #1325 Refactor app delete using react-redux hooks

- packages/marketplace/src/components/pages/admin-approvals/__tests__/__snapshots__/admin-approvals.test.tsx.snap
- packages/marketplace/src/components/ui/__tests__/__snapshots__/approve-revision-modal.tsx.snap
- packages/marketplace/src/components/ui/__tests__/approve-revision-modal.tsx
- packages/marketplace/src/components/ui/approve-revision-modal.tsx
- packages/marketplace/src/services/apps.ts
> refactor: #1325 Refactor approve revision modal using react-redux hooks

- .github/workflows/check-production-alive-cronjob.yml
- .github/workflows/foundation-ts-definition-cronjob.yml
- .github/workflows/pr-ci.yml
- .github/workflows/release-dev.yml
- .github/workflows/release-note-update.yml
- .github/workflows/release-tag.yml
- packages/geo-diary-v2/src/core/__tests__/__snapshots__/app.tsx.snap
- packages/graphql-server/package.json
- packages/smb-onboarder/src/components/pages/login/__tests__/__snapshots__/login.test.tsx.snap
- packages/smb-onboarder/src/components/pages/login/__tests__/__snapshots__/style.test.tsx.snap
- packages/smb-onboarder/src/components/pages/negotiators/__tests__/__snapshots__/negotiators.test.tsx.snap
- packages/smb-onboarder/src/components/pages/offices/__tests__/__snapshots__/offices.tsx.snap
- packages/smb-onboarder/src/components/ui/__tests__/__snapshots__/upload-result-modal.tsx.snap
- packages/smb-onboarder/src/components/ui/negotiators-list/__tests__/__snapshots__/negotiators-list.test.tsx.snap
- packages/smb-onboarder/src/components/ui/offices-tab/__tests__/__snapshots__/offices-tab.tsx.snap
- packages/smb-onboarder/src/core/__tests__/__snapshots__/app.tsx.snap
- yarn.lock
> fix: failing pipeline

- packages/foundations-ts-definitions/package.json
fixes: #1714 
https://github.com/reapit/foundations/runs/779637465?check_suite_focus=true
-
> fix: #1714 add un-implemented build prod script to ts def package

- packages/elements/src/components/HelpGuide/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components/HelpGuide/__tests__/index.tsx
- packages/elements/src/components/HelpGuide/context.tsx
- packages/elements/src/components/HelpGuide/index.tsx
- packages/marketplace/src/components/pages/__tests__/__snapshots__/client-welcome.tsx.snap
- packages/marketplace/src/components/pages/__tests__/__snapshots__/developer-welcome.tsx.snap
fixes: #1743 
Issue Number: #1743 
- Responsive bug on welcome screen
http://g.recordit.co/0ne58g4Yms.gif
> fix: #1743 responsive error on wizard

- packages/marketplace/src/components/ui/__stubs__/developer-installations-chart-data.ts
- packages/marketplace/src/components/ui/developer-analytics/detailed/__test__/__snapshots__/installation-app-section.test.tsx.snap
- packages/marketplace/src/components/ui/developer-analytics/detailed/__test__/installation-app-section.test.tsx
- packages/marketplace/src/components/ui/developer-analytics/detailed/detailed-tab.tsx
- packages/marketplace/src/components/ui/developer-analytics/detailed/installation-app-section.tsx
- packages/marketplace/src/components/ui/developer-installations-chart.tsx
- packages/marketplace/src/utils/developer-analytics.ts
fixes: https://github.com/reapit/foundations/issues/1776
-
> chore: #1776 Update Installations Graph and Current Installations list

- packages/marketplace/src/components/pages/admin-dev-management/__tests__/__snapshots__/admin-dev-management.test.tsx.snap
- packages/marketplace/src/components/ui/__tests__/__snapshots__/developer-set-status.tsx.snap
- packages/marketplace/src/components/ui/__tests__/developer-set-status.tsx
- packages/marketplace/src/components/ui/developer-set-status.tsx
- packages/marketplace/src/selector/__tests__/developer-set-status.test.ts
- packages/marketplace/src/selector/developer-set-status.ts
> refactor: #1325 Refactor developer set status using react-redux hooks

- packages/marketplace/src/components/pages/settings/developer-settings-billing-tab/accounts-information-form/__tests__/__snapshots__/accounts-information-form.test.tsx.snap
- packages/marketplace/src/components/pages/settings/developer-settings-billing-tab/accounts-information-form/__tests__/__snapshots__/direct-debit-section.test.tsx.snap
- packages/marketplace/src/components/pages/settings/developer-settings-billing-tab/accounts-information-form/__tests__/direct-debit-section.test.tsx
- packages/marketplace/src/components/pages/settings/developer-settings-billing-tab/accounts-information-form/accounts-information-form.tsx
- packages/marketplace/src/components/pages/settings/developer-settings-billing-tab/accounts-information-form/direct-debit-section.tsx
fixes: #1765
Issue Number: #1765
> feat: #1765 Updates to the ‘Account Information’ section (Billing Tab)

- packages/marketplace/src/components/ui/__tests__/__snapshots__/toast-message.test.tsx.snap
- packages/marketplace/src/components/ui/__tests__/__snapshots__/toast.test.tsx.snap
- packages/marketplace/src/components/ui/__tests__/toast-message.test.tsx
- packages/marketplace/src/components/ui/__tests__/toast.test.tsx
- packages/marketplace/src/components/ui/toast-message.tsx
- packages/marketplace/src/components/ui/toast.tsx
- packages/marketplace/src/core/__tests__/__snapshots__/app.tsx.snap
- packages/marketplace/src/selector/__tests__/error.test.ts
- packages/marketplace/src/selector/__tests__/notification-message.ts
- packages/marketplace/src/selector/error.ts
- packages/marketplace/src/selector/notification-message.ts
> refactor: #1325 Refactor toast messages using react-redux hooks

- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/developer-submit-app.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/developer-submit-app.tsx
- packages/marketplace/src/components/pages/developer-submit-app/form-schema/form-fields.ts
- packages/marketplace/src/components/pages/developer-submit-app/form-schema/validation-schema.ts
fixes: #1769 
Issue Number: #1769 
- Should not allow special character
> fix: #1769 app name should not allow special char

- packages/marketplace/src/components/pages/developer-submit-app/__test__/__snapshots__/developer-submit-app.test.tsx.snap
- packages/marketplace/src/components/pages/developer-submit-app/form-schema/form-fields.ts
- packages/marketplace/src/components/pages/developer-submit-app/form-schema/validation-schema.ts
fixes: #1770 
Issue Number: #1770 
-
> fix: #1770 submit app should limit number char fields

- packages/marketplace/src/components/ui/developer-confirm-subscription.tsx
fixes: https://github.com/reapit/foundations/issues/1717
-
> chore: fix typo

- packages/marketplace/src/components/pages/settings/developer-settings-organisation-tab/__tests__/__snapshots__/members.test.tsx.snap
- packages/marketplace/src/components/pages/settings/developer-settings-organisation-tab/__tests__/members.test.tsx
- packages/marketplace/src/components/pages/settings/developer-settings-organisation-tab/members.tsx
- packages/marketplace/src/components/ui/__tests__/__snapshots__/organisation-set-member-status-modal.tsx.snap
- packages/marketplace/src/components/ui/__tests__/organisation-set-member-status-modal.tsx
- packages/marketplace/src/components/ui/organisation-set-member-status-modal.tsx
fixes: https://github.com/reapit/foundations/issues/1346
-
> feat: #1346 Create set member status modal

- packages/elements/src/components/HelpGuide/__styles__/styles.ts
- packages/elements/src/components/HelpGuide/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components/HelpGuide/fade.tsx
- packages/elements/src/components/HelpGuide/index.tsx
- packages/elements/src/styles/components/help-guide.scss
- packages/marketplace/src/components/pages/__tests__/__snapshots__/client-welcome.tsx.snap
- packages/marketplace/src/components/pages/__tests__/__snapshots__/developer-welcome.tsx.snap
- packages/marketplace/src/components/pages/client-welcome.tsx
- packages/marketplace/src/components/pages/developer-welcome.tsx
- packages/marketplace/src/styles/pages/developer-welcome.scss
fixes: #1743 
Issue Number: #1743 
- Bug fixing
- Refactor helper guide
> fix: #1743 css issue on helper

- packages/elements/src/components/DropdownSelect/dropdown-select.stories.tsx
- packages/elements/src/components/DropdownSelect/index.tsx
fixes: #1847
Issue Number: #1847 
when adding a new tag in `mode = 'tags'`, the newly added tag will become empty like this
- When adding a new tag in `mode = 'tags'`, the newly added tag should be added to the list
- Nothing is changed in  `mode = 'multiple'` (which we're currently using in marketplace)
> feat: #1847 fix <DropdownSelect> tags mode

- packages/marketplace/src/components/ui/__tests__/__snapshots__/call-to-action.tsx.snap
- packages/marketplace/src/components/ui/call-to-action.tsx
fixes: #1874 
Issue Number: #1874 
- Fix bug
- Update snapshot
> fix: #1874 button login register should on the right

- packages/marketplace/src/components/pages/settings/__tests__/__snapshots__/tabs.test.tsx.snap
- packages/marketplace/src/components/pages/settings/__tests__/tabs.test.tsx
- packages/marketplace/src/components/pages/settings/developer-settings-billing-tab/__tests__/__snapshots__/developer-settings-billing-tab.tsx.snap
- packages/marketplace/src/components/pages/settings/developer-settings-billing-tab/__tests__/developer-settings-billing-tab.tsx
- packages/marketplace/src/components/pages/settings/developer-settings-billing-tab/developer-settings-billing-tab.tsx
- packages/marketplace/src/components/pages/settings/developer-settings/__tests__/__snapshots__/developer-settings.test.tsx.snap
- packages/marketplace/src/components/pages/settings/developer-settings/__tests__/developer-settings.test.tsx
- packages/marketplace/src/components/pages/settings/developer-settings/developer-settings.tsx
- packages/marketplace/src/components/pages/settings/tabs.tsx
fixes: https://github.com/reapit/foundations/issues/1870
-
> chore: #1870 show profile and billing to non-admins

- packages/marketplace/src/components/pages/developer-webhooks/__test__/__snapshots__/developer-webhooks.test.tsx.snap
- packages/marketplace/src/components/pages/developer-webhooks/developer-webhooks.tsx
fixes: #1876
Issue Number: #1876
> chore: #1876 update webhook subtext

- packages/marketplace/src/sagas/client.ts
fixes: https://github.com/reapit/foundations/issues/1848
-
> chore: #1848 add developerId to filter get app api

- packages/marketplace/src/components/pages/developer-edit-app/form-schema/form-fields.ts
- packages/marketplace/src/components/ui/submit-app-wizard/form-fields.ts
fixes: #1769 
Issue Number: #1769 
-
> fix: #1769 change text for submit app error message on name field

- packages/marketplace/src/components/pages/developer-edit-app/__test__/__snapshots__/upload-image-section.test.tsx.snap
- packages/marketplace/src/components/pages/developer-edit-app/developer-edit-app.tsx
- packages/marketplace/src/components/pages/developer-edit-app/form-schema/validation-schema.ts
- packages/marketplace/src/components/pages/developer-edit-app/upload-image-section.tsx
fixes: #1900 
Issue Number: #1900 
- Validation bug on featureImage
> fix: #1900 validation bug in submit app

- packages/marketplace/src/components/pages/authentication/__test__/__snapshots__/authentication.test.tsx.snap
- packages/marketplace/src/components/pages/authentication/__test__/authentication.test.tsx
- packages/marketplace/src/components/pages/authentication/authentication.tsx
fixes: #1887
Issue Number: #1887
> fix: #1887 Update the text on the ‘Agency Cloud User Licence’ modal

- packages/marketplace/src/actions/submit-revision.ts
- packages/marketplace/src/components/pages/developer-edit-app/__test__/developer-edit-app.test.tsx
- packages/marketplace/src/components/pages/developer-edit-app/developer-edit-app.tsx
- packages/marketplace/src/sagas/__tests__/submit-revision.ts
- packages/marketplace/src/sagas/submit-revision.ts
fixes: https://github.com/reapit/foundations/issues/1902
-
> fix: #1902 fix User can't edit the apps before click edit detail 3 times

- packages/marketplace/src/components/pages/admin-apps/__tests__/__snapshots__/admin-apps.test.tsx.snap
- packages/marketplace/src/components/pages/admin-apps/admin-apps.tsx
fixes: #1926 
Issue Number: #1926
> fix: #1926 [Marketplace][Admin] Dev Management search button align

- packages/geo-diary-v2/src/components/pages/login/__styles__/index.ts
fixes: #
- Remove import style from geo-diary-v2 to fix pipeline error
> fix: remove import style from geo-diary-v2 to fix pipeline error

- packages/elements/src/components/Input/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components/Input/__tests__/index.tsx
- packages/elements/src/components/Input/index.tsx
- packages/elements/src/styles/vendor/bulma-overrides.scss
- packages/elements/src/utils/validators/error-messages.ts
- packages/marketplace/src/components/ui/submit-app-wizard/steps/__tests__/__snapshots__/step-before-you-start.test.tsx.snap
- packages/marketplace/src/components/ui/submit-app-wizard/steps/__tests__/__snapshots__/step-chose-auth-type.tsx.snap
- packages/marketplace/src/components/ui/submit-app-wizard/steps/__tests__/__snapshots__/step-create-new-app.test.tsx.snap
- packages/marketplace/src/components/ui/submit-app-wizard/steps/__tests__/__snapshots__/step-grant-permisions.test.tsx.snap
- packages/marketplace/src/components/ui/submit-app-wizard/steps/__tests__/__snapshots__/step-input-app-name.test.tsx.snap
- packages/marketplace/src/components/ui/submit-app-wizard/steps/__tests__/__snapshots__/step-input-authentication-uris.test.tsx.snap
- packages/marketplace/src/components/ui/submit-app-wizard/steps/__tests__/__snapshots__/step-submit-app-success.test.tsx.snap
- packages/marketplace/src/components/ui/submit-app-wizard/steps/__tests__/step-before-you-start.test.tsx
- packages/marketplace/src/components/ui/submit-app-wizard/steps/step-before-you-start.tsx
- packages/marketplace/src/components/ui/submit-app-wizard/steps/step-chose-auth-type.tsx
- packages/marketplace/src/components/ui/submit-app-wizard/steps/step-create-new-app.tsx
- packages/marketplace/src/components/ui/submit-app-wizard/steps/step-grant-permisions.tsx
- packages/marketplace/src/components/ui/submit-app-wizard/steps/step-input-app-name.tsx
- packages/marketplace/src/components/ui/submit-app-wizard/steps/step-input-authentication-uris.tsx
- packages/marketplace/src/components/ui/submit-app-wizard/steps/step-submit-app-success.tsx
- packages/marketplace/src/constants/error-messages.ts
- packages/marketplace/src/styles/blocks/submit-app-wizard.scss
fixes: https://github.com/reapit/foundations/issues/1921
-
> chore: #1921 Update ui to the submit app wizard

- packages/marketplace/src/components/pages/admin-dev-management/__tests__/__snapshots__/admin-dev-management.test.tsx.snap
- packages/marketplace/src/components/pages/admin-dev-management/admin-dev-management.tsx
- packages/marketplace/src/components/ui/admin-dev-management-filter-form.tsx
fixes: #1927
Issue Number: #1927 
- My current day is 02/07, but can't select day 02
- Can select current day
> fix: #1927 [Marketplace][Admin] Min & Max search date of Dev Management

- packages/marketplace/src/components/ui/developer-edition-modal/__tests__/__snapshots__/developer-edition-content.tsx.snap
- packages/marketplace/src/components/ui/developer-edition-modal/developer-edition-content.tsx
fixes: https://github.com/reapit/foundations/issues/1940
-
> chore: #1940 Update the text on the ‘Agency Cloud Developer Edition’ modal

- packages/marketplace/src/components/pages/developer-edit-app/__test__/__snapshots__/general-information-section.test.tsx.snap
- packages/marketplace/src/components/pages/developer-edit-app/__test__/__snapshots__/upload-image-section.test.tsx.snap
- packages/marketplace/src/components/pages/developer-edit-app/__test__/developer-edit-app.test.tsx
- packages/marketplace/src/components/pages/developer-edit-app/__test__/general-information-section.test.tsx
- packages/marketplace/src/components/pages/developer-edit-app/__test__/upload-image-section.test.tsx
- packages/marketplace/src/components/pages/developer-edit-app/developer-edit-app.tsx
- packages/marketplace/src/components/pages/developer-edit-app/form-schema/validation-schema.ts
- packages/marketplace/src/components/pages/developer-edit-app/general-information-section.tsx
- packages/marketplace/src/components/pages/developer-edit-app/upload-image-section.tsx
fixes: #1934 
Issue Number: #1934 
- Fix validation for non list app
> fix: #1934 validation required for non list app

- packages/marketplace/src/components/ui/submit-app-wizard/steps/__tests__/__snapshots__/step-create-new-app.test.tsx.snap
- packages/marketplace/src/components/ui/submit-app-wizard/steps/step-create-new-app.tsx
fixes: #1940 
Issue Number: #1940 
- Removes some redundant text for release
> fix: #1940 remove redundant text

- packages/marketplace/src/components/ui/submit-app-wizard/__tests__/submit-app-wizard-modal.test.tsx
- packages/marketplace/src/components/ui/submit-app-wizard/submit-app-wizard-modal.tsx
fixes: #1953 
Issue Number: #1953 
- Submit App Wizard modal won't be closed when pressing Enter
> fix: #1953 Fix closing submit app modal issue when pressing enter

- packages/marketplace/src/components/pages/__tests__/__snapshots__/developer-help.test.tsx.snap
- packages/marketplace/src/components/pages/developer-help.tsx
- packages/marketplace/src/components/ui/__tests__/__snapshots__/help-item-list.tsx.snap
fixes: #1939 
Issue Number: #1939 
- Small text change
> fix: text change

- .github/workflows/release-note-update.yml
fixes: #
- To fetch all revision of workflow instead of fetch HEAD from checkout actions
> fix: update release note workflow

- packages/marketplace/src/components/ui/developer-analytics/cost-explorer/cost-explorer-component/cost-explorer-table.tsx
fixes: https://github.com/reapit/foundations/issues/1962
-
> chore: #1962 Remove email casing on the ‘Cost Explorer’

- packages/cognito-auth/package.json
- packages/elements/package.json
- packages/elements/src/components/ImageInput/__tests__/index.tsx
- packages/elements/src/components/ImageInput/index.tsx
> fix: #1978 elements production issue cant resolve reapit utils

- packages/graphql-server/src/__tests__/index.test.ts
- packages/graphql-server/src/index.ts
- packages/graphql-server/src/resolvers/appointments/resolvers.ts
- packages/graphql-server/src/resolvers/appointments/types.graphql
- packages/graphql-server/src/resolvers/configurations/__tests__/dataloader.test.ts
- packages/graphql-server/src/resolvers/configurations/dataloader.ts
- packages/graphql-server/src/resolvers/properties/__tests__/dataloader.test.ts
- packages/graphql-server/src/resolvers/properties/dataloader.ts
- packages/graphql-server/src/schema.graphql
- packages/graphql-server/src/utils/__tests__/check-permission.test.ts
fixes: #1037 
- Add resolver relation for property model
> feat: #1037 add data loader relation for appointment

- scripts/release/utils.js
fixes: #
- Add package name so we can release from our own branches
> chore: add packages for releasing admin-portal & developer-portal

- packages/geo-diary-v2/src/components/pages/appointment/__styles__/index.ts
- packages/geo-diary-v2/src/components/pages/appointment/appointment.tsx
- packages/geo-diary-v2/src/components/pages/appointment/get-appointments.graphql
- packages/geo-diary-v2/src/components/pages/appointment/mobile-layout.tsx
- packages/geo-diary-v2/src/components/ui/appointment-list/__tests__/__snapshots__/appointment-list.test.tsx.snap
- packages/geo-diary-v2/src/components/ui/appointment-list/appointment-list.tsx
- packages/geo-diary-v2/src/components/ui/appointment-tile/__tests__/__snapshots__/appointment-tile.test.tsx.snap
- packages/geo-diary-v2/src/components/ui/appointment-tile/__tests__/appointment-tile.test.tsx
- packages/geo-diary-v2/src/components/ui/appointment-tile/appointment-tile.tsx
- packages/geo-diary-v2/src/components/ui/appointment-time/__styles__/index.ts
- packages/geo-diary-v2/src/components/ui/appointment-time/__tests__/__snapshots__/appointment-time.test.tsx.snap
- packages/geo-diary-v2/src/components/ui/appointment-time/appointment-time.tsx
- packages/geo-diary-v2/src/components/ui/map-pannel/__styles__/index.ts
- packages/geo-diary-v2/src/components/ui/map-pannel/__test__/__snapshots__/map-pannel.test.tsx.snap
- packages/geo-diary-v2/src/components/ui/map-pannel/__test__/map-pannel.test.tsx
- packages/geo-diary-v2/src/components/ui/map-pannel/index.ts
- packages/geo-diary-v2/src/components/ui/map-pannel/map-pannel.tsx
- packages/geo-diary-v2/src/components/ui/map/__test__/__snapshots__/map.test.tsx.snap
- packages/geo-diary-v2/src/components/ui/map/map.tsx
- packages/geo-diary-v2/src/graphql/__mocks__/appointment.ts
- packages/geo-diary-v2/src/graphql/__mocks__/appointments.ts
- packages/geo-diary-v2/src/graphql/fragments/list-item-model.graphql
- packages/geo-diary-v2/src/graphql/fragments/property-model.graphql
- packages/geo-diary-v2/src/types/global.d.ts
fixes: #1037 
- Integrate with map component
> feat: #1037 integrate with map component

- packages/api-docs-lamda/src/index.ts
fixes: #
Issue Number: #1997 
- Adds standalone dev portal to docs proxy
> fix: #1997 updated control list for docs proxy

- packages/admin-portal/src/components/pages/__tests__/__snapshots__/login.test.tsx.snap
- packages/admin-portal/src/components/pages/__tests__/login.test.tsx
- packages/admin-portal/src/components/pages/login.tsx
- packages/admin-portal/src/constants/routes.ts
- packages/admin-portal/src/core/__tests__/__snapshots__/router.tsx.snap
- packages/admin-portal/src/core/__tests__/private-route-wrapper.tsx
- packages/admin-portal/src/core/private-route-wrapper.tsx
- packages/admin-portal/src/core/router.tsx
- packages/admin-portal/src/reducers/auth.ts
- packages/admin-portal/src/sagas/__tests__/auth.ts
- packages/admin-portal/src/sagas/auth.ts
- packages/admin-portal/src/utils/__tests__/route-dispatcher.ts
- packages/admin-portal/src/utils/route-dispatcher.ts
fixes: https://github.com/reapit/foundations/issues/1916
-
> chore: #1916 Purge unused code from admin portal: login page

- packages/graphql-server/src/__mocks__/context.ts
- packages/graphql-server/src/index.ts
- packages/graphql-server/src/resolvers/appointments/__tests__/resolvers.test.ts
- packages/graphql-server/src/resolvers/appointments/resolvers.ts
- packages/graphql-server/src/resolvers/appointments/types.graphql
- packages/graphql-server/src/resolvers/configurations/__tests__/dataloader.test.ts
- packages/graphql-server/src/resolvers/negotiators/__tests__/dataloader.ts
- packages/graphql-server/src/resolvers/negotiators/dataloader.ts
- packages/graphql-server/src/resolvers/offices/__tests__/dataloader.test.ts
- packages/graphql-server/src/resolvers/offices/dataloader.ts
- packages/graphql-server/src/resolvers/properties/__tests__/dataloader.test.ts
- packages/graphql-server/src/schema.graphql
fixes: #1037 
- Add more resolver for appointment model
> feat: #1037 add relation resolver for query appointment

- packages/elements/src/index.tsx
fixes: #1037 
- Add style for rc-dialog
> feat: #1037 add style for rc dialog

- packages/developer-portal/package.json
- packages/developer-portal/src/components/pages/settings/developer-settings-billing-tab/accounts-information-form/__tests__/__snapshots__/accounts-information-form.test.tsx.snap
- packages/developer-portal/src/components/pages/settings/developer-settings-billing-tab/accounts-information-form/__tests__/__snapshots__/contact-information-section.test.tsx.snap
- packages/developer-portal/src/components/pages/settings/developer-settings-billing-tab/accounts-information-form/__tests__/__snapshots__/direct-debit-section.test.tsx.snap
- packages/developer-portal/src/components/pages/settings/developer-settings-billing-tab/accounts-information-form/__tests__/__snapshots__/reapit-reference-section.test.tsx.snap
- packages/developer-portal/src/components/pages/settings/developer-settings-billing-tab/accounts-information-form/__tests__/accounts-information-form.test.tsx
- packages/developer-portal/src/components/pages/settings/developer-settings-billing-tab/accounts-information-form/__tests__/direct-debit-section.test.tsx
- packages/developer-portal/src/components/pages/settings/developer-settings-billing-tab/accounts-information-form/__tests__/reapit-reference-section.test.tsx
- packages/developer-portal/src/components/pages/settings/developer-settings-billing-tab/accounts-information-form/__tests__/validation-schema.ts
- packages/developer-portal/src/components/pages/settings/developer-settings-billing-tab/accounts-information-form/accounts-information-form.tsx
- packages/developer-portal/src/components/pages/settings/developer-settings-billing-tab/accounts-information-form/direct-debit-section.tsx
- packages/developer-portal/src/components/pages/settings/developer-settings-billing-tab/accounts-information-form/form-schema/form-fields.ts
- packages/developer-portal/src/components/pages/settings/developer-settings-billing-tab/accounts-information-form/form-schema/validation-schema.ts
- packages/developer-portal/src/components/ui/developer-traffic-chart.tsx
- packages/developer-portal/src/components/ui/developer-traffic-table.tsx
- packages/developer-portal/src/reducers/app-usage-stats.ts
- packages/developer-portal/src/sagas/__stubs__/app-usage-stats.ts
- packages/developer-portal/src/sagas/__tests__/settings.ts
- packages/developer-portal/src/sagas/settings.ts
- packages/developer-portal/src/services/statistics.ts
- packages/developer-portal/src/utils/app-usage-stats.ts
fixes: #1987 
Issue Number: #1897 
Layout looks difference. There maybe a task to update the UI match the spec. No requirement to alter UI.
-
> chore: #1987 update billing page

- packages/cloud-alert/cypress/fixtures/search-widget/properties.json
> fix: error pipeline on cloud alert

- package.json
- packages/geo-diary-v2/manifest.json
- packages/geo-diary-v2/package.json
- packages/geo-diary-v2/src/core/index.tsx
- packages/geo-diary-v2/src/core/service-worker.ts
- scripts/webpack/webpack.pwa.prod.js
- yarn.lock
fixes: #1038 
Issue Number: #1038 
- Add workbox for webpack build
> feat: #1038 pwa for geo-diary-v2

- packages/geo-diary-v2/src/components/pages/login/__styles__/index.ts
- packages/geo-diary-v2/src/components/ui/appointment-time/appointment-time.tsx
- packages/geo-diary-v2/src/components/ui/list-and-map-tab/__styles__/index.ts
- packages/geo-diary-v2/src/components/ui/travel-mode/travel-mode.tsx
fixes: #1037 
- Fix initial time and travel mode
> fix: #1037 initial default for travel mode and time

- packages/developer-portal/src/components/pages/analytics/detailed/__test__/detailed-tab.test.tsx
- packages/developer-portal/src/components/pages/analytics/detailed/detailed-tab.tsx
- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/__test__/__snapshots__/default-filter-group.test.tsx.snap
- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/__test__/__snapshots__/filter-bar.test.tsx.snap
- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/__test__/default-filter-group.test.tsx
- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/__test__/filter-bar.test.tsx
- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/default-filter-group.tsx
- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/filter-bar.tsx
- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/filter-form.tsx
fixes: https://github.com/reapit/foundations/issues/1961
-
> chore: #1961 Update the filtering options on the ‘Detailed’ tab in ‘Analytics’

- packages/developer-portal/src/components/pages/register/__tests__/register.test.tsx
- packages/developer-portal/src/components/pages/register/register.tsx
fixes: #2076 
Issue Number: #2076 
- Fix bug on login page
> fix: #2076 register page bug

- packages/marketplace/src/components/pages/handle-legacy-routes/__tests__/__snapshots__/handle-legacy-admin-routes-modal.tsx.snap
- packages/marketplace/src/components/pages/handle-legacy-routes/__tests__/handle-legacy-admin-routes-modal.tsx
- packages/marketplace/src/components/pages/handle-legacy-routes/handle-legacy-admin-routes-modal.tsx
> fix: #1997 fix admin redirect modal on marketplace

- packages/geo-diary-v2/jest.config.js
- packages/geo-diary-v2/src/components/ui/appointment-detail-modal/appointment-detail-modal.tsx
- packages/geo-diary-v2/src/components/ui/map/__test__/__mocks__/create-google-map.ts
- packages/geo-diary-v2/src/components/ui/map/__test__/__snapshots__/gmaps.test.tsx.snap
- packages/geo-diary-v2/src/components/ui/map/__test__/__snapshots__/map.test.tsx.snap
- packages/geo-diary-v2/src/components/ui/map/__test__/gmaps.test.tsx
- packages/geo-diary-v2/src/components/ui/map/gmaps.tsx
- packages/geo-diary-v2/src/components/ui/map/map.tsx
fixes: #2027 
Issue Number: #2027 
- Google Map issue
> fix: #2027 geo-diary map issue

- packages/geo-diary-v2/src/components/ui/appointment-tile/__tests__/__snapshots__/appointment-tile.test.tsx.snap
- packages/geo-diary-v2/src/components/ui/appointment-tile/appointment-tile.tsx
- packages/geo-diary-v2/src/components/ui/appointment-time/appointment-time.tsx
- packages/geo-diary-v2/src/components/ui/eta-button/__tests__/__snapshots__/eta-button.test.tsx.snap
- packages/geo-diary-v2/src/components/ui/eta-button/eta-button.tsx
- packages/geo-diary-v2/src/components/ui/map/__test__/__snapshots__/map.test.tsx.snap
- packages/geo-diary-v2/src/components/ui/map/gmaps.tsx
- packages/geo-diary-v2/src/components/ui/map/map.tsx
fixes: #2027 
Issue Number: #2027 
- Fix style bug on geo-diary v2
> fix: #2027 fix  layout issue on geo-diary app v2

- packages/geo-diary-v2/src/components/pages/appointment/__tests__/__snapshots__/mobile-layout.test.tsx.snap
- packages/geo-diary-v2/src/components/ui/appointment-detail-modal/__tests__/__snapshots__/appointment-detail-modal.test.tsx.snap
- packages/geo-diary-v2/src/components/ui/appointment-list/__tests__/__snapshots__/appointment-list.test.tsx.snap
- packages/geo-diary-v2/src/components/ui/appointment-tile/__tests__/__snapshots__/appointment-tile.test.tsx.snap
- packages/geo-diary-v2/src/components/ui/eta-button/__tests__/__snapshots__/eta-button.test.tsx.snap
- packages/geo-diary-v2/src/components/ui/eta-button/__tests__/eta-button.test.tsx
- packages/geo-diary-v2/src/components/ui/eta-button/eta-button.tsx
- packages/geo-diary-v2/src/components/ui/map/gmaps.tsx
- packages/geo-diary-v2/src/graphql/__mocks__/appointment.ts
fixes: #2027 
Issue Number: #2027 
- Fix bug geo-diary
> fix: #2027 geo diary v2 bug

- packages/developer-portal/src/components/pages/settings/settings-billing-tab/accounts-information-form/__styles__/account-status-section.ts
- packages/developer-portal/src/components/pages/settings/settings-billing-tab/accounts-information-form/__tests__/__snapshots__/account-status-section.test.tsx.snap
- packages/developer-portal/src/components/pages/settings/settings-billing-tab/accounts-information-form/__tests__/__snapshots__/reapit-reference-section.test.tsx.snap
- packages/developer-portal/src/components/pages/settings/settings-billing-tab/accounts-information-form/__tests__/accounts-information-form.test.tsx
- packages/developer-portal/src/components/pages/settings/settings-billing-tab/accounts-information-form/account-status-section.tsx
- packages/developer-portal/src/components/pages/settings/settings-billing-tab/accounts-information-form/accounts-information-form.tsx
- packages/developer-portal/src/components/pages/settings/settings-billing-tab/accounts-information-form/form-schema/validation-schema.ts
- packages/developer-portal/src/components/pages/settings/settings-billing-tab/accounts-information-form/reapit-reference-section.tsx
> fix: #1987 update billing page

- packages/marketplace/src/components/pages/settings/__tests__/__snapshots__/setting.test.tsx.snap
- packages/marketplace/src/components/pages/settings/__tests__/setting.test.tsx
- packages/marketplace/src/components/pages/settings/setting.tsx
fixes: https://github.com/reapit/foundations/issues/2090
-
> chore: #2090 Logout button should be hidden in Desktop Mode for Client

- packages/developer-portal/src/components/pages/app-detail/__tests__/app-content.test.tsx
- packages/developer-portal/src/components/pages/app-detail/app-content.tsx
fixes: #2111 
Issue Number: #2111 
- Fixes dead link to preview page
> fix: #2111 fixes app preview

- packages/geo-diary-v2/src/components/pages/appointment/__styles__/index.ts
- packages/geo-diary-v2/src/components/pages/appointment/__tests__/__snapshots__/mobile-layout.test.tsx.snap
- packages/geo-diary-v2/src/components/pages/appointment/mobile-layout.tsx
- packages/geo-diary-v2/src/components/ui/appointment-detail-modal/__tests__/__snapshots__/appointment-detail-modal.test.tsx.snap
- packages/geo-diary-v2/src/components/ui/appointment-detail-modal/__tests__/appointment-detail-modal.test.tsx
- packages/geo-diary-v2/src/components/ui/appointment-detail-modal/appointment-detail-modal.tsx
- packages/geo-diary-v2/src/components/ui/appointment-tile/__tests__/appointment-tile.test.tsx
- packages/geo-diary-v2/src/components/ui/appointment-tile/appointment-tile.tsx
- packages/geo-diary-v2/src/components/ui/appointment-time/__tests__/appointment-time.test.tsx
- packages/geo-diary-v2/src/components/ui/appointment-time/appointment-time.tsx
- packages/geo-diary-v2/src/components/ui/eta-button/__tests__/__snapshots__/eta-button.test.tsx.snap
- packages/geo-diary-v2/src/components/ui/eta-button/eta-button.tsx
- packages/geo-diary-v2/src/components/ui/list-and-map-tab/list-and-map-tab.tsx
- packages/geo-diary-v2/src/components/ui/map-pannel/map-pannel.tsx
fixes: #2072 
Issue Number: #2072 
- Fix geo-diary v2 issue
> fix: #2072 geo diary v2 issue

- packages/connect-session/src/__mocks__/browser-session.ts
- packages/connect-session/src/browser/__tests__/index.test.ts
- packages/connect-session/src/browser/index.ts
fixes: #2056 
Issue Number: #2056 
- Browser module now clears our local storage on logout
> feat: #2056 improve logout

- packages/elements/src/components/ModalV2/__styles__/index.ts
- packages/elements/src/components/ModalV2/index.tsx
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-detail.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-install-confirmation.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/__tests__/app-install-confirmation.test.tsx
- packages/marketplace/src/components/pages/app-detail/client/app-install-confirmation.tsx
fixes: #2088 
Issue Number: #2088 
-
> chore: #2088 update success modal for direct api apps

- packages/cloud-alert/cypress.json
- packages/cloud-alert/cypress/integration/admin-portal.test.ts
- packages/cloud-alert/cypress/integration/developer-portal.test.ts
fixes: #2114
Issue Number: #2114
> feat: #2114 uptime test for admin & dev portal

- packages/reapit-connect/package.json
fixes: #2091
Issue Number: #2091
- Fix CI due to sentry
cross-env not working when chaining `&&` https://github.com/kentcdodds/cross-env/issues/50#issuecomment-329970058
> fix: #2091 fix process.env when chaining env variable

- scripts/release/utils.js
fixes: #2117 
Issue Number: #2117 
- Onboard Reapit connect session
> chore: #2117 #2022 release reapit connect session and cra external template

- packages/marketplace/package.json
- packages/marketplace/src/components/pages/apps/__tests__/__snapshots__/apps.test.tsx.snap
- packages/marketplace/src/components/pages/apps/apps.tsx
- packages/marketplace/src/components/ui/__tests__/__snapshots__/app-card.tsx.snap
- packages/marketplace/src/components/ui/__tests__/__snapshots__/app-list.tsx.snap
- packages/marketplace/src/components/ui/__tests__/__snapshots__/fade.tsx.snap
- packages/marketplace/src/components/ui/__tests__/__snapshots__/featured-app.tsx.snap
- packages/marketplace/src/components/ui/__tests__/fade.tsx
- packages/marketplace/src/components/ui/__tests__/featured-app.tsx
- packages/marketplace/src/components/ui/app-card.tsx
- packages/marketplace/src/components/ui/app-list.tsx
- packages/marketplace/src/components/ui/fade.tsx
- packages/marketplace/src/components/ui/featured-app.tsx
- packages/marketplace/src/constants/paginator.ts
- packages/marketplace/src/reducers/client/__test__/app-summary.test.ts
- packages/marketplace/src/reducers/client/app-summary.ts
- packages/marketplace/src/sagas/__tests__/client.ts
- packages/marketplace/src/sagas/client.ts
- packages/marketplace/src/styles/blocks/featured-app.scss
- packages/marketplace/src/styles/index.scss
- packages/marketplace/src/styles/pages/apps.scss
- packages/marketplace/src/utils/__tests__/route-dispatcher.ts
- packages/marketplace/src/utils/route-dispatcher.ts
- yarn.lock
fixes: https://github.com/reapit/foundations/issues/2120
-
> feat: #2120 Pagination of Browse Apps list on Marketplace should be an infinite scroll

- packages/aml-checklist/package.json
- packages/aml-checklist/src/core/connect-session.ts
- packages/aml-checklist/src/core/index.tsx
- packages/connect-session/README.md
- packages/connect-session/jest.config.js
- packages/connect-session/src/__mocks__/session.ts
- packages/connect-session/src/browser/__tests__/index.test.ts
- packages/connect-session/src/browser/index.ts
- packages/connect-session/src/index.ts
- packages/connect-session/src/react/__tests__/index.test.tsx
- packages/connect-session/src/server/__tests__/index.test.ts
- packages/connect-session/src/server/index.ts
- packages/connect-session/src/types.ts
- packages/cra-external-template/template/src/components/pages/__tests__/login.tsx
- packages/cra-external-template/template/src/components/pages/login.tsx
- packages/cra-external-template/template/src/components/ui/menu.tsx
- packages/cra-external-template/template/src/core/connect-session.tsx
- packages/cra-external-template/template/src/core/private-route-wrapper.tsx
- packages/cra-external-template/template/src/index.tsx
fixes: #2116 
Issue Number: #2116 
- Adds node version of connect session
- Refactors AML and CRA template so singleton does not get a runtime issue
> feat: #2116 node connect session

- packages/elements/src/components/Wizard/wizard.stories.tsx
fixes: #2089 
Issue Number: #2089 
- Tweak UI layout
> fix: #2089 tweak ui for storybook

- packages/marketplace/src/components/pages/apps/apps.tsx
- packages/marketplace/src/core/__tests__/__snapshots__/private-route-wrapper.tsx.snap
- packages/marketplace/src/core/private-route-wrapper.tsx
- packages/marketplace/src/sagas/client.ts
- packages/marketplace/src/utils/__tests__/browse-app.ts
- packages/marketplace/src/utils/browse-app.ts
fixes: https://github.com/reapit/foundations/issues/2120
-
> chore: #2120 calculate number of apps on different screen height

- packages/site-builder/src/components/pages/__tests__/gallery-page.test.tsx
- packages/site-builder/src/components/pages/gallery-page.tsx
- packages/site-builder/src/utils/clipboard-copy.ts
> chore: fix ci failing

- packages/cognito-auth/package.json
fixes: #
- Bump cognito-auth 2.1.10
> chore: bump cognito-auth 2.1.10

- packages/elements/src/components/ModalV2/index.tsx
> fix: billing modal not responsive

- packages/marketplace/src/reducers/client/app-summary.ts
- packages/marketplace/src/utils/__tests__/browse-app.ts
- packages/marketplace/src/utils/browse-app.ts
fixes: https://github.com/reapit/foundations/issues/2120
-
> fix: #2120 fix apps are duplicated after go back from app detail

- packages/admin-portal/src/components/pages/devs-management/set-status-modal/__tests__/__snapshots__/status-modal.test.tsx.snap
- packages/developer-portal/src/components/pages/invite/__tests__/__snapshots__/accepted.test.tsx.snap
- packages/developer-portal/src/components/pages/invite/__tests__/__snapshots__/invite.test.tsx.snap
- packages/developer-portal/src/components/pages/invite/__tests__/__snapshots__/rejected.test.tsx.snap
- packages/developer-portal/src/components/pages/invite/accepted.tsx
- packages/developer-portal/src/components/pages/invite/invite.tsx
- packages/developer-portal/src/components/pages/invite/rejected.tsx
- packages/developer-portal/src/components/ui/developer-invite-member-modal/__tests__/__snapshots__/developer-invite-member-modal.test.tsx.snap
- packages/elements/src/components/ModalV2/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components/ModalV2/__tests__/index.tsx
- packages/elements/src/components/ModalV2/index.tsx
- packages/geo-diary-v2/src/components/ui/appointment-detail-modal/__tests__/__snapshots__/appointment-detail-modal.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-detail.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-install-confirmation.test.tsx.snap
fixes: #2096
Issue Number: #2096
-
> chore: #2096 update modal v2 header style

- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-install-confirmation.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/app-install-confirmation.tsx
- packages/marketplace/src/components/pages/app-detail/client/app-uninstall-confirmation.tsx
fixes: https://github.com/reapit/foundations/issues/2190
-
> chore: #2190 Update confirm install and confirm uninstall modals

- packages/marketplace/src/components/pages/apps/__tests__/__snapshots__/apps.test.tsx.snap
- packages/marketplace/src/components/pages/apps/apps.tsx
fixes: https://github.com/reapit/foundations/issues/2120
-
> fix: #2120 fix spacing between normal apps and comming soon apps

- packages/marketplace/src/components/pages/app-detail/client/web-component-config-modal/client-web-component-config.tsx
fixes: #
Cannot fetch web component config if have no clientId.
-
> fix: cannot fetch webcomponent config after migrate to connect-session

- packages/developer-portal/src/styles/vendor/swagger.scss
fixes: #2204
Issue Number: #2204
- Add scrollbar in developer swagger page
> fix: #2204 Scrollbar in developer swagger page

- packages/developer-portal/src/components/pages/invite/__tests__/__snapshots__/accepted.test.tsx.snap
- packages/developer-portal/src/components/pages/invite/__tests__/__snapshots__/invite.test.tsx.snap
- packages/developer-portal/src/components/pages/invite/__tests__/accepted.test.tsx
- packages/developer-portal/src/components/pages/invite/accepted.tsx
- packages/developer-portal/src/core/private-route-wrapper.tsx
fixes: #2177
Issue Number: #2177
- **Also change redirect route to `/APPS` when access the root route**
> feat: #2177 Add a ‘Login’ button the Invite ‘success’ modal

- packages/elements/src/components/ModalV2/__styles__/index.ts
- packages/elements/src/components/ModalV2/index.tsx
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-detail.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-install-confirmation.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-uninstall-confirmation.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/__tests__/app-uninstall-confirmation.test.tsx
- packages/marketplace/src/components/pages/app-detail/client/app-install-confirmation.tsx
- packages/marketplace/src/components/pages/app-detail/client/app-uninstall-confirmation.tsx
fixes: https://github.com/reapit/foundations/issues/2190
-
> chore: #2190 Update the ‘Confirm Installation’ & ‘Confirm Uninstall’ modals

- packages/connect-session/package.json
- packages/cra-template-foundations/package.json
- packages/elements/package.json
> chore: bump version for packages

- packages/cognito-auth/README.md
- packages/cognito-auth/package.json
- packages/connect-session/README.md
- packages/connect-session/package.json
- packages/cra-template-foundations/README.md
- packages/cra-template-foundations/package.json
- packages/elements/README.md
- packages/elements/package.json
- packages/foundations-ts-definitions/README.md
- packages/foundations-ts-definitions/package.json
- packages/react-app-scaffolder/README.md
- packages/react-app-scaffolder/package.json
fixes: #2023 
Issue Number: #2023 
- Updates docs links and bumps versions
> fix: #2023 tweaks to go live with NPM

- packages/marketplace/src/styles/blocks/featured-app.scss
fixes: #
Spacing between feature apps and main apps on small screen
> fix: feature apps, main apps spacing fix

- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-button-group.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-detail.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/non-admin-modal.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/__tests__/app-button-group.test.tsx
- packages/marketplace/src/components/pages/app-detail/client/__tests__/app-detail.test.tsx
- packages/marketplace/src/components/pages/app-detail/client/__tests__/non-admin-modal.test.tsx
- packages/marketplace/src/components/pages/app-detail/client/app-detail-button-group.tsx
- packages/marketplace/src/components/pages/app-detail/client/app-detail.tsx
- packages/marketplace/src/components/pages/app-detail/client/non-admin-modal.tsx
fixes: #2216
Issue Number: #2216
> feat: #2216 non admins should see the install/uninstall buttons

- packages/marketplace/src/sagas/apps/apps.ts
- packages/marketplace/src/sagas/installations/installations.ts
fixes: https://github.com/reapit/foundations/issues/2257
-
> fix: #2257 Marketplace throws and invariant error when logging in as a developer without a client id

- packages/developer-portal/src/components/pages/apps/__tests__/__snapshots__/apps.test.tsx.snap
- packages/developer-portal/src/components/ui/submit-app-wizard/__tests__/__snapshots__/submit-app-wizard-modal.test.tsx.snap
- packages/developer-portal/src/components/ui/submit-app-wizard/__tests__/__snapshots__/submit-app-wizard.test.tsx.snap
- packages/developer-portal/src/components/ui/submit-app-wizard/submit-app-wizard-modal.tsx
- packages/developer-portal/src/components/ui/submit-app-wizard/submit-app-wizard.tsx
fixes: https://github.com/reapit/foundations/issues/2261
-
> fix: #2261 Create New App wizard has double close option

- packages/marketplace/src/sagas/apps/apps.ts
- packages/marketplace/src/sagas/installations/installations.ts
fixes: https://github.com/reapit/foundations/issues/2257
-
> fix: #2257 remove unnecessary error alert

- packages/geo-diary-v2/package.json
- packages/geo-diary-v2/src/core/__mocks__/router.tsx
> ci: pipeline for geo-diary-v2

- packages/developer-portal/src/components/pages/analytics/analytics.tsx
- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/filter-form.tsx
fixes: #2251 
Issue Number: #2251 
- Fix clean up warning in analytics page
> fix: #2251 remove warning  in analytics page

- packages/elements/src/components/ModalV2/__styles__/index.ts
- packages/elements/src/components/ModalV2/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components/ModalV2/index.tsx
fixes: https://github.com/reapit/foundations/issues/2261
-
> fix: #2261 update close button style

- packages/reapit-connect/src/constants/routes.ts
- packages/reapit-connect/src/core/__tests__/__snapshots__/app.test.tsx.snap
- packages/reapit-connect/src/core/__tests__/app.test.tsx
- packages/reapit-connect/src/core/app.tsx
fixes: #2252 
Issue Number: #2252 
-
> chore: #2252 developers should redirect to developer portal when landing on the reapit connect splash page

- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-detail.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-install-confirmation.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-uninstall-confirmation.test.tsx.snap
fixes: #
- Fix snapshot caused CI failed
> chore: update snapshot

- packages/developer-portal/src/components/pages/settings/__tests__/settings.test.tsx
- packages/developer-portal/src/components/pages/settings/settings-billing-tab/settings-billing-tab.tsx
- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/settings-organisation-tab.tsx
- packages/developer-portal/src/components/pages/settings/settings.tsx
fixes: #2260
Issue Number: #2260
- Change from get by developerId to email
> feat: #2260 billing and organisation only show admin

- packages/elements/src/styles/components/layout.scss
fixes: #2298
Issue Number: #2298 
- 768px screen now work correctly
> fix: #2298 fix 768px screen content not showing

- packages/developer-portal/src/components/pages/app-detail/app-revision-modal/app-revision-modal.tsx
fixes: #2293
Issue Number: #2293
-
> fix: #2293 Pending revision modal should loading when open 

- packages/developer-portal/src/components/pages/apps/__tests__/__snapshots__/apps.test.tsx.snap
- packages/developer-portal/src/components/ui/submit-app-wizard/__tests__/__snapshots__/submit-app-wizard-modal.test.tsx.snap
- packages/developer-portal/src/components/ui/submit-app-wizard/__tests__/__snapshots__/submit-app-wizard.test.tsx.snap
- packages/developer-portal/src/components/ui/submit-app-wizard/__tests__/submit-app-wizard.test.tsx
- packages/developer-portal/src/components/ui/submit-app-wizard/steps/__tests__/__snapshots__/step-submit-app-success.test.tsx.snap
- packages/developer-portal/src/components/ui/submit-app-wizard/steps/__tests__/step-submit-app-success.test.tsx
- packages/developer-portal/src/components/ui/submit-app-wizard/steps/step-submit-app-success.tsx
- packages/developer-portal/src/components/ui/submit-app-wizard/submit-app-wizard-modal.tsx
- packages/developer-portal/src/components/ui/submit-app-wizard/submit-app-wizard.tsx
- packages/developer-portal/src/components/ui/submit-app-wizard/types.ts
fixes: #2292
Issue Number: #2292 
- Fix bug on create new app
> fix: #2292 bug on create new app

- packages/developer-portal/src/components/ui/submit-app-wizard/__tests__/__snapshots__/submit-app-wizard.test.tsx.snap
- packages/developer-portal/src/components/ui/submit-app-wizard/__tests__/submit-app-wizard.test.tsx
- packages/developer-portal/src/components/ui/submit-app-wizard/submit-app-wizard.tsx
fixes: #2295 
Issue Number: #2295 
- Fix create app wizard modal's issues when closing
> fix: #2295: Fix create app wizard modal's issues when closing

- packages/marketplace/src/styles/pages/apps.scss
fixes: #2314 
Issue Number: #2314 
- Fix app container misaligned issue
> fix: #2314: Fix app container misaligned issue

- packages/geo-diary-v2/src/graphql/client.ts
fixes: #2315
Issue Number: #2315
- Add notification error for geo-diary-v2
> fix: #2315 add notification error for geo-diary-v2

- packages/elements/src/components/Map/__tests__/index.tsx
- packages/elements/src/components/Map/index.tsx
- packages/elements/src/styles/components/notification.scss
- packages/geo-diary-v2/src/components/ui/map/__test__/gmaps.test.tsx
- packages/geo-diary-v2/src/components/ui/map/gmaps.tsx
fixes: #2189 
Issue Number: #2189 
- Apply notifications for geo-diary-v2
> fix: #2189: Apply notifications for geo-diary-v2

- packages/developer-portal/src/components/pages/settings/settings.tsx
fixes: #2260
Issue Number: #2260
- Change method to check role by email from connectSession
> feat: #2260 change method to check role by email

- packages/reapit-connect/src/components/pages/welcome/welcome.tsx
- packages/reapit-connect/src/components/ui/section/__styles__/index.ts
- scripts/webpack/webpack.config.prod.js
fixes: https://github.com/reapit/foundations/issues/2202
-
> fix: #2202 fix linaria styles isn't consistent between dev and prod

- packages/marketplace/package.json
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/aside.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/aside.tsx
- packages/marketplace/src/components/pages/app-detail/common/ui-sections.tsx
- yarn.lock
> feat: #2214 add show the about developer section

- packages/graphql-server/src/constants/api.ts
- packages/graphql-server/src/resolvers/index.ts
- packages/graphql-server/src/resolvers/offers/__mocks__/create-offer.ts
- packages/graphql-server/src/resolvers/offers/__mocks__/offer.ts
- packages/graphql-server/src/resolvers/offers/__mocks__/offers.ts
- packages/graphql-server/src/resolvers/offers/__mocks__/update-offer.ts
- packages/graphql-server/src/resolvers/offers/__tests__/resolvers.test.ts
- packages/graphql-server/src/resolvers/offers/__tests__/services.test.ts
- packages/graphql-server/src/resolvers/offers/api.ts
- packages/graphql-server/src/resolvers/offers/offers.d.ts
- packages/graphql-server/src/resolvers/offers/resolvers.ts
- packages/graphql-server/src/resolvers/offers/services.ts
- packages/graphql-server/src/resolvers/offers/types.graphql
- packages/graphql-server/src/schema.graphql
- scripts/api-documentation/api-doc-config.json
fixes: #2138
Issue Number: #2138
-
> feat: #2138 Expand GraphQL Service service for Offers entity

- packages/graphql-server/src/resolvers/applicants/types.graphql
- packages/graphql-server/src/resolvers/propertyImages/types.graphql
- packages/graphql-server/src/resolvers/tenancies/api.ts
- packages/graphql-server/src/resolvers/tenancies/types.graphql
- packages/graphql-server/src/schema.graphql
- scripts/api-documentation/api-doc-config.json
fixes: #2142
Issue Number: #2142
- Add insomnia file and fix type
> fix: #2142 Add insomnia file and fix type

- packages/elements/src/components/Spreadsheet/utils.tsx
- packages/smb-onboarder/src/components/ui/offices-tab/offices-tab.tsx
- packages/smb-onboarder/src/worker/csv-upload.worker.ts
fixes: https://github.com/reapit/foundations/issues/2254
-
> fix: #2254 fix upload offices csv error

- packages/developer-portal/src/components/pages/analytics/cost-explorer/transaction-history/__test__/utils.test.ts
- packages/developer-portal/src/components/pages/analytics/cost-explorer/transaction-history/utils.ts
fixes: #2346
Issue Number: #2346
- Fix bug on transaction previous
> fix: #2346 transaction history bug

- packages/admin-portal/src/components/pages/devs-management/set-status-modal/__tests__/__snapshots__/status-modal.test.tsx.snap
- packages/developer-portal/src/components/pages/apps/__tests__/__snapshots__/apps.test.tsx.snap
- packages/developer-portal/src/components/pages/invite/__tests__/__snapshots__/invite.test.tsx.snap
- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/organisation-form/__tests__/__snapshots__/company-address-section.test.tsx.snap
- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/organisation-form/__tests__/__snapshots__/company-information.test.tsx.snap
- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/organisation-form/__tests__/organisation-form.test.tsx
- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/organisation-form/company-information-section.tsx
- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/organisation-form/form-schema/form-fields.ts
- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/organisation-form/form-schema/validation-schema.ts
- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/organisation-form/organisation-form.tsx
- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/settings-organisation-tab.tsx
- packages/developer-portal/src/components/ui/developer-invite-member-modal/__tests__/__snapshots__/developer-invite-member-modal.test.tsx.snap
- packages/elements/src/components/ModalV2/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components/ModalV2/index.tsx
- packages/geo-diary-v2/src/components/ui/appointment-detail-modal/__tests__/__snapshots__/appointment-detail-modal.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-detail.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-install-confirmation.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-uninstall-confirmation.test.tsx.snap
fixes: #2328 
Issue Number: #2328 
- Tweak UI for organisation tab
> feat: #2328 update organisation tab ui

- packages/developer-portal/src/components/pages/settings/settings-billing-tab/accounts-information-form/__tests__/__snapshots__/account-status-section.test.tsx.snap
- packages/developer-portal/src/components/pages/settings/settings-billing-tab/accounts-information-form/account-status-section.tsx
- packages/developer-portal/src/components/pages/settings/settings-billing-tab/accounts-information-form/direct-debit-section.tsx
> fix: #1987 hide direct debit helper text when status is pending

- packages/reapit-connect/src/components/pages/welcome/__styles__/index.ts
- packages/reapit-connect/src/components/pages/welcome/welcome.tsx
- packages/reapit-connect/src/components/ui/section/__styles__/index.ts
- packages/reapit-connect/src/components/ui/section/__tests__/__snapshots__/section.test.tsx.snap
- packages/reapit-connect/src/components/ui/section/section.tsx
fixes: https://github.com/reapit/foundations/issues/2202
- [] Bugfix
-
> chore: #2202 Update component style

- packages/reapit-connect/src/components/ui/section/__styles__/index.ts
fixes: https://github.com/reapit/foundations/issues/2202
-
> chore: #2202 update image size

- packages/developer-portal/src/components/pages/analytics/cost-explorer/transaction-history/__test__/__snapshots__/transaction-history.test.tsx.snap
- packages/developer-portal/src/components/pages/analytics/cost-explorer/transaction-history/transaction-history.tsx
fixes: #2346 
Issue Number: #2346 
- Hide previous transaction history if there is no previous transaction history
> feat: #2346 hide transaction history if there is no transactions

- packages/developer-portal/src/utils/route-dispatcher.ts
fixes: #2260
Issue Number: #2260 
- Show the organisation billing tab bug fixing on fetch current user
> fix: #2260 show the organisation billing tab

- packages/elements/src/components/Spreadsheet/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components/Spreadsheet/__tests__/__snapshots__/modal-upload.tsx.snap
- packages/elements/src/components/Spreadsheet/__tests__/handlers.tsx
- packages/elements/src/components/Spreadsheet/__tests__/modal-upload.tsx
- packages/elements/src/components/Spreadsheet/handlers.tsx
- packages/elements/src/components/Spreadsheet/index.tsx
- packages/elements/src/components/Spreadsheet/modal-upload.tsx
- packages/elements/src/components/Spreadsheet/types.tsx
- packages/elements/src/components/Spreadsheet/utils.tsx
- packages/smb-onboarder/src/components/ui/offices-tab/__tests__/offices-tab.tsx
- packages/smb-onboarder/src/components/ui/offices-tab/offices-tab.tsx
- packages/smb-onboarder/src/utils/worker-upload-helper.ts
- packages/smb-onboarder/src/worker/csv-upload.worker.ts
fixes: https://github.com/reapit/foundations/issues/2254
-
> chore: #2254 update upload csv workflow. Add meaningful errors

- packages/marketplace/src/components/pages/settings/__tests__/__snapshots__/setting.test.tsx.snap
- packages/marketplace/src/components/pages/settings/setting.tsx
- packages/marketplace/src/components/ui/menu.tsx
fixes: https://github.com/reapit/foundations/issues/2332
-
> feat: #2332 Update settings page in marketplace

- packages/marketplace/src/components/pages/apps/__tests__/apps.test.tsx
- packages/marketplace/src/components/pages/apps/apps.tsx
- packages/marketplace/src/utils/route-dispatcher.ts
fixes: #2371 
Issue Number: #2371 
- Infinity scroll bug on fetch apps
> fix: #2371 bug on infinity scroll

- packages/marketplace/src/components/pages/settings/__tests__/__snapshots__/setting.test.tsx.snap
- packages/marketplace/src/components/pages/settings/setting.tsx
- packages/marketplace/src/styles/pages/settings.scss
fixes: https://github.com/reapit/foundations/issues/2385
-
> chore: #2332 Update settings page in marketplace

- packages/developer-portal/src/components/pages/login/__tests__/login.test.tsx
- packages/developer-portal/src/components/pages/login/login.tsx
- packages/developer-portal/src/core/private-route-wrapper.tsx
fixes: #2274 
Issue Number: #2274 
- Fixes redirect loop on login page
> fix: #2274 login bug fixed

- packages/developer-portal/src/core/private-route-wrapper.tsx
fixes: #2372
Issue Number: #2372
- Fix sentry type error when invite member
> fix: #2372 sentry error type error when invite member

- .github/workflows/delete-environment.yml
- packages/deploy-slack-bot/src/index.ts
fixes: #2396 
Issue Number: #2396
- update slackbot for new command
- Add pipeline for delete-environment
> feat: #2396 update slack bot

- packages/elements/src/components/Layout/index.tsx
- packages/elements/src/styles/base/utilities.scss
- packages/marketplace/package.json
- packages/marketplace/src/components/pages/apps/__tests__/__snapshots__/apps.test.tsx.snap
- packages/marketplace/src/components/pages/apps/__tests__/__snapshots__/coming-soon.test.tsx.snap
- packages/marketplace/src/components/pages/apps/__tests__/apps.test.tsx
- packages/marketplace/src/components/pages/apps/__tests__/coming-soon.test.tsx
- packages/marketplace/src/components/pages/apps/apps.tsx
- packages/marketplace/src/components/pages/apps/coming-soon.tsx
- packages/marketplace/src/components/ui/__tests__/__snapshots__/app-list.tsx.snap
- packages/marketplace/src/components/ui/app-list.tsx
- packages/marketplace/src/core/__tests__/__snapshots__/private-route-wrapper.tsx.snap
- packages/marketplace/src/core/private-route-wrapper.tsx
- packages/marketplace/src/styles/pages/apps.scss
- yarn.lock
fixes: #2391 
Issue Number: #2391 
- Browse app page scrolling is disabled when not over app list
> fix: #2391 Browse app page scrolling is disabled when not over app list

- packages/graphql-server/jest.config.js
- packages/graphql-server/src/resolvers/applicants/__tests__/api.test.ts
- packages/graphql-server/src/resolvers/appointments/__tests__/api.test.ts
- packages/graphql-server/src/resolvers/areas/__tests__/api.test.ts
- packages/graphql-server/src/resolvers/companies/__tests__/api.test.ts
- packages/graphql-server/src/resolvers/configurations/__tests__/api.test.ts
- packages/graphql-server/src/resolvers/contacts/__tests__/api.test.ts
- packages/graphql-server/src/resolvers/departments/types.graphql
- packages/graphql-server/src/resolvers/identity-checks/__tests__/api.test.ts
- packages/graphql-server/src/resolvers/identity-checks/api.ts
- packages/graphql-server/src/resolvers/negotiators/__tests__/api.test.ts
- packages/graphql-server/src/resolvers/offers/__tests__/api.test.ts
- packages/graphql-server/src/resolvers/offices/__tests__/api.test.ts
- packages/graphql-server/src/resolvers/properties/__tests__/api.test.ts
- packages/graphql-server/src/resolvers/propertyImages/__tests__/api.test.ts
- packages/graphql-server/src/resolvers/tenancies/__tests__/api.test.ts
- packages/graphql-server/src/resolvers/vendors/__stubs__/create-vendor-relationships.ts
- packages/graphql-server/src/resolvers/vendors/__stubs__/delete-vendor-relationships.ts
- packages/graphql-server/src/resolvers/vendors/__stubs__/vendor-relationship.ts
- packages/graphql-server/src/resolvers/vendors/__stubs__/vendor-relationships.ts
- packages/graphql-server/src/resolvers/vendors/__tests__/api.test.ts
- packages/graphql-server/src/resolvers/vendors/vendors.d.ts
fixes: #2362
Issue Number: #2362
- Add tests for API layer in graphql server
> chore: #2362 graphql api layer tests

- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/members.tsx
fixes: https://github.com/reapit/foundations/issues/2385
-
> chore: #2385 update condition typo

- packages/developer-portal/src/components/pages/analytics/cost-explorer/cost-explorer-component/cost-explorer.tsx
fixes: https://github.com/reapit/foundations/issues/1970
-
> chore: #1970 Add helper text for the 'Cost Explorer'

- .github/workflows/release.yml
- packages/deploy-slack-bot/src/index.ts
> fix: pipeline deployment

- .github/workflows/release.yml
> fix: pipeline deploy

- packages/deploy-slack-bot/src/index.ts
> fix: deploy slack bot

- packages/connect-session/jest.config.js
- packages/connect-session/src/browser/__tests__/index.test.ts
- packages/connect-session/src/browser/index.ts
fixes: #2274 
Issue Number: #2274 
- Adds caching of refresh token only
- Redirect to authorize not login page on fail
> fix: #2274 cache refresh token for better UX and don't redirect to login

- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/__tests__/__snapshots__/members.test.tsx.snap
- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/__tests__/__snapshots__/settings-organisation-tab.test.tsx.snap
- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/__tests__/members.test.tsx
- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/members.tsx
- packages/developer-portal/src/components/ui/developer-invite-member-modal/developer-invite-member-modal.tsx
fixes: #2395
Issue Number: #2395
> feat: #2395 update invite again

- .github/workflows/release.yml
- packages/admin-portal/serverless.yml
- packages/aml-checklist/serverless.yml
- packages/api-docs-lamda/serverless.yml
- packages/cognito-custom-mail-lambda/serverless.yml
- packages/cognito-custom-mail-lambda/webpack.config.js
- packages/demo-site/serverless.yml
- packages/deploy-slack-bot/serverless.yml
- packages/deploy-slack-bot/src/index.ts
- packages/developer-portal/serverless.yml
- packages/elements-next/serverless.yml
- packages/elements/serverless.yml
- packages/geo-diary-v2/serverless.yml
- packages/geo-diary/serverless.yml
- packages/graphql-server/serverless.yml
- packages/lifetime-legal/serverless.yml
- packages/marketplace/serverless.yml
- packages/reapit-connect/serverless.yml
- packages/site-builder/serverless.yml
- packages/smb-onboarder/serverless.yml
- packages/web-components-config-server/serverless.yml
- packages/web-components/serverless.example.yml
- packages/web-components/src/appointment-planner-component/server/serverless.yml
- packages/web-components/src/search-widget/server/serverless.yml
- scripts/release/utils.js
- scripts/serverless-template-generator/fullstack.ejs
- scripts/serverless-template-generator/lambda.ejs
- scripts/serverless-template-generator/webapp.ejs
> chore: change-deploy-serverless-scripts

- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/__test__/__snapshots__/filter-bar.test.tsx.snap
- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/__test__/__snapshots__/filter-form.test.tsx.snap
- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/__test__/default-filter-group.test.tsx
- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/__test__/filter-bar.test.tsx
- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/__test__/filter-form.test.tsx
- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/default-filter-group.tsx
- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/filter-bar.tsx
- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/filter-form.tsx
- packages/developer-portal/src/components/pages/webhooks/__tests__/webhook-edit-modal.test.tsx
- packages/developer-portal/src/components/pages/webhooks/webhook-edit-modal.tsx
- packages/developer-portal/src/reducers/webhooks-subscriptions/webhook-edit-modal.ts
fixes: #2401
Issue Number: #2401
> feat: #2401 Update the 'Client' drop down to show Customer Name & Customer ID 

- packages/connect-session/README.md
- packages/connect-session/jest.config.js
- packages/connect-session/package.json
- packages/connect-session/src/__mocks__/session.ts
- packages/connect-session/src/server/index.ts
- packages/connect-session/src/types.ts
- packages/connect-session/src/utils/verify-decode-id-token.ts
fixes: #2274 
Issue Number: #2274 
- IE does not like promisified version of JWT verify
> fix: #2274 addresses small IE bug

- packages/marketplace/src/components/pages/app-detail/common/__tests__/__snapshots__/ui-app-header.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/common/ui-app-header.tsx
- packages/marketplace/src/core/__tests__/__snapshots__/private-route-wrapper.tsx.snap
- packages/marketplace/src/core/private-route-wrapper.tsx
fixes: #2453 
Issue Number: #2453 
-  Fix standalone app page scrolling issues on mobile
> fix: #2453 - Fix standalone app page scrolling issues on mobile

- packages/connect-session/jest.config.js
- packages/connect-session/package.json
- packages/connect-session/src/browser/index.ts
- yarn.lock
fixes: #2274 
Issue Number: #2274 
- Ensure we only fetch the refresh token for last auth user from local storage
> fix: #2274 ensure old-sessions do not persist

- packages/aml-checklist/src/components/ui/modal/__tests__/__snapshots__/update-status.tsx.snap
- packages/aml-checklist/src/components/ui/modal/update-status.tsx
fixes: https://github.com/reapit/foundations/issues/2450
-
> chore: #2450 Disable the 'Refer to Lifetime Legal' feature in AML

- packages/geo-diary/package.json
fixes: https://github.com/reapit/foundations/issues/2431
-
> chore: Update geo-diary release script

- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/__test__/filter-form.test.tsx
- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/filter-form.tsx
- packages/developer-portal/src/components/pages/webhooks/__tests__/webhook-edit-modal.test.tsx
- packages/developer-portal/src/components/pages/webhooks/webhook-edit-modal.tsx
- packages/developer-portal/src/constants/api.ts
fixes: #2401
Issue Number: #2401
-
> chore: #2401 only add SBOX if no installation

- packages/developer-portal/src/components/pages/register/__tests__/__snapshots__/register.test.tsx.snap
- packages/developer-portal/src/components/pages/register/register.tsx
fixes: #2464 
Issue Number: #2464 
- Fix registration success message styles
> fix: #2464 - Fix registration success message styles

- packages/admin-portal/src/services/utils.ts
- packages/connect-session/src/utils/verify-decode-id-token.ts
- packages/developer-portal/src/services/utils.ts
- packages/marketplace/src/services/negotiators.ts
- packages/marketplace/src/services/utils.ts
fixes: #2467 
Issue Number: #2467 
- fix CPU variance issue which caused time now to be in the past and therefore invalid id_tokens
> fix: #2467 fix CPU variance issue

- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/__test__/filter-form.test.tsx
- packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/filter-form.tsx
- packages/developer-portal/src/components/pages/webhooks/__tests__/webhook-edit-modal.test.tsx
- packages/developer-portal/src/components/pages/webhooks/webhook-edit-modal.tsx
- packages/developer-portal/src/constants/api.ts
fixes: #2401
Issue Number: #2401
- rename sbox account from `Sandbox Estates` to `Sandbox Estates SBOX`
> chore: #2401 rename SBOX client name

- packages/admin-portal/src/core/private-route-wrapper.tsx
- packages/developer-portal/src/components/hocs/__tests__/route-fetcher.tsx
- packages/developer-portal/src/constants/routes.ts
- packages/developer-portal/src/core/__tests__/__snapshots__/private-route.tsx.snap
- packages/developer-portal/src/core/__tests__/private-route.tsx
- packages/developer-portal/src/core/private-route-wrapper.tsx
- packages/marketplace/src/core/private-route-wrapper.tsx
fixes: #2451 
Issue Number: #2451 
- fix bug on land on page not found
> fix: #2451 land on page not found

- packages/admin-portal/src/core/__tests__/__snapshots__/private-route.tsx.snap
- packages/admin-portal/src/core/private-route.tsx
fixes: # 
Issue Number: # 
- Fix admin portal login issues
> fix: Admin portal login issues

- packages/developer-portal/src/components/pages/help/__tests__/help.test.tsx
- packages/developer-portal/src/components/pages/help/help.tsx
- packages/developer-portal/src/scripts/chat-bot.js
fixes: https://github.com/reapit/foundations/issues/2476
-
> fix: #2476 fix chatbot show multiple times on developer portal

- packages/reapit-connect/src/constants/routes.ts
- packages/reapit-connect/src/core/__tests__/app.test.tsx
- packages/reapit-connect/src/core/app.tsx
- packages/reapit-connect/src/core/index.tsx
- packages/reapit-connect/src/types/global.d.ts
> chore: Update developer redirect url in reapit connect

- packages/developer-portal/src/components/pages/edit-app/developer-edit-app.tsx
- packages/elements/src/components/FileInput/index.tsx
fixes: #2479 
Issue Number: #2479
- Fix upload image button error
> fix: #2479 upload image button error

- packages/developer-portal/src/components/pages/help/help.tsx
fixes: https://github.com/reapit/foundations/issues/2476
-
> chore: #2476 identify chatlio when identity available

- packages/aml-checklist/src/components/ui/menu.tsx
- packages/aml-checklist/src/core/index.tsx
- packages/aml-checklist/src/types/global.d.ts
fixes: https://github.com/reapit/foundations/issues/2478
-
> chore: update marketplace redirect url on aml-checklist app

- packages/developer-portal/src/components/pages/edit-app/__tests__/__snapshots__/developer-edit-app.test.tsx.snap
- packages/developer-portal/src/components/pages/edit-app/developer-edit-app.tsx
- packages/elements/src/components/FileInput/index.tsx
> fix: #2479 bug on upload images ui button

- packages/graphql-server/src/utils/__tests__/handle-error.test.ts
- packages/graphql-server/src/utils/handle-error.ts
> chore: temporary disabled logger for graphql

- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/organisation-form/__tests__/__snapshots__/company-address-section.test.tsx.snap
- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/organisation-form/__tests__/__snapshots__/company-information.test.tsx.snap
- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/organisation-form/form-schema/form-fields.ts
- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/organisation-form/form-schema/validation-schema.ts
fixes: #2495
Issue Number: #2495
- Add an * to field names to show the following fields are also required:
1. VAT Registration Number
2. Company Registration Number
3. Address Line 1
4. Address Line 4
- Add require validate for the following fields:
1. Address Line 1
1. Address Line 4
> feat: #2495 add * to require fields in organisation tab

- packages/graphql-server/src/utils/handle-error.ts
> chore: temporary disabled errors

- packages/graphql-server/src/utils/handle-error.ts
> chore: change log errors

- packages/graphql-server/src/resolvers/appointments/__tests__/api.test.ts
- packages/graphql-server/src/resolvers/appointments/api.ts
> chore: remove logger for debugging

- packages/smb-onboarder/src/components/pages/negotiators/__tests__/__snapshots__/negotiators.test.tsx.snap
- packages/smb-onboarder/src/components/pages/offices/__tests__/__snapshots__/offices.tsx.snap
- packages/smb-onboarder/src/components/ui/negotiators-list/__tests__/__snapshots__/negotiators-list.test.tsx.snap
- packages/smb-onboarder/src/components/ui/negotiators-list/gql/get-negotiators.graphql
- packages/smb-onboarder/src/components/ui/offices-tab/__tests__/__snapshots__/offices-tab.tsx.snap
- packages/smb-onboarder/src/graphql/fragments/negotiator.graphql
- packages/smb-onboarder/src/graphql/fragments/office.graphql
fixes: # 
Issue Number: # 
- Fix smb graphql embedded issues
> fix: SMB graphql embedded issues

- packages/graphql-server/src/resolvers/appointments/__tests__/api.test.ts
- packages/graphql-server/src/resolvers/appointments/api.ts
- packages/graphql-server/src/utils/__tests__/handle-error.test.ts
- packages/graphql-server/src/utils/handle-error.ts
> chore: revert logger

- packages/developer-portal/src/components/pages/app-detail/app-revision-modal/app-revision-modal.tsx
- packages/developer-portal/src/components/pages/settings/settings-billing-tab/accounts-information-form/__tests__/__snapshots__/account-status-section.test.tsx.snap
- packages/developer-portal/src/components/pages/settings/settings-billing-tab/accounts-information-form/account-status-section.tsx
- packages/developer-portal/src/components/pages/settings/settings-billing-tab/accounts-information-form/accounts-information-form.tsx
- packages/developer-portal/src/styles/blocks/submit-app-wizard.scss
- packages/smb-onboarder/src/components/providers/__tests__/upload-provider.tsx
> fix: #2402 tweak developer portal ui

- packages/connect-session/package.json
- packages/connect-session/src/__mocks__/session.ts
- packages/connect-session/src/types.ts
- packages/connect-session/src/utils/verify-decode-id-token.ts
- packages/marketplace/src/components/pages/settings/__tests__/__snapshots__/setting.test.tsx.snap
- packages/marketplace/src/components/pages/settings/setting.tsx
- packages/marketplace/src/selector/auth/__mocks__/auth.ts
- packages/marketplace/src/selector/auth/__tests__/auth.test.ts
- packages/marketplace/src/selector/auth/auth.ts
fixes: https://github.com/reapit/foundations/issues/2501
-
> chore: #2501 Update the 'Settings/Profile' page in Marketplace to populate the user information

- packages/marketplace/src/components/pages/settings/setting.tsx
fixes: #2396 
Issue Number: #2396 
- Disable change password in prod
> fix: #2396 disable change password in desktop

- packages/cloud-alert/cypress/fixtures/search-widget/property-images.json
- packages/cloud-alert/cypress/integration/aml-checklist.test.ts
- packages/cloud-alert/cypress/integration/geo-diary.test.ts
- packages/cloud-alert/cypress/integration/life-time-legal.test.ts
- packages/cloud-alert/cypress/support/constants.ts
fixes: #2459
Issue Number: #2459
- Fix cloud uptime tesr
> fix: #2459 cloud uptime fix

- packages/admin-portal/package.json
- packages/aml-checklist/package.json
- packages/cognito-custom-mail-lambda/package.json
- packages/demo-site/package.json
- packages/developer-portal/package.json
- packages/elements-next/package.json
- packages/elements/package.json
- packages/geo-diary/package.json
- packages/lifetime-legal/package.json
- packages/marketplace/package.json
- packages/reapit-connect/package.json
- packages/site-builder/package.json
- packages/smb-onboarder/package.json
- packages/web-components/package.json
fixes: #2519 
Issue Number: #2519 
- Fix release:dev command
> chore: #2519 update dev pipeline to deploy new infra

- .github/workflows/release-dev.yml
- yarn.lock
> fix: node version for ci release dev

- packages/cloud-alert/cypress/fixtures/search-widget/property-images.json
> chore: update cloud uptime

- packages/admin-portal/src/components/pages/customers/__tests__/__snapshots__/customers.test.tsx.snap
- packages/admin-portal/src/components/pages/customers/__tests__/customers.test.tsx
- packages/admin-portal/src/components/pages/customers/customers.tsx
> feat: #2536 Improve UI for no-result in search's feature from the Customers page

- packages/foundations-ts-definitions/scripts/release-github.js
- packages/foundations-ts-definitions/scripts/update-npm.js
- packages/web-components/scripts/release-serverless.js
- scripts/release/fetch-artifact.js
- scripts/release/upload-artifact.js
- scripts/release/utils.js
fixes: #2519 
Issue Number: #2519 
-
> fix: #2519 add await for run command

- scripts/release/utils.js
> fix: pipeline throw error when run command

- packages/graphql-server/src/errors/errors.ts
- packages/graphql-server/src/utils/handle-error.ts
fixes: https://github.com/reapit/foundations/issues/2550
-
> fix: #2550 add extensions field on graphql error

- packages/admin-portal/src/components/pages/customers/__tests__/__snapshots__/customers.test.tsx.snap
- packages/admin-portal/src/components/pages/customers/__tests__/customers.test.tsx
- packages/admin-portal/src/components/pages/customers/customers.tsx
fixes: #2534
Issue Number: #2534
- Add refresh button for customer search
> chore: #2537 add reset form button for customer search

- packages/aml-checklist/src/sagas/api.ts
fixes: #2512 
Issue Number: #2512 
- Change from return error to throw error
> fix: #2512 aml checklist throw error to notification

- scripts/release/fetch-artifact.js
> fix: mkdir for public if not exists

- packages/aml-checklist/src/sagas/__tests__/checklist-detail.test.ts
- packages/aml-checklist/src/sagas/checklist-detail.ts
fixes: #2458 
Issue Number: #2458 
- Fix error when submit update status identity check
> fix: #2548 cannot update status identity check

- packages/graphql-server/src/utils/handle-error.ts
fixes: https://github.com/reapit/foundations/issues/2550
-
> fix: #2550 fix sentry error object in graphql server

- packages/marketplace/src/utils/launch-app.ts
fixes: https://github.com/reapit/foundations/issues/2575
-
> fix: #2572 Marketplace Launch URI for apps query string is incorrect in desktop

- packages/developer-portal/src/components/ui/menu.tsx
- packages/developer-portal/src/core/__tests__/__snapshots__/router.tsx.snap
- packages/developer-portal/src/core/router.tsx
- yarn.lock
fixes: #2579 
Issue Number: #2579 
-
> fix: #2579 invite flow broken on prod

- packages/smb-onboarder/src/components/ui/offices-tab/offices-tab.tsx
fixes: https://github.com/reapit/foundations/issues/2582
-
> fix: #2582 fix Bad Request when create new office

- packages/cra-template-foundations/package.json
- packages/cra-template-foundations/template/src/reapit.config.json
> chore: #2563 update reapit config json to reflect new config schema

- packages/smb-onboarder/src/components/ui/upload-result-modal.tsx
fixes: #2591
Issue Number: #2591
-
> chore: #2591 Should hide traceId in errors uploads smb 

- packages/elements/src/components/Spreadsheet/utils.tsx
fixes: https://github.com/reapit/foundations/issues/2592
-
> fix: #2592 filter empty row from csv data

- packages/smb-onboarder/src/components/ui/negotiators-list/__tests__/__snapshots__/negotiators-list.test.tsx.snap
- packages/smb-onboarder/src/components/ui/negotiators-list/negotiators-list.tsx
- packages/smb-onboarder/src/components/ui/offices-tab/__tests__/__snapshots__/offices-tab.tsx.snap
- packages/smb-onboarder/src/components/ui/offices-tab/offices-tab.tsx
fixes: #2584 
Issue Number: #2584 
- Add hint for add new offices and add new users
> fix: #2584 hint for add  new offices and users

- package.json
- packages/admin-portal/package.json
- packages/elements/src/components/Spreadsheet/__tests__/handlers.tsx
- packages/elements/src/components/Spreadsheet/handlers.tsx
- packages/elements/src/components/Spreadsheet/index.tsx
- packages/elements/src/components/Spreadsheet/types.tsx
- packages/smb-onboarder/src/components/ui/negotiators-list/negotiators-list.tsx
- packages/smb-onboarder/src/components/ui/offices-tab/__tests__/__snapshots__/offices-tab.tsx.snap
- packages/smb-onboarder/src/components/ui/offices-tab/offices-tab.tsx
fixes: https://github.com/reapit/foundations/issues/2590
-
> feat: #2590 add download sample button

- packages/elements-next/src/index.mdx
fixes: #2146 
Issue Number: #2146 
- Elements v2 spec
> feat: #2146 Elements v2 spec

- packages/elements/package.json
- packages/elements/src/components/Spreadsheet/__tests__/__snapshots__/context-menu.tsx.snap
- packages/elements/src/components/Spreadsheet/__tests__/context-menu.tsx
- packages/elements/src/components/Spreadsheet/__tests__/handlers.tsx
- packages/elements/src/components/Spreadsheet/context-menu.tsx
- packages/elements/src/components/Spreadsheet/handlers.tsx
- packages/elements/src/styles/components/spreadsheet.scss
fixes: #2583 
Issue Number: #2583 
- Fix spreadsheet context menu position
v
> fix: #2583 data sheet context menu broken on scroll

- packages/web-components/src/appointment-planner-component/server/serverless.yml
> chore: #1224 update serverless yml of appointment planner api

- packages/marketplace/src/components/pages/app-detail/client/contact-developer-modal.tsx
fixes: https://github.com/reapit/foundations/issues/2650
-
> chore: #2650 Remove the 'Mailto' link in 'Desktop Mode' for app listings 'Need Help'

- packages/elements/src/styles/components/spreadsheet.scss
- packages/smb-onboarder/src/components/ui/negotiators-list/__tests__/__snapshots__/negotiators-list.test.tsx.snap
- packages/smb-onboarder/src/components/ui/negotiators-list/negotiators-list.tsx
- packages/smb-onboarder/src/components/ui/offices-tab/__tests__/__snapshots__/offices-tab.tsx.snap
- packages/smb-onboarder/src/components/ui/offices-tab/offices-tab.tsx
fixes: https://github.com/reapit/foundations/issues/2590
-
> chore: #2590 fix buttons spacing. Add download sample for users

- scripts/release/utils.js
> fix: pipeline for release note

- packages/reapit-connect/src/components/pages/welcome/welcome.tsx
> fix: #2618 update reapit connect link

- scripts/api-documentation/api-doc-config.json
> chore: #1224 update insomania docs

- packages/developer-portal/src/components/pages/edit-app/developer-edit-app.tsx
fixes: https://github.com/reapit/foundations/issues/2702
-
> chore: #2702 Additional text for Account Information

- packages/developer-portal/src/components/pages/app-detail/__styles__/app-detail.ts
fixes: #2520 
Issue Number: #2520 
- Fix wrong tag background color
> fix: #2520 - Fix wrong tag background color

- packages/elements-next/src/components/radio/index.ts
- packages/elements-next/src/components/radio/radio.stories.tsx
- packages/elements-next/src/components/radio/radio.tsx
- packages/elements-next/src/components/radio/styles.ts
fixes: #58
Issue Number: #58 
- Radio select feature
> feat: #58 radio select elements

- packages/developer-portal/src/services/developers.ts
- yarn.lock
fixes: #2782
Issue Number: #2782
- As per ticket
> chore: #2782 re-adds auth on dev and member endpoints

- packages/elements/package.json
> chore: #2717 bump elements version

- .github/workflows/codeql-analysis.yml
> feat: #2800 add code analysis action

- packages/marketplace/src/components/pages/apps/coming-soon.tsx
> fix: #2859 addresses infinite scroll bug

- packages/developer-portal/src/components/pages/edit-app/__tests__/__snapshots__/developer-edit-app.test.tsx.snap
- packages/developer-portal/src/components/pages/edit-app/__tests__/__snapshots__/general-information-section.test.tsx.snap
- packages/developer-portal/src/components/pages/edit-app/developer-edit-app.tsx
- packages/developer-portal/src/components/pages/edit-app/form-schema/form-fields.ts
- packages/developer-portal/src/components/pages/edit-app/general-information-section.tsx
- packages/reapit-connect/src/components/pages/welcome/welcome.tsx
> feat: #2900 disabled marketplace section RC. Updated isListed text

- packages/data-warehouse/package.json
- packages/payments-client/package.json
- packages/payments-server/package.json
- scripts/webpack/webpack.config.dev.js
> fix: #2910 fix pipeline so can deploy to prod

- packages/cra-template-foundations/package.json
- packages/elements/package.json
> fix: #2910 bump version numbers

- package.json
- packages/developer-portal/src/components/pages/analytics/__tests__/analytics.tsx
- packages/developer-portal/src/components/pages/analytics/detailed/__test__/detailed-tab.test.tsx
- packages/developer-portal/src/components/pages/analytics/detailed/__test__/installation-app-section.test.tsx
- packages/developer-portal/src/components/pages/register-confirm/__tests__/register-confirm.test.tsx
- packages/developer-portal/src/components/pages/settings/__tests__/tabs.test.tsx
- packages/developer-portal/src/components/pages/settings/settings-billing-tab/accounts-information-form/__tests__/accounts-information-form.test.tsx
- packages/developer-portal/src/components/pages/settings/settings-organisation-tab/organisation-form/__tests__/organisation-form.test.tsx
- packages/developer-portal/src/components/pages/settings/settings-profile-tab/__tests__/contact-information-form.test.tsx
- packages/developer-portal/src/components/ui/__tests__/menu.tsx
- packages/developer-portal/src/components/ui/developer-edition-modal/__tests__/developer-edition-modal.tsx
- packages/developer-portal/src/components/ui/submit-app-wizard/__tests__/submit-app-wizard-modal.test.tsx
- packages/developer-portal/src/core/__tests__/private-route-wrapper.tsx
- packages/developer-portal/src/sagas/__tests__/developer.ts
- packages/developer-portal/src/sagas/__tests__/settings.ts
- packages/developer-portal/src/sagas/apps/__test__/app-detail.test.ts
- packages/developer-portal/src/sagas/traffic-statistics/__tests__/traffic-statistics.ts
- packages/developer-portal/src/services/billing.ts
- scripts/webpack/webpack.config.dev.js
- yarn.lock
> feat: #2866 dev infra migration

- packages/developer-portal/src/constants/iframe-urls.ts
> feat: #2866 adds docs lambda endpoint

- packages/elements/package.json
> chore: #2866 bump elements version

- packages/elements/package.json
- packages/graphql-server/README.md
- scripts/release/utils.js
> fix: #2866 fixes a couple of config issues

- scripts/webpack/webpack.config.dev.js
> fix: #2866 don't cache elements in dev webpack

- scripts/webpack/webpack.config.prod.js
> fix: #2983 caching css fix

- .github/workflows/release-tag.yml
> fix: #2865 fix for GH Actions

- packages/cognito-custom-mail-lambda/src/mailer/__tests__/custom-mailer.ts
- packages/cognito-custom-mail-lambda/src/mailer/custom-mailer.ts
- packages/cognito-custom-mail-lambda/src/mailer/templates/ejs/admin-user-invite.ejs
- packages/cognito-custom-mail-lambda/src/mailer/templates/ejs/confirm-registration.ejs
- packages/cognito-custom-mail-lambda/src/mailer/templates/ejs/forgotten-password.ejs
> feat: #2649 updates connect mailer copy

- package.json
- packages/cognito-custom-mail-lambda/src/mailer/__tests__/custom-mailer.ts
- packages/cognito-custom-mail-lambda/src/mailer/custom-mailer.ts
- packages/cognito-custom-mail-lambda/src/mailer/templates/ejs/admin-user-invite.ejs
- packages/cognito-custom-mail-lambda/src/mailer/templates/ejs/forgotten-password.ejs
- yarn.lock
> feat: #2649 fixes email templates

- packages/elements/package.json
> chore: #2974 release elements

- packages/marketplace/src/components/pages/installed-apps/installed-apps.tsx
> fix: #3052 don't render helper text if no integrations

- packages/geo-diary/src/components/pages/appointment/__styles__/index.ts
> fix: #3121 Geo Diary css tweak

- package.json
- packages/developer-portal/package.json
- packages/developer-portal/src/components/pages/app-detail/__tests__/__snapshots__/app-content.test.tsx.snap
- packages/developer-portal/src/components/pages/app-detail/__tests__/__snapshots__/app-detail.test.tsx.snap
- packages/developer-portal/src/components/pages/app-detail/__tests__/app-content.test.tsx
- packages/developer-portal/src/components/pages/app-detail/app-content.tsx
- packages/developer-portal/src/components/pages/authentication/__test__/__snapshots__/authentication.test.tsx.snap
- packages/developer-portal/src/components/pages/authentication/__test__/authentication.test.tsx
- packages/developer-portal/src/components/pages/authentication/authentication.tsx
- yarn.lock
> feat: #3159 #3140 installs table non dev flow

- packages/graphql-server/src/resolvers/companies/dataloader.ts
- packages/graphql-server/src/resolvers/configurations/dataloader.ts
- packages/graphql-server/src/resolvers/conveyancing/dataloader.ts
- packages/graphql-server/src/resolvers/departments/dataloader.ts
- packages/graphql-server/src/resolvers/negotiators/dataloader.ts
- packages/graphql-server/src/resolvers/offices/dataloader.ts
- packages/graphql-server/src/resolvers/properties/dataloader.ts
- packages/graphql-server/src/resolvers/propertyImages/dataloader.ts
> fix: #3168 stop gql throwing when types undefined

- packages/developer-portal/src/components/pages/edit-app/form-schema/form-fields.ts
- packages/developer-portal/src/sagas/__tests__/current-member.test.ts
- packages/developer-portal/src/services/developers.ts
- packages/payments-service/src/controllers/__tests__/create-api-key.test.ts
- packages/payments-service/src/controllers/create-api-key.ts
- packages/utils/src/validators/__tests__/string.test.ts
- packages/utils/src/validators/string.ts
fixes: #3191 
fixes: #2962 
fixes: #3067 
> feat: #3191 #2962 #3067 dev portal fixes

- packages/marketplace/src/components/pages/app-detail/__styles__/app-install-confirmation.ts
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-install-confirmation.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/app-install-confirmation.tsx
> fix: #3170 fix overflow issue

- packages/data-warehouse/.sentryclirc
- packages/geo-diary/src/core/__tests__/__snapshots__/private-route-wrapper.test.tsx.snap
- packages/geo-diary/src/core/private-route-wrapper.tsx
- packages/payments-client/src/utils/headers.ts
- packages/payments-service/README.md
- packages/payments-service/serverless.yml
- yarn.lock
fixes: #3193 
fixes: #3236 
fixes: #3246
> feat: #3193 #3236 #3246 various fixes

- packages/marketplace/src/components/pages/app-detail/client/app-install-confirmation.tsx
> fix: #3251 install modal fix

- packages/reapit-connect-management/src/components/ui/offices/__tests__/__snapshots__/office-list-cell.test.tsx.snap
- packages/reapit-connect-management/src/components/ui/offices/create-office-group.tsx
- packages/reapit-connect-management/src/components/ui/offices/edit-office-group.tsx
- packages/reapit-connect-management/src/components/ui/offices/office-list-cell.tsx
- packages/reapit-connect-management/src/components/ui/users/edit-user-group.tsx
- packages/reapit-connect-management/src/components/ui/users/edit-user.tsx
> feat: #3272 fixes search, loses inline loader on tables

- packages/admin-portal/src/services/approvals.ts
- packages/developer-portal/src/selector/__tests__/auth.ts
- packages/developer-portal/src/selector/auth.ts
- packages/marketplace/src/components/pages/settings/setting.tsx
- packages/marketplace/src/constants/api.ts
- packages/marketplace/src/selector/auth/__tests__/auth.test.ts
- packages/marketplace/src/selector/auth/auth.ts
- packages/marketplace/src/utils/__tests__/route-dispatcher.ts
- packages/reapit-connect-management/src/core/index.tsx
- packages/reapit-connect-management/src/services/apps.ts
- packages/reapit-connect-management/src/types/global.d.ts
> feat: #3294 marketplace admin rcm fixes

- packages/reapit-connect-management/src/components/pages/__tests__/__snapshots__/offices.test.tsx.snap
- packages/reapit-connect-management/src/components/pages/__tests__/__snapshots__/users.test.tsx.snap
- packages/reapit-connect-management/src/components/pages/offices.tsx
- packages/reapit-connect-management/src/components/pages/users.tsx
- packages/reapit-connect-management/src/core/private-route-wrapper.tsx
chore: Reapit Connect Management
> chore: rcm add feature flag for demo

- packages/elements/src/components/ModalV2/index.tsx
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-detail.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-uninstall-confirmation.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/app-uninstall-confirmation.tsx
- packages/marketplace/src/components/pages/apps/coming-soon.tsx
fixes: #3319 
fixes: #3299 
fixes: #3301
> fix: #3299 #3301 #3319 various marketplace fixes

- packages/reapit-connect-management/src/components/ui/offices/__tests__/__snapshots__/create-office-group.test.tsx.snap
- packages/reapit-connect-management/src/components/ui/offices/__tests__/__snapshots__/edit-office-group.test.tsx.snap
- packages/reapit-connect-management/src/components/ui/offices/__tests__/create-office-group.test.tsx
- packages/reapit-connect-management/src/components/ui/offices/__tests__/edit-office-group.test.tsx
- packages/reapit-connect-management/src/services/__tests__/office.test.ts
- packages/reapit-connect-management/src/services/office.ts
> fix: #3331 use fetcher from element instead

- packages/reapit-connect-management/src/components/ui/users/edit-user-group.tsx
- packages/reapit-connect-management/src/utils/__tests__/header.test.ts
- packages/reapit-connect-management/src/utils/headers.ts
> fix: #3336 #3337 rcm auth fixes

- packages/reapit-connect-management/package.json
- packages/reapit-connect-management/src/components/ui/offices/__tests__/create-office-group.test.tsx
- packages/reapit-connect-management/src/components/ui/offices/__tests__/edit-office-group.test.tsx
- packages/reapit-connect-management/src/components/ui/offices/create-office-group.tsx
- packages/reapit-connect-management/src/components/ui/offices/edit-office-group.tsx
- packages/reapit-connect-management/src/components/ui/offices/form-fields.ts
- packages/reapit-connect-management/src/components/ui/offices/offices-groups-tab.tsx
- yarn.lock
> fix: #3341 fix errors saving groups

- packages/mailer-service/src/controllers/create-payment-request.ts
- packages/payments-client/src/components/pages/__tests__/__snapshots__/payments.test.tsx.snap
- packages/payments-client/src/components/pages/payment-external.tsx
- packages/payments-client/src/components/pages/payment.tsx
- packages/payments-client/src/components/pages/payments.tsx
- packages/payments-client/src/components/ui/__tests__/payments/__snapshots__/payment-request-modal.test.tsx.snap
- packages/payments-client/src/components/ui/__tests__/payments/payment-form.test.tsx
- packages/payments-client/src/components/ui/payments/payment-form.tsx
- packages/payments-client/src/components/ui/payments/payment-handlers.ts
- packages/payments-client/src/components/ui/payments/payment-page-content.tsx
- packages/payments-client/src/components/ui/payments/payment-request-modal.tsx
> feat: #3353 payments refinements

- packages/elements/src/components/CardInputGroup/__tests__/__snapshots__/card-input-group.test.tsx.snap
- packages/elements/src/components/CardInputGroup/card-input-group.tsx
- packages/mailer-service/serverless.yml
- packages/mailer-service/src/templates/create-payment-receipt.ejs
- packages/mailer-service/src/templates/create-payment-request.ejs
- packages/payments-client/src/components/pages/__tests__/__snapshots__/payments.test.tsx.snap
- packages/payments-client/src/components/pages/payment-external.tsx
- packages/payments-client/src/components/pages/payment-internal.tsx
- packages/payments-client/src/components/pages/payments.tsx
- packages/payments-client/src/components/ui/__stubs__/payment.ts
- packages/payments-client/src/components/ui/__tests__/payments/__snapshots__/payment-form.test.tsx.snap
- packages/payments-client/src/components/ui/__tests__/payments/payment-form.test.tsx
- packages/payments-client/src/components/ui/payment-logo.tsx
- packages/payments-client/src/components/ui/payments/payment-form.tsx
- packages/payments-client/src/components/ui/payments/payment-handlers.ts
- packages/payments-client/src/components/ui/payments/payment-page-content.tsx
- packages/payments-client/src/opayo-api/merchant-key.ts
- packages/payments-client/src/opayo-api/transactions.ts
- packages/payments-client/src/services/payment.ts
- packages/payments-service/serverless.yml
> feat: #3353 various ui tweaks and fixes

- packages/payments-service/serverless.yml
> feat: #3353 adds if-match header

- packages/reapit-connect-management/src/components/ui/users/edit-user-group.tsx
> fix: #3310 switch table buttons for links

- packages/marketplace/src/components/pages/app-detail/client/__tests__/__snapshots__/app-install-confirmation.test.tsx.snap
- packages/marketplace/src/components/pages/app-detail/client/app-install-confirmation.tsx
- packages/reapit-connect-management/src/components/pages/offices.tsx
- packages/reapit-connect-management/src/core/private-route-wrapper.tsx
> fix: #3310 #3402 show offices, fix launch link

- packages/payments-client/src/components/ui/payment-handlers.ts
> fix: #3353 allow non-unique transactions

- packages/reapit-connect-management/src/components/pages/__tests__/__snapshots__/marketplace-app.test.tsx.snap
- packages/reapit-connect-management/src/components/pages/__tests__/__snapshots__/marketplace.test.tsx.snap
- packages/reapit-connect-management/src/components/pages/__tests__/access-denied.test.tsx
- packages/reapit-connect-management/src/components/pages/__tests__/marketplace-app.test.tsx
- packages/reapit-connect-management/src/components/pages/__tests__/marketplace.test.tsx
- packages/reapit-connect-management/src/components/pages/access-denied.tsx
- packages/reapit-connect-management/src/components/pages/marketplace-app.tsx
- packages/reapit-connect-management/src/components/pages/marketplace.tsx
- packages/reapit-connect-management/src/components/ui/apps/__tests__/__snapshots__/app-card.test.tsx.snap
- packages/reapit-connect-management/src/components/ui/apps/__tests__/__snapshots__/app-pricing-permissions-section.test.tsx.snap
- packages/reapit-connect-management/src/components/ui/apps/__tests__/__snapshots__/app-toggle-visibility-section.test.tsx.snap
- packages/reapit-connect-management/src/components/ui/apps/__tests__/app-card.test.tsx
- packages/reapit-connect-management/src/components/ui/apps/__tests__/app-pricing-permissions-section.test.tsx
- packages/reapit-connect-management/src/components/ui/apps/__tests__/app-toggle-visibility-section.test.tsx
- packages/reapit-connect-management/src/components/ui/apps/app-card.tsx
- packages/reapit-connect-management/src/components/ui/apps/app-pricing-permissions-section.tsx
- packages/reapit-connect-management/src/components/ui/apps/app-toggle-visibility-section.tsx
- packages/reapit-connect-management/src/constants/api.ts
- packages/reapit-connect-management/src/constants/routes.ts
- packages/reapit-connect-management/src/core/__tests__/__snapshots__/router.test.tsx.snap
- packages/reapit-connect-management/src/core/router.tsx
- yarn.lock
fixes: #3430 
fixes: #3431 
- Partial fix, missing a few tests, will add in next PR
> feat: #3430 #3431 add app detail page rcm

- .vscode/settings.json
- packages/reapit-connect-management/src/components/ui/apps/__styled__/app-styles.ts
- packages/reapit-connect-management/src/components/ui/apps/__tests__/__snapshots__/app-card.test.tsx.snap
- packages/reapit-connect-management/src/components/ui/apps/__tests__/app-card.test.tsx
- packages/reapit-connect-management/src/components/ui/apps/app-card.tsx
> feat: #3432 add visual indicator of installs

- .github/workflows/codeql-analysis.yml
- .github/workflows/release-prod.yml
- .github/workflows/test-pr.yml
- package.json
- packages/data-warehouse/src/components/pages/analytics/analytics-handlers.ts
> fix: #3503 missing return statement, tweak to build script

- .github/ISSUE_TEMPLATE/cloud--internal-.md
- packages/data-warehouse/src/components/pages/__styles__/styles.ts
- packages/data-warehouse/src/components/pages/accounts/accounts.tsx
- packages/data-warehouse/src/components/pages/analytics/__tests__/__snapshots__/analytics-cost-explorer.test.tsx.snap
- packages/data-warehouse/src/components/pages/analytics/__tests__/__snapshots__/analytics.test.tsx.snap
- packages/data-warehouse/src/components/pages/analytics/__tests__/analytics-handlers.test.tsx
- packages/data-warehouse/src/components/pages/analytics/analytics-cost-explorer.tsx
- packages/data-warehouse/src/components/pages/analytics/analytics-handlers.ts
- packages/data-warehouse/src/components/pages/analytics/analytics.tsx
- packages/data-warehouse/src/components/pages/data/data.tsx
- packages/data-warehouse/src/components/pages/subscriptions/subscriptions-content.tsx
- packages/data-warehouse/src/components/pages/subscriptions/subscriptions.tsx
> feat: #3556 data warehouse analytics and copy updates:

- packages/data-warehouse/src/components/pages/analytics/__tests__/__snapshots__/analytics-cost-explorer.test.tsx.snap
- packages/data-warehouse/src/components/pages/analytics/__tests__/__snapshots__/analytics-monthly-usage.test.tsx.snap
- packages/data-warehouse/src/components/pages/analytics/analytics-cost-explorer.tsx
- packages/data-warehouse/src/components/pages/analytics/analytics-monthly-usage.tsx
- packages/data-warehouse/src/components/pages/subscriptions/subscriptions-content.tsx
> feat: #3556 dw text changes

- packages/cloud-alert/cypress/integration/node-services.test.ts
- packages/cloud-alert/cypress/integration/web-apps.test.ts
- packages/cloud-alert/cypress/support/constants.ts
- packages/data-warehouse/src/core/__tests__/__snapshots__/router.test.tsx.snap
- packages/data-warehouse/src/core/router.tsx
- packages/event-status-service/serverless.yml
- packages/mailer-service/serverless.yml
- packages/payments-service/serverless.yml
> fix: #3513 fix healthchecks

- packages/cloud-alert/cypress/integration/node-services.test.ts
- packages/cloud-alert/cypress/integration/web-apps.test.ts
- packages/data-warehouse/src/core/__tests__/__snapshots__/router.test.tsx.snap
- packages/data-warehouse/src/core/router.tsx
- packages/event-status-service/src/core/server.ts
- packages/reapit-connect/src/core/__tests__/__snapshots__/router.test.tsx.snap
- packages/reapit-connect/src/core/index.tsx
- packages/reapit-connect/src/core/router.tsx
- scripts/webpack/webpack.config.node.js
> fix: #3513 additional healthcheck fixes

- packages/graphql-server/webpack.config.js
- packages/payments-service/webpack.config.js
> fix: #3051 fix a couple of infra broken links

- packages/developer-portal/src/components/pages/webhooks/form-schema/form-fields.ts
- packages/developer-portal/src/reducers/webhooks-subscriptions/webhook-edit-modal.ts
> fix: #3596 tweak webhook etag behaviour

- packages/marketplace/src/services/apps.ts
- packages/marketplace/src/utils/__tests__/route-dispatcher.ts
- packages/marketplace/src/utils/route-dispatcher.ts
> feat: #3638 adds show hidden apps flag marketplace

- packages/data-warehouse/linaria.config.js
- packages/data-warehouse/src/components/pages/__tests__/__snapshots__/login.test.tsx.snap
- packages/data-warehouse/src/components/pages/accounts/__tests__/__snapshots__/account-progress-bar.test.tsx.snap
- packages/data-warehouse/src/components/pages/analytics/__tests__/__snapshots__/analytics-cost-explorer.test.tsx.snap
- packages/data-warehouse/src/components/pages/analytics/__tests__/__snapshots__/analytics-daily-usage.test.tsx.snap
- packages/data-warehouse/src/components/pages/analytics/__tests__/__snapshots__/analytics-monthly-usage.test.tsx.snap
- packages/data-warehouse/src/components/pages/analytics/analytics-handlers.ts
- packages/data-warehouse/src/components/pages/data/__tests__/__snapshots__/shares-table.test.tsx.snap
- packages/data-warehouse/src/components/pages/subscriptions/__tests__/__snapshots__/subscriptions.test.tsx.snap
- packages/data-warehouse/src/components/pages/subscriptions/subscriptions-content.tsx
> feat: #3639 data warehouse ui fixes

- packages/cloud-alert/cypress/support/constants.ts
- packages/cognito-custom-mail-lambda/src/mailer/templates/index.ts
- packages/geo-diary/src/graphql/client.ts
- packages/graphql-server/README.md
- packages/graphql-server/serverless.yml
- packages/graphql-server/src/__tests__/index.test.ts
- packages/graphql-server/src/errors/errors.ts
- packages/graphql-server/src/index.ts
- packages/graphql-server/src/utils/__tests__/handle-error.test.ts
- packages/graphql-server/src/utils/handle-error.ts
> feat: #3617 add gql authorizer

- packages/cognito-custom-mail-lambda/src/mailer/templates/index.ts
> fix: #3645 fixed template issue with mailer

- packages/ts-types/package.json
> fix: #3624 fix prod release workflow

- packages/events-service/serverless.yml
> fix: add new allowed CORS headers for the events endpoint

- packages/elements/README.md
- packages/elements/package.json
> feat: #56 elements v3 spec

- packages/foundations-ts-definitions/package.json
- packages/foundations-ts-definitions/scripts/create-index-file.js
- packages/foundations-ts-definitions/scripts/fetch-definitions.js
- packages/foundations-ts-definitions/scripts/format-code.js
- packages/foundations-ts-definitions/scripts/get-current-time-stamp-string.js
- packages/foundations-ts-definitions/scripts/handle-cronjob.js
- packages/foundations-ts-definitions/scripts/release-github.js
- packages/foundations-ts-definitions/scripts/release-npm.js
- packages/foundations-ts-definitions/scripts/update-npm.js
- packages/foundations-ts-definitions/types/marketplace-schema.ts
- packages/foundations-ts-definitions/types/platform-schema.ts
- packages/ts-scripts/package.json
> fix: #3888 ts definitions cron fix

- packages/admin-portal/src/components/pages/approvals/approvals.tsx
> fix: admin approval created row

- packages/elements/src/components-v3/Steps/__styles__/index.tsx
- packages/elements/src/components-v3/Steps/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components-v3/Steps/__tests__/index.tsx
- packages/elements/src/components-v3/Steps/index.tsx
- packages/elements/src/components-v3/Steps/steps.stories.mdx
- packages/elements/src/styles-v3/base/states.ts
- packages/elements/src/styles-v3/base/variables.ts
> feat: #2636 - add Steps component for use in the wizard

- packages/ts-scripts/src/webpack/webpack.config.dev.js
- packages/ts-scripts/src/webpack/webpack.config.prod.js
> fix: #3904 fix svg loading issue

- .github/workflows/release-prod.yml
- packages/developer-portal/src/components/pages/edit-app/__tests__/__snapshots__/developer-edit-app.test.tsx.snap
- packages/developer-portal/src/components/pages/edit-app/__tests__/__snapshots__/redirect-uri-section.test.tsx.snap
- packages/developer-portal/src/components/pages/edit-app/redirect-uri-section.tsx
- packages/developer-portal/src/components/pages/settings/billing/__tests__/__snapshots__/subscriptions.test.tsx.snap
- packages/developer-portal/src/components/pages/settings/billing/subscriptions.tsx
- packages/developer-portal/src/components/pages/settings/settings-billing-tab/__tests__/__snapshots__/settings-billing-tab.test.tsx.snap
- packages/developer-portal/src/components/pages/welcome/welcome.tsx
- packages/developer-portal/src/components/ui/submit-app-wizard/steps/__tests__/__snapshots__/step-before-you-start.test.tsx.snap
- packages/developer-portal/src/components/ui/submit-app-wizard/steps/step-before-you-start.tsx
- packages/reapit-connect/.sentryclirc
- packages/reapit-connect/src/core/index.tsx
- packages/reapit-connect/src/types/global.d.ts
- packages/ts-scripts/src/webpack/webpack.config.prod.js
fixes: #3908 
fixes: #3910 
fixes: #3912 
fixes: #3914 
fixes: #3911 
fixes: #3884
> fix: #3908 #3910 #3912 #3914 #3911 #3884 various bugfixes

- packages/aml-checklist/src/components/ui/modal/update-status.tsx
> fix: #3689 aml status update

- .github/workflows/release-prod.yml
> fix: #3908 setting env vars prod workflow

- packages/elements/src/components-v3/SecondaryNav/__styles__/index.tsx
- packages/elements/src/components-v3/SecondaryNav/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components-v3/SecondaryNav/__tests__/index.tsx
- packages/elements/src/components-v3/SecondaryNav/index.tsx
- packages/elements/src/components-v3/SecondaryNav/secondaryNav.stories.mdx
- packages/elements/src/styles-v3/base/variables.ts
> feat: #2632 - add SecondaryNav component, styles, story and tests

- packages/elements/src/components-v3/Loader/__styles__/index.tsx
- packages/elements/src/components-v3/Loader/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components-v3/Loader/__tests__/index.tsx
- packages/elements/src/components-v3/Loader/index.tsx
- packages/elements/src/components-v3/Loader/loader.stories.mdx
- packages/elements/src/styles-v3/base/states.ts
- packages/elements/src/styles-v3/base/variables.ts
> feat: #2626 - add a loader to the elements v3 lib

- packages/elements/src/components-v3/Loader/__styles__/index.tsx
- packages/elements/src/components-v3/Loader/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components-v3/Loader/index.tsx
- packages/elements/src/components-v3/Loader/loader.stories.mdx
- Adds an optional label to the loader
- Sets a sensible default width
- Increase the animation time
> feat: #2626 - loader tweaks

- packages/developer-portal/src/components/pages/webhooks/__tests__/__snapshots__/webhooks.test.tsx.snap
- packages/developer-portal/src/components/pages/webhooks/webhooks.tsx
- packages/developer-portal/src/sagas/webhook-logs/webhook-logs.ts
> fix: #3994 webhook logs table

- packages/elements/src/components-v3/Modal/__styles__/index.tsx
- packages/elements/src/components-v3/Modal/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components-v3/Modal/__tests__/index.tsx
- packages/elements/src/components-v3/Modal/index.tsx
- packages/elements/src/components-v3/Modal/modal.stories.mdx
- packages/elements/src/hooks/useModal-v3/index.tsx
- packages/elements/src/v3.tsx
#2629 
- Exports a `<Modal>` component and a `useModal` hook
- Plus stories/docs and tests
> feat: #2629 - modal v3

- packages/developer-portal/src/components/pages/desktop/__styles__/styles.tsx
- packages/developer-portal/src/components/pages/desktop/__tests__/__snapshots__/desktop.test.tsx.snap
- packages/developer-portal/src/components/pages/desktop/desktop.tsx
- packages/elements/package.json
- packages/elements/src/components-v3/Button/__styles__/index.tsx
- packages/elements/src/components/Modal/modal.stories.tsx
> fix: #4113 safari bug fix

- packages/foundations-ts-definitions/package.json
- packages/foundations-ts-definitions/scripts/create-index-file.js
- packages/foundations-ts-definitions/types/index.ts
- packages/foundations-ts-definitions/types/platform-schema.ts
> fix: #4324 fixes ts-definitions cron

- packages/elements/src/components-v3/Pagination/__styles__/index.ts
- packages/elements/src/components-v3/Pagination/__tests__/__snapshots__/pagination.test.tsx.snap
- packages/elements/src/components-v3/Pagination/__tests__/pagination.test.tsx
- packages/elements/src/components-v3/Pagination/index.tsx
- packages/elements/src/components-v3/Pagination/pagination.stories.mdx
- packages/elements/src/components-v3/Pagination/pagination.tsx
- packages/elements/src/v3.tsx
> feat: #2630 elements pagination

- packages/geo-diary/src/components/ui/map/google-map-component.tsx
> fix: hofix geo diary travel mode

- packages/cli/src/abstract.command.ts
- packages/cli/src/commands/deploy/list.ts
- packages/cli/src/commands/deploy/release.ts
- packages/cli/src/commands/deploy/version.ts
- packages/cli/src/commands/help.ts
- packages/cli/src/commands/pipeline/create.ts
- packages/cli/src/commands/pipeline/run.ts
- packages/cli/src/commands/react-starter.ts
- packages/cli/src/parent.command.ts
- packages/cli/src/utils/config.ts
- packages/deployment-service-ui/package.json
- packages/deployment-service-ui/src/components/pages/pipelines/create.tsx
- packages/deployment-service-ui/src/components/pages/pipelines/list.tsx
- packages/deployment-service-ui/src/components/pages/pipelines/show.tsx
- packages/deployment-service-ui/src/components/pages/releases.tsx
- packages/deployment-service-ui/src/components/ui/__tests__/__snapshots__/menu.test.tsx.snap
- packages/deployment-service-ui/src/components/ui/menu.tsx
- packages/deployment-service-ui/src/constants/api.ts
- packages/deployment-service-ui/src/constants/routes.ts
- packages/deployment-service-ui/src/core/__tests__/__snapshots__/router.test.tsx.snap
- packages/deployment-service-ui/src/core/index.tsx
- packages/deployment-service-ui/src/core/router.tsx
- packages/deployment-service-ui/src/platform-api/configuration-api.ts
- packages/deployment-service-ui/src/platform-api/pipelines.ts
- packages/deployment-service-ui/src/platform-api/releases.ts
- packages/deployment-service-ui/src/types/global.d.ts
- packages/deployment-service/serverless.yml
- packages/deployment-service/src/constants.ts
- packages/deployment-service/src/functions/deploy/release.ts
- yarn.lock
> fix: deployment run through fixes

- packages/cli/src/commands/deploy/release.ts
- packages/cli/src/commands/pipeline/run.ts
- packages/deployment-service/src/functions/pipeline/pipeline-run.ts
> fix: deployment fixes

- packages/developer-portal/src/components/ui/__tests__/terms-and-conditions-modal/__snapshots__/terms-and-conditions.tsx.snap
- packages/developer-portal/src/components/ui/terms-and-conditions-modal/__styles__/terms-and-conditions.ts
- packages/developer-portal/src/components/ui/terms-and-conditions-modal/terms-and-conditions.tsx
- packages/elements/src/components-v3/Card/card-components.tsx
- packages/elements/src/components-v3/Card/card.stories.mdx
- packages/elements/src/components-v3/Card/index.tsx
> fix: #4386 t and cs fix

- packages/developer-portal/src/constants/developer-help-links.ts
> fix: #4448 missed label in url

- packages/developer-portal/src/components/pages/desktop/__tests__/__snapshots__/desktop.test.tsx.snap
- packages/elements/src/components/button/__styles__/index.tsx
- packages/elements/src/components/button/__tests__/__snapshots__/index.tsx.snap
- packages/elements/src/components/button/__tests__/index.tsx
- packages/elements/src/components/button/button.stories.mdx
- packages/elements/src/components/button/index.tsx
- packages/elements/src/helpers/intent.ts
fixes: #4407 
Add floating button and button group components.
> feat: #4407 v3 component refactor

- packages/developer-portal/src/components/pages/desktop/__tests__/__snapshots__/desktop.test.tsx.snap
- packages/elements/src/styles/spacing.stories.mdx
- packages/elements/src/styles/spacing.ts
> feat: #4407 v3 storybook entries spacing

- packages/elements/src/components/button/__styles__/index.ts
fixes button with both chevrons
> fix: corrected button chevron with both applied
