reapit/foundations

packages/elements/src/components/grid/__styles__/index.ts
=> fix: corrected tablet grid span

.github/workflows/release-prod.yml, packages/elements-legacy/package.json, packages/elements/package.json, packages/geo-diary/serverless.beta.yml
=> feat: #4536 release geo diary beta

packages/foundations-ts-definitions/package.json
=> chore: bump foundations version

packages/deployment-service-ui/src/components/pages/pipelines/create.tsx, packages/deployment-service-ui/src/platform-api/pipelines.ts, packages/deployment-service/README.md, packages/deployment-service/src/functions/pipeline/pipeline-create.ts, packages/deployment-service/src/functions/pipeline/pipeline-update.ts
=> feat: #4588 pipeline UI creation

packages/deployment-service/serverless.yml, packages/deployment-service/src/functions/pipeline/pipeline-delete.ts, packages/deployment-service/src/functions/pipeline/pipeline-runner-get.ts, packages/deployment-service/src/functions/pipeline/pipeline-update.ts
=> fix: corrected paths in serverless

packages/deployment-service/src/functions/pipeline/pipeline-get.ts
=> fix: corrected path parameter name

packages/cli/src/abstract.command.ts
=> chore: updated deployment url

packages/deployment-service/README.md
fixes: #4613 
Basic docs for developing on deployment-service
=> docs: added docs for deployment service

packages/deployment-service/serverless.yml, packages/deployment-service/src/constants.ts, packages/deployment-service/src/entities/index.ts, packages/deployment-service/src/executables/pull.ts, packages/deployment-service/src/functions/pipeline/pipeline-runner-create.ts, packages/deployment-service/src/functions/pipeline/task-population.ts, packages/deployment-service/src/functions/pipeline/task-runner.ts, packages/deployment-service/webpack.config.js
=> fix: deployment issues and queue issues

packages/api-docs-lamda/serverless.yml, packages/api-key-service/serverless.yml, packages/config-service/serverless.yml, packages/deployment-service/serverless.yml, packages/events-service/serverless.yml, packages/mailer-service/serverless.yml, packages/payments-service/serverless.yml
=> fix: #4641 fixes malformed serverless templates

packages/developer-portal/src/components/pages/desktop/__styles__/styles.tsx, packages/developer-portal/src/components/pages/desktop/desktop.tsx
=> feat: #4269 update de pricing

.github/workflows/release-dev.yml, packages/seed-data-workflow/tsconfig.json
=> fix: #4596 #4646 release dev from origin head, fix seed workflow

.github/workflows/release-dev.yml
=> feat: #4271 revert release dev

packages/seed-data-workflow/package.json, packages/seed-data-workflow/src/index.ts, yarn.lock
=> fix: #4596 fix seed data workflow

packages/deployment-service/src/executables/build.ts, packages/deployment-service/src/executables/install.ts, packages/deployment-service/src/executables/pull.ts
=> feat: resolved exec methods

packages/deployment-service-ui/src/components/pages/pipelines/show.tsx, packages/deployment-service-ui/src/components/pages/pipelines/update.tsx, packages/deployment-service-ui/src/constants/routes.ts, packages/deployment-service-ui/src/core/__tests__/__snapshots__/router.test.tsx.snap, packages/deployment-service-ui/src/core/router.tsx, packages/deployment-service-ui/src/platform-api/pipelines.ts, packages/deployment-service/src/entities/index.ts, packages/foundations-ts-definitions/deployment-schema/index.ts
=> feat: deployment service UI update

packages/app-builder-backend/package.json
hopefully fixes https://github.com/reapit/foundations/runs/3290067788
=> fix: hopefully fix dev release docker build fail

packages/security-header-lambda/serverless.yml
=> feat: #3454 updates security header infra

packages/deployment-service/src/functions/pipeline/codebuild-pipeline-updater.ts, packages/deployment-service/src/functions/pipeline/version-deploy.ts
=> chore: fix linting issue on release

packages/deployment-service-ui/src/components/pages/pipelines/show.tsx, packages/deployment-service-ui/src/components/task/index.tsx, packages/deployment-service-ui/src/components/task/task.element.tsx, packages/deployment-service-ui/src/utils/status-to-intent.ts, packages/deployment-service/migrations/1630509406008-pipeline-signed-url.ts, packages/deployment-service/migrations/1630659208268-pipeline-signed-url-length.ts, packages/deployment-service/package.json, packages/deployment-service/serverless.yml, packages/deployment-service/src/entities/index.ts, packages/deployment-service/src/functions/pipeline/codebuild-executor.ts, packages/deployment-service/src/functions/pipeline/codebuild-pipeline-updater.ts, packages/deployment-service/src/services/pipeline.ts, packages/deployment-service/src/services/s3.ts, packages/foundations-ts-definitions/deployment-schema/index.ts
fixes: #4895 
- fix delete pipeline
- fix pusher implementation (toISOString on string not date)
- add order for tasks 
- revert script for DB rollback of migration
=> feat: #4895 deployment codebuild logs

packages/deployment-service/src/core/db.ts, packages/deployment-service/src/functions/pipeline/codebuild-executor.ts, packages/deployment-service/src/functions/pipeline/codebuild-pipeline-updater.ts, packages/deployment-service/src/functions/pipeline/version-deploy.ts
=> fix: attempting to close db connection in sqs funcs

packages/deployment-service/src/core/db.ts, packages/deployment-service/src/functions/pipeline/codebuild-executor.ts, packages/deployment-service/src/functions/pipeline/codebuild-pipeline-updater.ts, packages/deployment-service/src/functions/pipeline/version-deploy.ts
=> fix: hanging promises

packages/deployment-service-ui/src/components/pages/pipelines/show.tsx, packages/deployment-service-ui/src/components/task/index.tsx, packages/deployment-service-ui/src/utils/friendly-function-name.ts, packages/elements/src/components/status-indicator/__styles__/index.ts
=> fix: task design fixes

packages/deployment-service/src/functions/release/release-paginate.ts
=> fix: project params incorrect for release paginate

packages/deployment-service/serverless.yml
=> fix: queue visibility property

packages/deployment-service/src/executables/deploy-to-live.ts
=> feat: added content type to s3

packages/deployment-service-ui/src/components/pages/pipelines/show.tsx, packages/deployment-service-ui/src/utils/status-to-intent.ts, packages/deployment-service/serverless.yml, packages/deployment-service/src/functions/pipeline/codebuild-deploy.ts
=> feat: #4951 invalidate cache on deploy

packages/deployment-service/src/functions/pipeline/pipeline-runner-create.ts
=> feat: condition to prevent deployments at certain states

packages/deployment-service-ui/src/components/pages/pipelines/list.tsx, packages/deployment-service-ui/src/components/pages/pipelines/show.tsx, packages/deployment-service-ui/src/core/__tests__/__snapshots__/app.test.tsx.snap, packages/deployment-service-ui/src/core/app.tsx, packages/deployment-service/serverless.yml, packages/deployment-service/src/functions/index.ts, packages/deployment-service/src/functions/pipeline/codebuild-deploy.ts, packages/deployment-service/src/functions/pipeline/codebuild-pipeline-updater.ts, packages/deployment-service/src/functions/pipeline/pipeline-delete.ts, packages/deployment-service/src/functions/pusher-auth.ts
=> feat: #4899 pusher auth

packages/developer-portal/src/components/pages/api-docs/api-docs.tsx
=> refactor: rename links to API and warehouse

packages/developer-portal/src/components/pages/api-docs/api-docs.tsx
=> fix: pural APIs

packages/developer-portal/src/components/pages/api-docs/api-docs.tsx
=> feat: remove dev condition

packages/developer-portal/src/components/pages/api-docs/api-docs.tsx
=> fix: added an 's' to API

packages/deployment-service/serverless.yml
=> feat: added policy to make s3 bucket public

packages/deployment-service/package.json
=> feat: added db commands to release

packages/deployment-service/package.json
=> fix: corrected file path for db conf

packages/deployment-service/serverless.yml
=> feat: added policies for version bucket

packages/geo-diary-marketing/src/components/features-slide.svelte, packages/geo-diary-marketing/src/components/intro-slide.svelte
=> feat: #4688 a couple more style tweaks

packages/elements/src/components/layout/__styles__/index.ts, packages/geo-diary-marketing/src/components/availability-slide.svelte, packages/marketplace/src/components/pages/apps/__tests__/__snapshots__/coming-soon.test.tsx.snap, packages/marketplace/src/components/pages/apps/coming-soon.tsx
fixes: #4688 
fixes: #5065 
fixes: #5082
=> fix: #4688 #5065 #5082 various fixes

packages/insights/src/components/pages/home.tsx
=> fix: #5111 adds insights fix

packages/login-with-reapit/src/index.ts
=> feat: enabled shadow root elements

packages/login-with-reapit/public/index.html, packages/login-with-reapit/src/components/permission.svelte
=> fix: design fixes

packages/login-with-reapit/package.json
=> feat: added publish command

packages/login-with-reapit/package.json
=> fix: bump version

packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/__tests__/filter-form.test.tsx, packages/developer-portal/src/components/pages/analytics/detailed/filter-bar/filter-form.tsx
=> fix: #5347 fixes analytics filter bug

packages/deployment-service/cdk/lib/cdk-stack.ts, packages/deployment-service/src/functions/pipeline/pipeline-setup.ts, packages/deployment-service/src/utils/resolve-customer.ts
=> fix: user pool id correction

packages/marketplace-management/src/components/ui/offices/__tests__/__snapshots__/offices-tab.test.tsx.snap, packages/marketplace-management/src/components/ui/offices/__tests__/office-group-create.test.tsx, packages/marketplace-management/src/components/ui/offices/__tests__/office-group-edit-form.test.tsx, packages/marketplace-management/src/components/ui/offices/office-group-create.tsx, packages/marketplace-management/src/components/ui/offices/office-group-edit-form.tsx, packages/marketplace-management/src/components/ui/offices/offices-groups-tab.tsx, packages/marketplace-management/src/components/ui/offices/offices-tab.tsx, packages/marketplace-management/src/types/organisations-schema.ts, packages/marketplace-management/src/utils/use-org-id.tsx
=> fix: #5408 mm single org

packages/utils-react/src/get-platform-headers/__tests__/index.test.ts, packages/utils-react/src/get-platform-headers/index.ts
=> fix: allow connect session to manage redirects

packages/marketplace-management/src/components/ui/users/edit-user-group.tsx
=> fix: #5430 fix mm user group bug

packages/deployment-service/cdk/cdk.ts, packages/deployment-service/cdk/lib/cdk-stack.ts, packages/deployment-service/cdk/lib/create-aurora.ts, packages/deployment-service/cdk/lib/create-lambda.ts, packages/deployment-service/cdk/lib/create-policies.ts, packages/deployment-service/package.json, packages/deployment-service/src/config/db.ts, packages/deployment-service/src/utils/resolve-customer.ts, yarn.lock
=> fix: deployment service deployment

packages/elements/package.json, packages/elements/src/components/button/__styles__/index.ts, packages/elements/src/components/button/button.stories.mdx, packages/elements/src/components/button/button.tsx, packages/elements/src/components/card/__styles__/index.ts, packages/elements/src/components/card/card.stories.mdx, packages/elements/src/components/input-group/__styles__/index.ts, packages/elements/src/components/input/__styles__/index.ts, packages/elements/src/components/modal/modal.stories.mdx, packages/elements/src/components/nav/__tests__/__snapshots__/nav-responsive.test.tsx.snap, packages/elements/src/components/nav/__tests__/nav-responsive.test.tsx, packages/elements/src/components/nav/nav-responsive.tsx, packages/elements/src/components/pagination/__styles__/index.ts, packages/elements/src/components/searchable-dropdown/__styles__/index.ts, packages/elements/src/components/searchable-dropdown/__tests__/__snapshots__/searchable-dropdown.test.tsx.snap, packages/elements/src/components/searchable-dropdown/__tests__/searchable-dropdown.test.tsx, packages/elements/src/components/searchable-dropdown/index.ts, packages/elements/src/components/searchable-dropdown/searchable-dropdown.stories.mdx, packages/elements/src/components/searchable-dropdown/searchable-dropdown.tsx, packages/elements/src/components/select/__styles__/index.ts, packages/elements/src/components/snack/snack.stories.mdx, packages/elements/src/components/steps/steps.stories.mdx, packages/elements/src/components/table/__styles__/index.ts, packages/elements/src/components/table/table.stories.mdx, packages/elements/src/components/textarea/__styles__/index.ts, packages/elements/src/components/toggle/toggle.stories.mdx, packages/elements/src/storybook/changelog.stories.mdx, packages/elements/src/storybook/demo-block.tsx
=> feat: #5343 elements review fixes

.github/workflows/rollback-prod.yml
=> fix: freeze lock file

.github/workflows/rollback-prod.yml
=> fix: updated freeze tag

.github/workflows/rollback-prod.yml
=> fix: roll back immute

packages/elements/package.json, packages/elements/src/components/input/__styles__/index.ts, packages/elements/src/components/select/__styles__/index.ts, packages/elements/src/storybook/changelog.stories.mdx
=> fix: #5551 elements select fix

packages/marketplace/src/components/pages/apps/coming-soon.tsx
=> chore: #5464 updated coming soons

packages/marketplace-management/src/services/user.ts
=> fix: #5502 encode email address mm app

packages/auto-reply-bot/action/index.js, packages/auto-reply-bot/src/app.js
=> fix: auto bot improvements

packages/app-builder-backend/src/entities/property.ts, packages/app-builder-backend/src/platform/apps.ts, packages/app-builder-backend/src/resolvers/app-resolver.ts, packages/app-builder/src/components/ui/user/ejectable/form.tsx, packages/elements/src/components/searchable-dropdown/searchable-dropdown.tsx, packages/graphql-server/src/resolvers/keys/api.ts, packages/graphql-server/src/resolvers/keys/types.graphql
=> fix: various app builder fixes

packages/cra-template-foundations/package.json, packages/cra-template-foundations/template.json, packages/elements-legacy/package.json, packages/elements/package.json, packages/elements/src/storybook/changelog.stories.mdx, packages/elements/src/storybook/intro.stories.mdx
=> fix: #5564 elements v2 release

.github/workflows/definitions-update.yml, packages/foundations-ts-definitions/scripts/handle-cronjob.js
=> fix: #5549 ts definitions workflow test

.github/workflows/definitions-update.yml
=> fix: #5549 workflow syntax error

.github/workflows/definitions-update.yml
=> fix: #5549 remove uses as already in scope

.github/workflows/definitions-update.yml
=> fix: #5549 attempts different syntax

.github/workflows/definitions-update.yml
=> fix: #5549 tries a different config

.github/workflows/definitions-update.yml
=> fix: #5549 revert to default token

.github/workflows/definitions-update.yml, .husky/pre-push
=> fix: #5549 disable tests check

.github/workflows/definitions-update.yml
=> fix: #5549 remove run on pr

packages/utils-common/src/reapit-data/actions/api-constants.ts, packages/utils-common/src/reapit-data/actions/get.ts, packages/utils-common/src/reapit-data/actions/update.ts, packages/utils-react/src/use-reapit-data/__tests__/use-reapit-update.test.ts, packages/utils-react/src/use-reapit-data/use-reapit-update.ts
=> refactor: pipeline creation fixes

packages/developer-portal/src/components/pages/webhooks/__tests__/__snapshots__/webhooks-controls.test.tsx.snap, packages/developer-portal/src/components/pages/webhooks/__tests__/__snapshots__/webhooks.test.tsx.snap, packages/developer-portal/src/components/pages/webhooks/__tests__/webhooks-controls.test.tsx, packages/developer-portal/src/components/pages/webhooks/webhooks-controls.tsx, packages/developer-portal/src/components/pages/webhooks/webhooks.tsx, packages/insights/src/components/pages/__tests__/__snapshots__/home.test.tsx.snap, packages/insights/src/components/pages/home.tsx, packages/marketplace-management/src/components/pages/__tests__/__snapshots__/marketplace-app.test.tsx.snap, packages/marketplace-management/src/components/pages/__tests__/__snapshots__/marketplace.test.tsx.snap, packages/marketplace-management/src/components/pages/__tests__/__snapshots__/offices.test.tsx.snap, packages/marketplace-management/src/components/pages/__tests__/__snapshots__/users.test.tsx.snap, packages/marketplace-management/src/components/pages/marketplace-app.tsx, packages/marketplace-management/src/components/pages/marketplace.tsx, packages/marketplace-management/src/components/ui/nav/__tests__/__snapshots__/nav.test.tsx.snap, packages/marketplace-management/src/components/ui/nav/nav.tsx, packages/marketplace-management/src/components/ui/offices/__tests__/__snapshots__/offices-groups-tab.test.tsx.snap, packages/marketplace-management/src/components/ui/offices/__tests__/__snapshots__/offices-tab.test.tsx.snap, packages/marketplace-management/src/components/ui/offices/offices-groups-tab.tsx, packages/marketplace-management/src/components/ui/offices/offices-tab.tsx, packages/marketplace-management/src/components/ui/users/__tests_/__snapshots__/user-groups-tab.test.tsx.snap, packages/marketplace-management/src/components/ui/users/__tests_/__snapshots__/users-tab.test.tsx.snap, packages/marketplace-management/src/components/ui/users/user-groups-tab.tsx, packages/marketplace-management/src/components/ui/users/users-tab.tsx
=> feat: #5515 mobile UI

packages/cli/src/commands/release/deploy.ts
=> refactor: moved bump version to after successful deploy

packages/developer-portal/src/components/pages/edit-app/developer-edit-app.tsx, packages/developer-portal/src/components/pages/swagger/swagger.tsx, packages/developer-portal/src/components/pages/webhooks/__tests__/__snapshots__/webhooks-manage.test.tsx.snap, packages/developer-portal/src/components/pages/webhooks/webhooks-logs.tsx, packages/developer-portal/src/components/pages/webhooks/webhooks-manage.tsx, packages/login-with-reapit/package.json
fixes: #5536 
fixes: #5535 
fixes: #5515
=> chore: #5536 #5535 add feature flag

packages/app-builder/src/core/config.ts
=> fix: app-builder api url

packages/app-builder/src/components/ui/viewport/inject-frame-styles.tsx
=> fix: app builder scrolling on small screens

packages/cli/src/commands/react-starter.ts
=> chore: remove serverless config from cli command react-template

packages/cli/src/abstract.command.ts, packages/cli/src/commands/help.ts, packages/cli/src/index.ts, packages/cli/src/parent.command.ts
=> feat: added singular command help prints

packages/cli/src/commands/react-starter.ts
=> refactor: changed react template command name to bootstrap

packages/cli/README.md, packages/cli/src/commands/config.ts, packages/cli/src/intro.ts
=> feat: added note about where to get api-key

packages/cli/src/commands/help.ts, packages/cli/src/commands/pipeline/deploy-local.ts, packages/cli/src/commands/pipeline/deploy.ts, packages/cli/src/commands/pipeline/index.ts, packages/cli/src/commands/release/index.ts, packages/cli/src/parent.command.ts
=> refactor: renamed and restructured pipeline deploy commands

packages/cli/src/commands/pipeline/create.ts, packages/cli/src/commands/pipeline/deploy.ts, packages/deployment-service/src/functions/pipeline/pipeline-setup.ts
=> feat: architecture pusher cli updates

packages/cli/src/commands/pipeline/create.ts
=> fix: change pipeline values in local json

packages/deployment-service-ui/src/components/task/index.tsx, packages/elements/package.json, packages/elements/src/storybook/changelog.stories.mdx, packages/elements/src/storybook/random-id.ts
=> fix: #5674 multi select chrome 69 issue

packages/marketplace-management/src/components/pages/__tests__/offices.test.tsx, packages/marketplace-management/src/components/pages/__tests__/users.test.tsx, packages/marketplace-management/src/components/pages/offices.tsx, packages/marketplace-management/src/components/pages/users.tsx
=> fix: #5670 broken docs link mm app

.gitignore, packages/ts-scripts/src/cdk/utils/output.ts
=> fix: gitignore'd file

packages/utils-common/src/reapit-data/actions/api-constants.ts
=> feat: added deployment url

packages/cli/src/abstract.command.ts
=> feat: updated deployment url for cli

packages/app-builder/src/components/ui/render-node/index.tsx
=> fix: undefined ref

packages/app-builder-backend/src/ddb.ts, packages/app-builder/package.json, packages/app-builder/src/components/ui/render-node/index.tsx
=> fix: app builder local dev

packages/elements/package.json, packages/elements/src/components/searchable-dropdown/searchable-dropdown.stories.mdx, packages/elements/src/storybook/changelog.stories.mdx, packages/elements/src/storybook/render-html-markup.tsx
=> fix: #5807 storybook rendering bug

packages/cli/README.md, packages/cli/package.json, packages/cli/src/abstract.command.ts, packages/cli/src/commands/pipeline/deploy-local.ts, packages/cli/src/commands/release/list.ts, packages/cli/src/utils/config.ts, packages/cli/src/utils/resolveArgs.ts
=> feat: cli env config

packages/cli/README.md
=> feat: added more description to readme

packages/app-builder-backend/README.md, packages/ts-bundler/src/remove-deps.ts, packages/ts-bundler/src/ts-bundler.ts, packages/ts-bundler/src/workspace-deps.ts, packages/ts-bundler/src/yarn-lock.ts
=> fix: app builder ci

packages/elements/src/components/tool-tip/__styles__/index.ts, packages/elements/src/components/tool-tip/__tests__/__snapshots__/tool-tip.test.tsx.snap, packages/elements/src/components/tool-tip/__tests__/tool-tip.test.tsx, packages/elements/src/components/tool-tip/index.tsx, packages/elements/src/components/tool-tip/tool-tip-story-component.tsx, packages/elements/src/components/tool-tip/tooltip.stories.mdx, packages/elements/src/index.ts, packages/geo-diary/src/components/pages/appointment/__tests__/__snapshots__/appointment.test.tsx.snap, packages/geo-diary/src/components/ui/contact-drawer/property-drawer.tsx, packages/geo-diary/src/graphql/fragments/property-model.graphql, packages/geo-diary/src/types/global.d.ts
=> feat: key details in geo diary

packages/ts-scripts/src/cdk/components/api-gateway-api.ts, packages/ts-scripts/src/cdk/components/stack-event-handler.ts
=> fix: added cors headers by default

packages/elements/src/components/searchable-dropdown/searchable-dropdown.stories.mdx
=> fix: added storyboard header

packages/deployment-service/src/functions/pipeline/pipeline-setup.ts
=> fix: remove vip ssl support from cloudfront dist

packages/geo-diary/src/components/pages/appointment/__mocks__/appointments-query.ts, packages/geo-diary/src/components/pages/appointment/__tests__/__snapshots__/appointment.test.tsx.snap, packages/geo-diary/src/components/ui/cancel-confirm-modal/__tests__/__snapshots__/index.test.tsx.snap, packages/geo-diary/src/components/ui/contact-drawer/__tests__/__snapshots__/property-drawer.test.tsx.snap, packages/geo-diary/src/components/ui/contact-drawer/__tests__/property-drawer.test.tsx, packages/geo-diary/src/components/ui/contact-drawer/property-drawer.tsx, packages/geo-diary/src/components/ui/follow-up-notes-modal/__tests__/__snapshots__/index.test.tsx.snap, packages/geo-diary/src/graphql/fragments/property-model.graphql
=> feat: #5861 adds price to geo diary

.github/workflows/release-prod.yml
=> fix: added PAT to checkout for protected pushes

packages/aml-checklist/jest.config.js, packages/aml-checklist/src/components/ui/forms/__tests__/identification.tsx, packages/aml-checklist/src/components/ui/forms/identification.tsx, packages/aml-checklist/src/components/ui/modal/address-information/address-information.tsx, packages/aml-checklist/src/sagas/__tests__/checklist-detail.test.ts, packages/aml-checklist/src/sagas/checklist-detail.ts
=> fix: #5576 #5577 aml fixes

packages/marketplace/src/components/pages/apps/coming-soon.tsx
=> chore: #5872 update coming soons

packages/graphql-server/jest.config.js, packages/graphql-server/tsconfig.json, packages/ts-scripts/src/index.js, packages/ts-scripts/src/jest/jest-setup.js, packages/ts-scripts/src/jest/jest.config.node.js
=> feat: jest node config

packages/marketplace-management/src/components/ui/users/__tests_/__snapshots__/edit-user-group.test.tsx.snap, packages/marketplace-management/src/components/ui/users/__tests_/__snapshots__/user-groups-tab.test.tsx.snap, packages/marketplace-management/src/components/ui/users/__tests_/edit-user-group.test.tsx, packages/marketplace-management/src/components/ui/users/edit-user-group.tsx
=> feat: #5683 add user search mm app

packages/deployment-service/src/functions/pipeline/pipeline-setup.ts
=> fix: added sslmethod default value

packages/marketplace-management/src/components/ui/users/edit-user-group.tsx
=> feat: #5683 hotfix

packages/developer-portal/src/components/pages/apps-new/__tests__/__snapshots__/permissions-options-content.test.tsx.snap, packages/developer-portal/src/components/pages/apps-new/__tests__/__snapshots__/step-options-content.test.tsx.snap, packages/developer-portal/src/components/pages/apps-new/__tests__/permissions-options-content.test.tsx, packages/developer-portal/src/components/pages/apps-new/config.tsx, packages/developer-portal/src/components/pages/apps-new/permissions-options-content.tsx, packages/utils-common/src/reapit-data/actions/api-constants.ts, packages/utils-common/src/reapit-data/actions/get.ts
=> feat: #5870 adds fetch for permissions on app create flow

packages/deployment-service/cdk/lib/cdk-stack.ts
=> fix: increasing setup timeout again?

packages/deployment-service/src/functions/pipeline/pipeline-create.ts, packages/deployment-service/src/subscribers/sub-domain.ts
=> feat: sub domain maintain

packages/cli/src/commands/pipeline/create.ts
=> feat: added condition to prevent pusher time offset

packages/cli/src/abstract.command.ts
=> fix: annoying typescript issue on prod release

packages/cli/package.json
=> fix: corrected config name for cli

packages/deployment-service/cdk/lib/create-sqs.ts
=> fix: updated queue timeout to match lambda

packages/ts-scripts/src/cdk/components/rds-database.ts
=> feat: add bastion to stack if stack has rds db

packages/elements/src/storybook/changelog.stories.mdx, packages/elements/src/storybook/intro.stories.mdx
=> feat: #6001 adds figma community file to docs

packages/developer-portal/src/components/pages/apps-new/__tests__/__snapshots__/auth-options-content.test.tsx.snap, packages/developer-portal/src/components/pages/apps-new/__tests__/__snapshots__/step-options-content.test.tsx.snap, packages/developer-portal/src/components/pages/apps-new/auth-options-content.tsx, packages/developer-portal/src/components/pages/webhooks/__tests__/__snapshots__/webhooks-new-app.test.tsx.snap, packages/developer-portal/src/components/pages/webhooks/__tests__/__snapshots__/webhooks-new.test.tsx.snap, packages/developer-portal/src/components/pages/webhooks/__tests__/__snapshots__/webhooks.test.tsx.snap, packages/developer-portal/src/components/pages/webhooks/webhooks-new-app.tsx, packages/developer-portal/src/components/pages/webhooks/webhooks-new-customers.tsx
=> feat: #5989 sbox default for webhooks

packages/marketplace/src/components/pages/apps/coming-soon.tsx
=> feat: #5993 update coming soon

packages/developer-portal/src/scripts/chat-bot.js
=> feat: #5992 adds zendesk widget to dev

packages/insights/src/components/pages/home.tsx
=> feat: #6000 hotfix screen orientation

packages/deployment-service/src/functions/pipeline/pipeline-setup.ts
=> fix: add TLS version to cloudfront dist

packages/api-key-service/jest.config.js, packages/api-key-verify/jest.config.js, packages/app-builder-backend/jest.config.js, packages/cognito-custom-mail-lambda/jest.config.js, packages/config-service/jest.config.js, packages/events-service/jest.config.js, packages/mailer-service/jest.config.js, packages/payments-service/jest.config.js
=> refactor: #5658 jest for node

packages/developer-portal/src/components/pages/v8/pipeline/index.tsx
=> fix: pipeline auth uri

packages/admin-portal/src/components/pages/usage/__tests__/__snapshots__/usage-table.test.tsx.snap, packages/admin-portal/src/components/pages/usage/usage-table.tsx
=> feat: #6022 add monthly billing total

packages/auto-reply-bot/src/app.js
=> fix: key needs to be lowercase also

packages/geo-diary/src/components/pages/appointment/__tests__/__snapshots__/appointment.test.tsx.snap, packages/geo-diary/src/components/pages/appointment/appointment.tsx, packages/geo-diary/src/graphql/queries/get-appointments.graphql
=> feat: #6055 increase geo diary appointment limit

packages/utils-react/src/key-animation/__styles__/key-animation.ts, packages/utils-react/src/key-animation/__tests__/__snapshots__/key-animation.test.tsx.snap, packages/utils-react/src/key-animation/key-animation.tsx
=> fix: added auto width and height to svg

packages/admin-portal/src/components/pages/devs-management/devs-management.tsx
=> feat: #6074 add agreed terms admin

packages/developer-portal/src/components/pages/edit-app/developer-edit-app.tsx, packages/developer-portal/src/components/ui/developer-edition-modal/modal-content.tsx
=> feat: #6060 update subs modal text

packages/deployment-service/src/entities/index.ts
=> fix: added metadata type for event

packages/deployment-service/src/entities/index.ts
=> fix: corrected mix up of function types

packages/developer-portal/src/components/pages/v8/__tests__/__snapshots__/app-detail-v8-edit.test.tsx.snap, packages/developer-portal/src/components/pages/v8/__tests__/__snapshots__/app-detail-v8.test.tsx.snap, packages/elements/src/components/tabs/__tests__/__snapshots__/tabs.test.tsx.snap, packages/elements/src/components/tabs/tabs.stories.mdx, packages/elements/src/components/tabs/tabs.tsx, packages/elements/src/components/toggle/toggle.stories.mdx, packages/elements/src/storybook/changelog.stories.mdx
=> feat: #6083 tweaks to toggle and tabs in Elements

packages/developer-portal/src/components/pages/login/select-role.tsx
=> feat: #6112 new reg form

packages/elements-legacy/package.json, packages/elements/src/storybook/changelog.stories.mdx
=> chore: #6129 release elements legacy

packages/utils-common/src/reapit-data/__tests__/get-fetcher.test.ts, packages/utils-common/src/reapit-data/__tests__/utils.test.ts, packages/utils-common/src/reapit-data/get-fetcher.ts, packages/utils-common/src/reapit-data/utils.ts, packages/utils-react/src/use-reapit-data/use-reapit-update.ts
=> fix: #6114 handle reapit errors better

packages/app-builder-backend/src/get-schema.ts
=> fix: custom entities support custom fields

packages/admin-portal/src/components/pages/usage/index.tsx
=> fix: #6124 app id filter key incorrect

packages/admin-portal/src/components/ui/__tests__/menu.tsx, packages/admin-portal/src/utils/get-access.ts
=> fix: #6124 makes route visible to non admins

packages/app-builder-backend/README.md
=> chore: app builder release

packages/app-builder-backend/src/get-schema.ts
=> fix: special chars in app builder field names

packages/app-builder-backend/src/get-schema.ts, packages/app-builder-backend/src/platform/index.ts, packages/app-builder/src/components/hooks/use-introspection/parse-introspection.ts, packages/app-builder/src/components/ui/user/ejectable/form.tsx, packages/app-builder/src/components/ui/user/ejectable/table.tsx, packages/app-builder/src/components/ui/user/form.tsx, packages/app-builder/src/components/ui/user/table.tsx
=> fix: a bunch of app builder issues

packages/developer-portal/src/components/pages/settings/settings-profile-tab/toggle-customer-data-form.tsx
=> fix: fixes runtime error on profile page

packages/marketplace-management/src/components/ui/offices/__tests__/office-group-edit-form.test.tsx, packages/marketplace-management/src/components/ui/offices/__tests__/offices-groups-tab.test.tsx, packages/marketplace-management/src/components/ui/offices/office-group-create.tsx, packages/marketplace-management/src/components/ui/offices/office-group-edit-form.tsx, packages/marketplace-management/src/components/ui/offices/offices-groups-tab.tsx, packages/marketplace-management/src/utils/fetcher.ts
=> feat: #6228 fixes mm app offices bug

packages/marketplace-management/src/components/ui/apps/__tests__/app-toggle-visibility-section.test.tsx, packages/marketplace-management/src/components/ui/apps/app-toggle-visibility-section.tsx, packages/marketplace-management/src/components/ui/offices/office-group-create.tsx, packages/marketplace-management/src/components/ui/offices/offices-groups-tab.tsx, packages/marketplace-management/src/components/ui/users/edit-user-group.tsx, packages/marketplace-management/src/components/ui/users/user-groups-tab.tsx, packages/marketplace-management/src/components/ui/users/users-tab.tsx
=> fix: #6228 increase latency fix

packages/marketplace-management/src/components/ui/offices/__tests__/office-group-create.test.tsx, packages/marketplace-management/src/components/ui/offices/office-group-create.tsx
=> feat: #6228 mm app groups fix

packages/admin-portal/src/components/pages/devs-management/devs-management.tsx
=> feat: #6247 makes button visible

packages/cli/package.json, packages/cli/src/commands/pipeline/create.ts, packages/deployment-service/src/dto/pipeline-dto.ts, packages/developer-portal/src/components/pages/v8/pipeline/create-pipeline.tsx, packages/foundations-ts-definitions/deployment-schema/index.ts
=> feat: add branch to cli and dev

packages/admin-portal/src/components/pages/devs-management/set-status-modal/__tests__/__snapshots__/status-modal.test.tsx.snap, packages/admin-portal/src/components/pages/devs-management/set-status-modal/status-modal.tsx
=> fix: hotfix on admin statuses

packages/developer-portal/src/components/pages/webhooks/__tests__/__snapshots__/webhooks-manage.test.tsx.snap, packages/developer-portal/src/components/pages/webhooks/__tests__/__snapshots__/webhooks.test.tsx.snap, packages/developer-portal/src/components/pages/webhooks/webhooks-manage.tsx, packages/developer-portal/src/sagas/webhooks-subscriptions/__tests__/webhook-edit-modal.test.ts, packages/developer-portal/src/sagas/webhooks-subscriptions/webhooks-edit-modal.ts
=> fix: #6263 webhooks pagination patch

packages/cli/src/commands/pipeline/deploy-local.ts, packages/cli/src/commands/pipeline/deploy.ts
=> feat: added log for location of deployment on deploy

packages/ts-bundler/src/get-workspace-root.ts, packages/ts-bundler/src/ts-bundler.ts
=> fix: ts-bundler packages dir

packages/marketplace-management/package.json, packages/marketplace-management/src/components/ui/offices/__tests__/__snapshots__/office-group-edit-form.test.tsx.snap, packages/marketplace-management/src/components/ui/offices/__tests__/__snapshots__/offices-groups-tab.test.tsx.snap, packages/marketplace-management/src/components/ui/offices/__tests__/office-group-edit-form.test.tsx, packages/marketplace-management/src/components/ui/offices/office-group-edit-form.tsx, packages/marketplace-management/src/components/ui/offices/offices-groups-tab.tsx, packages/marketplace-management/tsconfig.json, packages/utils-common/src/reapit-data/actions/api-constants.ts, packages/utils-common/src/reapit-data/actions/update.ts, yarn.lock
=> feat: #6278 delete office groups

packages/deployment-service/cdk/lib/cdk-stack.ts, packages/deployment-service/cdk/lib/create-policies.ts, packages/deployment-service/src/functions/pipeline/codebuild-executor.ts, packages/deployment-service/src/functions/pipeline/pipeline-delete.ts, packages/deployment-service/src/functions/pipeline/pipeline-runner-create.ts, packages/deployment-service/src/functions/pipeline/pipeline-tear-down.ts, packages/developer-portal/src/components/pages/apps/edit/__tests__/__snapshots__/deployment-info.test.tsx.snap, packages/developer-portal/src/components/pages/apps/edit/__tests__/__snapshots__/pipeline-info.test.tsx.snap, packages/developer-portal/src/components/pages/apps/edit/__tests__/deployment-info.test.tsx, packages/developer-portal/src/components/pages/apps/edit/create-pipeline.tsx, packages/developer-portal/src/components/pages/apps/edit/deployment-info.tsx, packages/developer-portal/src/components/pages/apps/edit/index.tsx, packages/developer-portal/src/components/pages/apps/edit/pipeline-info-wrapper.tsx, packages/developer-portal/src/components/pages/apps/edit/pipeline-info.tsx, packages/utils-common/src/reapit-data/actions/update.ts
=> feat: #6154 delete pipeline

packages/admin-portal/src/components/pages/usage/__tests__/__snapshots__/filter-form.test.tsx.snap, packages/admin-portal/src/components/pages/usage/filter-form.tsx
=> fix: #6312 updates admin usage query

.github/workflows/release-prod.yml
=> fix: release prod workflow broken

packages/cli/src/commands/pipeline/delete.ts, packages/cli/src/commands/pipeline/index.ts, packages/deployment-service/src/functions/pipeline/pipeline-tear-down.ts
=> feat: #6150 delete pipeline cli

packages/cli/src/commands/pipeline/deploy-local.ts, packages/cli/src/commands/release/list.ts, packages/cli/src/commands/release/version.ts, packages/deployment-service/src/functions/release/deploy-release.ts
=> feat: #6156 semver unique

packages/graphql-server/src/resolvers/properties/properties.d.ts, packages/graphql-server/src/resolvers/properties/types.graphql, packages/graphql-server/src/schema.graphql
=> feat: add officeId to GetProperties query

packages/cli/src/commands/pipeline/create.ts
=> feat: cli support other git providers & https

packages/graphql-server/package.json
=> chore: bump graphql-server version

packages/developer-portal/src/components/pages/swagger/swagger.tsx
=> feat: #5682 set default swagger

packages/developer-portal/src/components/pages/webhooks/webhooks-manage.tsx
=> feat: #6244 add client id to webhooks manage

packages/developer-portal/src/components/ui/developer-edition-modal/developer-edition-content.tsx, packages/developer-portal/src/components/ui/developer-edition-modal/developer-edition-modal.tsx
=> feat: #6323 prevent desktop subscriptions

packages/deployment-service/cdk/lib/cdk-stack.ts
=> fix: corrected migration path name

packages/developer-portal/src/components/pages/analytics/cost-explorer/cost-explorer-component/cost-explorer.tsx, packages/developer-portal/src/components/pages/analytics/cost-explorer/cost-explorer-component/cost-filter-form.tsx, packages/developer-portal/src/components/ui/developer-edition-modal/developer-edition-modal.tsx, packages/developer-portal/src/services/billing.ts
fixes: #6031 
fixes: #5432 
fixes: #6323
=> feat: #6031 #5432 add app filter cost explorer

packages/deployment-service/migrations/1645444063726-bitBucket.ts
=> fix: remove nsleft and nsright from rollback migration

packages/admin-portal/jest.config.js, packages/admin-portal/src/components/pages/devs-management/set-status-modal/form-schema.ts, packages/admin-portal/src/components/pages/statistics/statistics.tsx, packages/admin-portal/src/components/pages/usage/index.tsx, packages/admin-portal/src/utils/statistics.ts
=> feat: #6210 #6325 admin usage download, validations fix

packages/developer-portal/src/components/pages/apps/detail/__styles__/index.ts, packages/developer-portal/src/components/pages/apps/detail/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/pages/apps/detail/index.tsx, packages/developer-portal/src/components/pages/apps/edit/__tests__/__snapshots__/ac-integration-tab.test.tsx.snap, packages/developer-portal/src/components/pages/apps/edit/__tests__/__snapshots__/app-edit-form.test.tsx.snap, packages/developer-portal/src/components/pages/apps/edit/__tests__/__snapshots__/app-listing-tab.test.tsx.snap, packages/developer-portal/src/components/pages/apps/edit/__tests__/__snapshots__/authentication-tab.test.tsx.snap, packages/developer-portal/src/components/pages/apps/edit/__tests__/__snapshots__/edit-page-tabs.test.tsx.snap, packages/developer-portal/src/components/pages/apps/edit/__tests__/__snapshots__/permissions-tab.test.tsx.snap, packages/developer-portal/src/components/pages/apps/edit/ac-integration-tab.tsx, packages/developer-portal/src/components/pages/apps/edit/app-listing-tab.tsx, packages/developer-portal/src/components/pages/apps/edit/authentication-tab.tsx, packages/developer-portal/src/components/pages/apps/edit/permissions-tab.tsx, packages/developer-portal/src/components/pages/apps/new/__tests__/__snapshots__/app-options-content.test.tsx.snap, packages/developer-portal/src/components/pages/apps/new/__tests__/__snapshots__/helper-content.test.tsx.snap, packages/developer-portal/src/components/pages/apps/new/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/pages/apps/new/__tests__/app-options-content.test.tsx, packages/developer-portal/src/components/pages/apps/new/app-options-content.tsx, packages/developer-portal/src/components/pages/apps/new/helper-content.tsx, packages/developer-portal/src/components/pages/apps/new/permissions-options-content.tsx, packages/developer-portal/src/components/pages/apps/page/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/utils/navigation.ts
=> feat: #6437 apps flow text changes

packages/api-key-service/serverless.yml
=> fix: corrected serverless config for api-key-service

packages/deployment-service/migrations/index.ts
=> fix: added missing migration

packages/deployment-service/src/functions/pipeline/pipeline-setup.ts
=> fix: added condition for hard coded url

packages/cli/src/commands/pipeline/create.ts, packages/deployment-service/src/functions/pipeline/pipeline-create.ts, packages/deployment-service/src/functions/pipeline/pipeline-setup.ts
=> refactor: change pusher channel name

packages/developer-portal/src/components/pages/apps/edit/__tests__/__snapshots__/app-edit-form.test.tsx.snap, packages/developer-portal/src/components/pages/apps/edit/__tests__/__snapshots__/edit-page-tabs.test.tsx.snap, packages/developer-portal/src/components/pages/apps/edit/__tests__/__snapshots__/permissions-tab.test.tsx.snap, packages/developer-portal/src/components/pages/apps/edit/__tests__/app-edit-form.test.tsx, packages/developer-portal/src/components/pages/apps/edit/app-edit-form.tsx, packages/developer-portal/src/components/pages/apps/edit/form-schema/validation-schema.ts, packages/developer-portal/src/components/pages/apps/edit/permissions-tab.tsx, packages/developer-portal/src/components/pages/apps/new/__tests__/__snapshots__/helper-content.test.tsx.snap, packages/developer-portal/src/components/pages/apps/new/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/pages/apps/new/helper-content.tsx, packages/developer-portal/src/components/pages/apps/page/helper.tsx, packages/developer-portal/src/components/pages/apps/welcome/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/pages/apps/welcome/index.tsx
=> feat: #6456 final prod tweaks

packages/utils-react/src/use-reapit-data/use-reapit-update.ts
=> fix: location header patch

packages/developer-portal/src/components/pages/apps/page/__tests__/__snapshots__/submit-review-modal.test.tsx.snap, packages/developer-portal/src/components/pages/apps/page/__tests__/helper.test.tsx, packages/developer-portal/src/components/pages/apps/page/__tests__/submit-review-modal.test.tsx, packages/developer-portal/src/components/pages/apps/page/helper.tsx, packages/developer-portal/src/components/pages/apps/page/submit-review-modal.tsx, packages/utils-common/src/reapit-data/actions/get.ts
=> feat: #6470 is listed modal

packages/marketplace-management/src/components/ui/apps/app-toggle-visibility-section.tsx, packages/marketplace-management/src/components/ui/offices/office-group-create.tsx, packages/marketplace-management/src/components/ui/offices/offices-groups-tab.tsx, packages/marketplace-management/src/components/ui/users/edit-user-group.tsx, packages/marketplace-management/src/components/ui/users/user-groups-tab.tsx, packages/marketplace-management/src/components/ui/users/users-tab.tsx
=> fix: #6500 re-add timeouts

packages/cra-template-foundations/template.json
=> fix: #6568 cra release with v18 react

packages/marketplace/src/components/pages/apps/coming-soon.tsx
=> chore: #6578 removing coming soons

packages/developer-portal/src/components/apps/pipeline/edit-pipeline.tsx
=> fix: corrected build status when editing pipeline

packages/developer-portal/src/components/apps/pipeline/create-pipeline.tsx
=> fix: added pipelineId to uriParams for create pipeline

packages/deployment-service/src/functions/pipeline/pipeline-runner-create.ts
=> fix: reversed condition to prevent deploys in pre provision

.github/workflows/release-dev.yml, .github/workflows/release-prod.yml, packages/deployment-service/cdk/lib/cdk-stack.ts, packages/deployment-service/cdk/lib/create-S3-bucket.ts, packages/deployment-service/src/functions/pipeline/pipeline-setup.ts, packages/developer-portal/src/utils/__tests__/pipeline-helpers.test.ts, packages/developer-portal/src/utils/pipeline-helpers.ts, packages/ts-scripts/src/cdk/components/codebuild-project.ts
=> feat: split dev prod resources

packages/deployment-service/cdk/lib/cdk-stack.ts
=> fix: added env to separate usercode formations

packages/deployment-service/src/functions/codebuild/codebuild-executor.ts
=> feat: upgraded hardcoded value for codebuild of node version

packages/developer-portal/src/components/api/__tests__/__snapshots__/api-page.test.tsx.snap, packages/developer-portal/src/components/api/__tests__/api-page.test.tsx, packages/developer-portal/src/components/api/__tests__/index.test.tsx, packages/developer-portal/src/components/api/api-page.tsx, packages/developer-portal/src/components/apps/new/__tests__/__snapshots__/helper-content.test.tsx.snap, packages/developer-portal/src/components/apps/new/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/new/__tests__/helper-content.test.tsx, packages/developer-portal/src/components/apps/new/helper-content.tsx, packages/developer-portal/src/components/settings/members/member-update-controls.tsx, packages/developer-portal/src/components/settings/page/controls.tsx, packages/developer-portal/src/components/settings/profile/__tests__/index.test.tsx, packages/developer-portal/src/components/settings/profile/__tests__/profile-form.test.tsx, packages/developer-portal/src/components/settings/profile/profile-form.tsx, packages/developer-portal/src/components/webhooks/__tests__/__snapshots__/webhooks-controls.test.tsx.snap, packages/developer-portal/src/components/webhooks/webhooks-controls.tsx, packages/developer-portal/src/core/index.tsx, packages/developer-portal/src/types/global.d.ts, packages/foundations-ts-definitions/package.json, packages/foundations-ts-definitions/types/marketplace-schema.ts, packages/utils-react/src/use-reapit-data/use-reapit-get.ts
=> feat: #6706 #6303 adds videos and put on members

packages/developer-portal/src/components/apps/pipeline/pipeline-configure.tsx, packages/utils-common/src/reapit-data/actions/update.ts
=> fix: pipeline patch

packages/deployment-service/cdk/lib/cdk-stack.ts
=> fix: corrected authid for cdk

packages/deployment-service/src/functions/codebuild/codebuild-executor.ts
=> fix: duplicate build

packages/cra-template-foundations/package.json, packages/cra-template-foundations/template/src/index.tsx, packages/developer-portal/src/core/index.tsx, packages/developer-portal/src/scripts/chat-bot.js
=> fix: #6750 cra fix, enable zendesk

packages/deployment-service/src/functions/github-webhook.ts
=> fix: ref string condition

packages/cli/package.json, packages/cli/src/abstract.command.ts, packages/cli/src/commands/pipeline/create.ts, packages/cli/src/commands/pipeline/delete.ts, packages/cli/src/commands/pipeline/edit.ts, packages/cli/src/commands/pipeline/link.ts, packages/cli/src/commands/release/list.ts, packages/cli/src/commands/release/repo.ts, packages/cli/src/commands/release/version.ts, packages/cli/src/commands/release/zip.ts
=> feat: #6743 deploy cli

packages/cli/package.json
=> fix: corrected access type to public

packages/developer-portal/src/components/apps/detail/__styles__/index.ts, packages/developer-portal/src/components/apps/detail/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/detail/index.tsx, packages/developer-portal/src/utils/navigation.ts
=> feat: #6744 code examples

packages/app-builder-backend/src/entities/contact.ts, packages/app-builder-backend/src/resolvers/contact-resolver.ts
=> feat: update contact with shared entity fields

packages/geo-diary-marketing/src/components/sign-in-button.svelte, packages/geo-diary-marketing/svelte.config.js
=> fix: #6794 fixes iframe crash

packages/marketplace-management/src/components/ui/offices/__tests__/__snapshots__/offices-groups-tab.test.tsx.snap, packages/marketplace-management/src/components/ui/offices/offices-groups-tab.tsx
=> feat: #6791 display customer id mm app

packages/developer-portal/src/components/apps/new/config.tsx
=> feat: #6808 update website default permissions

.github/workflows/codeql-analysis.yml
=> feat: #6769 codeql runs on cron

packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-deployments-table.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-tasks-list.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/pipeline-tasks-list.tsx
=> fix: corrected logs expiry date

packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-deployments-table.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-tasks-list.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/pipeline-tasks-list.tsx
=> fix: corrected condition for button text

packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-deployments-table.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-info.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-page.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-tasks-list.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/pipeline-info.tsx, packages/developer-portal/src/components/apps/pipeline/pipeline-tasks-list.tsx
=> feat: design tweeks on pipelines

packages/app-builder/src/components/pages/__tests__/__snapshots__/home.test.tsx.snap, packages/app-builder/src/components/ui/components.tsx, packages/app-builder/src/components/ui/header/PageSelector.tsx, packages/app-builder/src/components/ui/header/__tests__/__snapshots__/header.test.tsx.snap, packages/app-builder/src/components/ui/header/__tests__/__snapshots__/page-selector.test.tsx.snap, packages/app-builder/src/components/ui/viewport/__tests__/__snapshots__/viewport.test.tsx.snap
=> feat: add SelectOrInput component for renaming pages

packages/developer-portal/src/core/__tests__/__snapshots__/use-global-state.test.tsx.snap, packages/developer-portal/src/core/__tests__/use-global-state.test.tsx, packages/developer-portal/src/core/use-global-state.tsx
=> fix: #6890 login permissions error

packages/app-builder-backend/cdk-stack.ts
=> fix: add app-id header to cors config

packages/developer-portal/src/components/apps/pipeline/__tests__/pipeline-controls.test.tsx, packages/developer-portal/src/components/apps/pipeline/pipeline-controls.tsx, packages/developer-portal/src/components/apps/utils/handle-default-form-values.ts
=> fix: #6918 pipeline update error

packages/app-builder-backend/src/resolvers/appointment-resolver.ts, packages/app-builder/src/components/hooks/use-introspection/index.ts, packages/app-builder/src/components/hooks/use-introspection/query-generators.ts
=> fix: appointment entity

packages/developer-portal/src/components/api/__tests__/__snapshots__/api-page.test.tsx.snap, packages/developer-portal/src/components/webhooks/__tests__/__snapshots__/webhooks-controls.test.tsx.snap, packages/developer-portal/src/components/webhooks/state/defaults.ts, packages/developer-portal/src/components/webhooks/webhooks-controls.tsx, packages/developer-portal/src/components/webhooks/webhooks-logs.tsx
=> feat: #6846 adjust webhook log filters

packages/developer-portal/src/components/analytics/state/use-analytics-state.tsx, packages/developer-portal/src/components/apps/list/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/list/index.tsx, packages/developer-portal/src/components/apps/state/__mocks__/use-app-state.tsx, packages/developer-portal/src/components/apps/state/use-app-state.tsx, packages/developer-portal/src/components/webhooks/state/use-webhooks-state.tsx
=> feat: #6921 paginate apps

packages/elements/src/storybook/changelog.stories.mdx, packages/elements/src/styles/globals.ts
=> feat: #6940 adds base style to hyperlinks

packages/cra-template-foundations/package.json, packages/cra-template-foundations/template.json
=> fix: #6961 cra fix for react 18.1

packages/cra-template-foundations/template/src/components/ui/examples/form-example.tsx, packages/elements/src/storybook/changelog.stories.mdx
=> fix: #6979 fix typo

packages/data-warehouse/src/components/hocs/__tests__/__snapshots__/error-boundary.test.tsx.snap, packages/developer-portal/src/components/api/__tests__/__snapshots__/api-page.test.tsx.snap, packages/developer-portal/src/components/apps/detail/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/edit/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/installations/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-page.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-tasks-list.test.tsx.snap, packages/developer-portal/src/components/desktop/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/register/terms-and-conditions-modal/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/settings/profile/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/settings/profile/__tests__/__snapshots__/profile-form.test.tsx.snap, packages/developer-portal/src/components/swagger/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/webhooks/__tests__/__snapshots__/webhooks-about.test.tsx.snap, packages/developer-portal/src/components/webhooks/__tests__/__snapshots__/webhooks-logs.test.tsx.snap, packages/developer-portal/src/components/webhooks/__tests__/__snapshots__/webhooks-manage.test.tsx.snap, packages/developer-portal/src/core/__tests__/__snapshots__/error-boundary.test.tsx.snap, packages/developer-portal/src/core/__tests__/__snapshots__/router.test.tsx.snap, packages/elements/src/components/persistant-notification/__styles__/index.ts, packages/elements/src/components/persistant-notification/__tests__/__snapshots__/persistent-notification.test.tsx.snap, packages/elements/src/components/persistant-notification/persistent-notification.tsx, packages/elements/src/components/persistent-notification/__styles__/index.ts, packages/elements/src/components/persistent-notification/__tests__/__snapshots__/persistent-notification.test.tsx.snap, packages/elements/src/components/persistent-notification/persistent-notification.tsx, packages/elements/src/storybook/changelog.stories.mdx, packages/marketplace/src/components/hocs/__tests__/__snapshots__/error-boundary.tsx.snap, packages/marketplace/src/components/pages/apps/__tests__/__snapshots__/apps.test.tsx.snap
=> feat: #7001 update persistent notification classes elements

packages/developer-portal/src/components/apps/detail/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/detail/index.tsx, packages/developer-portal/src/components/apps/page/__tests__/__snapshots__/index.test.tsx.snap
=> fix: #7005 fix uri display

packages/deployment-service/src/events/pusher-webhook-controller.ts
=> fix: added bad request excep for no socket id on pusher auth

packages/deployment-service/cdk/cdk.ts, packages/deployment-service/cdk/lib/cdk-stack.ts, packages/ts-scripts/src/cdk/components/stack-event-handler.ts
=> fix: custom resource hopefully fires on properties change

packages/app-builder/src/components/pages/__tests__/__snapshots__/home.test.tsx.snap, packages/app-builder/src/components/ui/viewport/__tests__/__snapshots__/viewport.test.tsx.snap, packages/app-builder/src/components/ui/viewport/index.tsx
=> feat: app builder resizing

packages/admin-portal/src/components/ui/approval-modal/__tests__/approval-modal.test.tsx, packages/admin-portal/src/components/ui/approval-modal/approval-modal.tsx, packages/developer-portal/src/components/apps/consents/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/consents/__tests__/index.test.tsx, packages/developer-portal/src/components/apps/consents/index.tsx, packages/developer-portal/src/components/apps/edit/__tests__/app-edit-form.test.tsx, packages/developer-portal/src/components/apps/edit/app-edit-form.tsx, packages/developer-portal/src/components/apps/page/index.tsx, packages/developer-portal/src/components/apps/state/__mocks__/use-app-state.tsx, packages/developer-portal/src/components/apps/state/use-app-state.tsx, packages/developer-portal/src/components/apps/utils/__tests__/consents.test.ts, packages/developer-portal/src/components/apps/utils/consents.ts
=> feat: #4669 admin consents management

packages/deployment-service/src/bitbucket/bitbucket-provider.ts, packages/deployment-service/src/bitbucket/bitbucket-webhook-controller.ts, packages/deployment-service/src/events/pusher-provider.ts, packages/deployment-service/src/github/github-webhook-controller.ts, packages/deployment-service/src/pipeline/pipeline-provider.ts
=> feat: additional pipeline event updates

packages/admin-portal/src/components/ui/app-revision-comparison/app-revision-comparison.tsx, packages/developer-portal/src/components/apps/edit/app-edit-form.tsx, packages/developer-portal/src/components/apps/page/__tests__/__snapshots__/helper.test.tsx.snap, packages/developer-portal/src/components/apps/page/helper.tsx, packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-controls.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/__tests__/pipeline-configure.test.tsx, packages/developer-portal/src/components/apps/pipeline/pipeline-configure.tsx, packages/developer-portal/src/components/apps/pipeline/pipeline-controls.tsx, packages/developer-portal/src/components/apps/pipeline/pipeline-environment.tsx, packages/developer-portal/src/utils/navigation.ts
=> feat: #7078 update consents flow

packages/deployment-service/src/github/github-webhook-controller.ts
=> feat: refactored to handle multiple repositories

packages/cli/src/commands/pipeline/__tests__/create.test.ts, packages/cli/src/commands/pipeline/__tests__/edit.test.ts, packages/cli/src/commands/release/version.ts
=> fix: resolved version from id instead of build version

packages/deployment-service/src/app-event/app-event-workflow.ts, packages/deployment-service/src/pipeline-runner/pipeline-runner-controller.ts
=> fix: corrected pipeline status updates

packages/cli/package.json, packages/cli/src/commands/check-version.ts, packages/cli/src/index.ts
=> refactor: removed comment block for update prompt

packages/cli/README.md, packages/cli/package.json
=> docs: corrected image paths and added param commands

packages/deployment-service/src/entities/pipeline.entity.ts
=> fix: added bitbucketId column for exposing to frontend

packages/deployment-service/src/bitbucket/__test__/bitbucket-webhook-controller.test.ts, packages/deployment-service/src/bitbucket/bitbucket-webhook-controller.ts
=> feat: added bibucket webhook tests

packages/deployment-service/src/github/__test__/github-webhook-controller.test.ts
=> feat: added github webhook tests

packages/ts-scripts/src/cdk/bin/rpt-cdk.ts
=> fix: rpt-cdk remove excess args

packages/ts-bundler/src/workspace-deps.ts, packages/ts-bundler/src/yarn-lock.ts
=> fix: ts-bundler workspace non-namespaced deps

packages/app-builder/.sentryclirc
=> fix: add .sentryclirc

packages/ts-scripts/src/cdk/bin/rpt-cdk.ts
=> fix: rpt-cdk scriptName

.github/workflows/release-prod.yml
=> fix: update release-prod.yml

packages/app-builder-backend/src/resolvers/app-resolver.ts
=> fix: remove trailing slash from redirect uris when creating app

packages/developer-portal/src/components/analytics/calculator/__tests__/__snapshots__/results-table.test.tsx.snap, packages/developer-portal/src/components/analytics/costs/__tests__/__snapshots__/download-resources-table.test.tsx.snap, packages/developer-portal/src/components/analytics/costs/__tests__/__snapshots__/services-table.test.tsx.snap, packages/developer-portal/src/components/analytics/costs/__tests__/__snapshots__/usage-table.test.tsx.snap, packages/developer-portal/src/components/apps/consents/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/installations/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-api-keys.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-deployments-table.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-info.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-page.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-tasks-list.test.tsx.snap, packages/developer-portal/src/components/iaas/__tests__/__snapshots__/pipeline-row.test.tsx.snap, packages/developer-portal/src/components/register/terms-and-conditions-modal/__tests__/__snapshots__/consumption-cost-methodology-table.test.tsx.snap, packages/developer-portal/src/components/register/terms-and-conditions-modal/__tests__/__snapshots__/consumption-cost-types-table.test.tsx.snap, packages/developer-portal/src/components/register/terms-and-conditions-modal/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/register/terms-and-conditions-modal/__tests__/__snapshots__/schedule-two.test.tsx.snap, packages/developer-portal/src/components/settings/members/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/settings/subscriptions/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/webhooks/__tests__/__snapshots__/webhooks-logs.test.tsx.snap, packages/developer-portal/src/components/webhooks/__tests__/__snapshots__/webhooks-manage.test.tsx.snap, packages/elements/src/components/table/__styles__/index.ts, packages/elements/src/components/table/table.stories.mdx, packages/elements/src/storybook/changelog.stories.mdx
=> feat: #7133 adds elements table modifier

packages/developer-portal/src/components/desktop/__tests__/__snapshots__/developer-edition-download.test.tsx.snap, packages/developer-portal/src/components/desktop/__tests__/developer-edition-download.test.tsx, packages/developer-portal/src/components/desktop/developer-edition-download.tsx, packages/developer-portal/src/constants/routes.ts, packages/developer-portal/src/core/router.tsx
=> fix: #7192 adds download dev edition route

packages/app-marketplace-admin/cdk-stack.ts
=> fix: cdk env

.github/workflows/release-prod.yml
=> fix: added app-marketplace-admin to condition to remove stage

packages/app-marketplace-admin/src/components/apps-market-manager/__tests__/__snapshots__/app-browse-manage-table.test.tsx.snap, packages/app-marketplace-admin/src/components/apps-market-manager/__tests__/__snapshots__/app-browse-upsert-modal.test.tsx.snap, packages/app-marketplace-admin/src/components/apps-market-manager/__tests__/__snapshots__/app-browse-upsert.test.tsx.snap, packages/app-marketplace-admin/src/components/apps-market-manager/__tests__/app-browse-upsert-modal.test.tsx, packages/app-marketplace-admin/src/components/apps-market-manager/app-browse-manage-table.tsx, packages/app-marketplace-admin/src/components/apps-market-manager/app-browse-upsert-modal.tsx, packages/app-marketplace-admin/src/components/apps-market-manager/app-browse-upsert.tsx, packages/app-marketplace-admin/src/components/apps-market-manager/app-browse.styles.ts, packages/app-marketplace-admin/src/utils/navigation.ts, packages/developer-portal/src/components/apps/page/submit-review-modal.tsx, packages/developer-portal/src/components/settings/profile/profile-form.tsx, packages/ts-scripts/src/cdk/components/site.ts, packages/utils-react/src/use-reapit-data/use-reapit-update.ts
=> feat: #7305 app marketplace admin UI improvements

packages/payments-service/src/controllers/__tests__/get-payment.test.ts, packages/payments-service/src/controllers/get-payment.ts
=> fix: #7313 fix payment service error

packages/payments-service/src/controllers/__tests__/get-payment.test.ts, packages/payments-service/src/controllers/get-payment.ts
=> fix: #7313 further fix to payments service headers

packages/payments-service/src/controllers/get-payment.ts
=> fix: #7313 include mailer in whitelist

packages/app-market/src/components/apps-browse/__tests__/__snapshots__/app-search-filters-bar.test.tsx.snap, packages/app-market/src/components/apps-browse/app-search-filters-bar.tsx, packages/app-market/src/components/apps-browse/apps-browse.tsx
=> fix: #7387 fixes mobile filters bug

packages/app-market/src/core/index.tsx, packages/app-market/src/types/global.d.ts
=> feat: #7389 updates configs for prod release

packages/app-market/src/components/apps-browse/apps-browse.tsx, packages/app-market/src/core/config.ts, packages/ts-scripts/src/webpack/webpack.config.dev.js
=> feat: #7385 ordering app market

packages/marketplace-management/src/components/ui/offices/office-group-create.tsx, packages/marketplace-management/src/components/ui/offices/office-group-edit-form.tsx, packages/marketplace-management/src/components/ui/offices/offices-groups-tab.tsx
=> fix: #7468 fix offices pagination

packages/developer-portal/src/components/webhooks/__tests__/__snapshots__/webhooks-controls.test.tsx.snap, packages/developer-portal/src/components/webhooks/state/defaults.ts, packages/developer-portal/src/components/webhooks/state/use-webhooks-state.tsx, packages/developer-portal/src/components/webhooks/webhook-ping-form.tsx, packages/developer-portal/src/components/webhooks/webhooks-controls.tsx, packages/developer-portal/src/components/webhooks/webhooks-logs.tsx
=> feat: #7299 webhook logs filtering

packages/app-marketplace-admin/src/components/apps-market-manager/__tests__/__snapshots__/app-browse-manage-table.test.tsx.snap, packages/app-marketplace-admin/src/components/apps-market-manager/__tests__/__snapshots__/app-browse-upsert-modal.test.tsx.snap, packages/app-marketplace-admin/src/components/apps-market-manager/__tests__/__snapshots__/app-browse-upsert.test.tsx.snap, packages/app-marketplace-admin/src/components/apps-market-manager/__tests__/__snapshots__/subs-helper-text.test.tsx.snap, packages/app-marketplace-admin/src/components/apps-market-manager/__tests__/subs-helper-text.test.tsx, packages/app-marketplace-admin/src/components/apps-market-manager/app-browse-manage-table.tsx, packages/app-marketplace-admin/src/components/apps-market-manager/app-browse-upsert-modal.tsx, packages/app-marketplace-admin/src/components/apps-market-manager/app-browse-upsert.tsx, packages/app-marketplace-admin/src/components/apps-market-manager/app-browse.styles.ts, packages/app-marketplace-admin/src/components/apps-market-manager/subs-helper-text.tsx
=> feat: #7405 cms helper text

packages/app-market/src/components/apps-browse/__styles__/featured-hero-apps.ts, packages/app-market/src/components/apps-detail/__styles__/index.ts, packages/app-market/src/components/apps-detail/__tests__/__snapshots__/apps-detail-header.test.tsx.snap, packages/app-market/src/components/apps-detail/apps-detail-header.tsx, packages/app-market/src/components/apps-detail/apps-detail.tsx
=> feat: #7502 app market qa

packages/app-market/src/components/apps-browse/__styles__/featured-hero-apps.ts
=> feat: #7502 app market tweaks

packages/app-market/src/core/index.tsx
=> feat: #7514 turn on mixpanel in prod

packages/app-market/src/components/apps-browse/__tests__/__snapshots__/app-search-filters-bar.test.tsx.snap, packages/app-market/src/components/apps-browse/__tests__/__snapshots__/apps-browse.test.tsx.snap, packages/app-market/src/components/apps-browse/__tests__/app-filters-collection.test.tsx, packages/app-market/src/components/apps-browse/__tests__/app-search-filters-bar.test.tsx, packages/app-market/src/components/apps-browse/app-filters-collection.tsx, packages/app-market/src/components/apps-browse/app-search-filters-bar.tsx, packages/app-market/src/components/apps-detail/app-install-modal.tsx, packages/app-market/src/core/__mocks__/use-apps-browse-state.tsx, packages/app-market/src/core/use-apps-browse-state.tsx, packages/app-market/src/tests/__stubs__/categories.ts, packages/app-marketplace-admin/src/components/apps-market-manager/app-browse-upsert-modal.tsx
=> feat: #7514 fixed a few bugs in app market

packages/app-market/src/components/apps-browse/__styles__/hero-apps.ts, packages/app-market/src/components/settings/__tests__/__snapshots__/settings-installed.test.tsx.snap, packages/app-market/src/core/__tests__/analytics.test.tsx, packages/app-market/src/core/analytics.ts, packages/developer-portal/src/components/apps/installations/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/pipeline/__tests__/__snapshots__/pipeline-deployments-table.test.tsx.snap, packages/developer-portal/src/components/settings/members/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/settings/subscriptions/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/webhooks/__tests__/__snapshots__/webhooks-manage.test.tsx.snap, packages/elements/src/components/pagination/__styles__/index.ts, packages/elements/src/components/pagination/__tests__/__snapshots__/pagination.test.tsx.snap, packages/elements/src/components/pagination/__tests__/pagination.test.tsx, packages/elements/src/components/pagination/pagination.stories.mdx, packages/elements/src/components/pagination/pagination.tsx, packages/elements/src/storybook/changelog.stories.mdx, packages/marketplace-management/src/components/pages/__tests__/__snapshots__/marketplace.test.tsx.snap, packages/marketplace-management/src/components/ui/offices/__tests__/__snapshots__/offices-groups-tab.test.tsx.snap, packages/marketplace-management/src/components/ui/users/__tests_/__snapshots__/user-groups-tab.test.tsx.snap, packages/marketplace-management/src/components/ui/users/__tests_/__snapshots__/users-tab.test.tsx.snap, packages/payments-client/src/components/pages/payments/__tests__/__snapshots__/index.test.tsx.snap
=> feat: #7464 adds pagination input to Elements

packages/developer-portal/src/components/webhooks/__tests__/webhooks-new.test.tsx, packages/developer-portal/src/components/webhooks/webhooks-new.tsx
=> fix: corrected loading value for create button disabling

packages/developer-portal/src/components/apps/new/index.tsx
=> chore: remove console.log

packages/app-market/src/core/index.tsx
=> fix: #7608 always initialize mixpanel

README.md
Updated readme to remove reference to obsolete frontend board
=> chore: #7696 Update README.md

packages/marketplace-management/src/components/hocs/__tests__/__snapshots__/error-boundary.test.tsx.snap, packages/marketplace-management/src/components/hocs/error-boundary.tsx, packages/marketplace-management/src/components/pages/__tests__/__snapshots__/access-denied.test.tsx.snap, packages/marketplace-management/src/components/pages/__tests__/__snapshots__/marketplace-app.test.tsx.snap, packages/marketplace-management/src/components/pages/__tests__/__snapshots__/marketplace.test.tsx.snap, packages/marketplace-management/src/components/pages/access-denied.tsx, packages/marketplace-management/src/components/pages/marketplace-app.tsx, packages/marketplace-management/src/components/pages/marketplace.tsx, packages/marketplace-management/src/components/ui/apps/__tests__/__snapshots__/app-card.test.tsx.snap, packages/marketplace-management/src/components/ui/apps/app-card.tsx, packages/marketplace-management/src/components/ui/offices/__tests__/__snapshots__/offices-groups-tab.test.tsx.snap, packages/marketplace-management/src/components/ui/offices/__tests__/__snapshots__/offices-tab.test.tsx.snap, packages/marketplace-management/src/components/ui/offices/office-group-create.tsx, packages/marketplace-management/src/components/ui/offices/office-group-edit-form.tsx, packages/marketplace-management/src/components/ui/offices/offices-groups-tab.tsx, packages/marketplace-management/src/components/ui/offices/offices-tab.tsx, packages/marketplace-management/src/components/ui/users/__tests_/__snapshots__/user-groups-tab.test.tsx.snap, packages/marketplace-management/src/components/ui/users/__tests_/__snapshots__/users-tab.test.tsx.snap, packages/marketplace-management/src/components/ui/users/edit-user-group.tsx, packages/marketplace-management/src/components/ui/users/edit-user.tsx, packages/marketplace-management/src/components/ui/users/user-groups-tab.tsx, packages/marketplace-management/src/components/ui/users/users-tab.tsx
=> fix: #7735 fixes user pagination mm app

packages/marketplace-management/src/components/ui/users/__tests_/__snapshots__/users-tab.test.tsx.snap, packages/marketplace-management/src/components/ui/users/users-tab.tsx
=> fix: #7735 mm app pagination fix

packages/connect-session/src/browser/__tests__/index.test.ts, packages/connect-session/src/browser/index.ts
=> chore: #7713 remove timeouts for web apps in desktop mode

packages/app-market/src/components/apps-browse/__styles__/featured-hero-apps.ts, packages/app-market/src/components/apps-browse/__styles__/hero-apps.ts, packages/app-market/src/components/apps-detail/__tests__/__snapshots__/apps-detail.test.tsx.snap, packages/app-market/src/components/apps-detail/__tests__/__snapshots__/index.test.tsx.snap, packages/app-market/src/components/apps-detail/apps-detail.tsx, packages/elements/src/components/card/__styles__/index.ts, packages/elements/src/storybook/changelog.stories.mdx
fixes: #7726 
fixes: #7711 
fixes: #7690
=> fix: #7726 #7711 #7690 app market visual fixes

packages/app-market/src/components/apps-browse/__tests__/__snapshots__/filtered-apps.test.tsx.snap, packages/app-market/src/components/apps-browse/__tests__/app-filters-collection.test.tsx, packages/app-market/src/components/apps-browse/__tests__/app-search-filters-bar.test.tsx, packages/app-market/src/components/apps-browse/__tests__/apps-browse.test.tsx, packages/app-market/src/components/apps-browse/__tests__/filtered-apps.test.tsx, packages/app-market/src/components/apps-browse/app-filters-collection.tsx, packages/app-market/src/components/apps-browse/app-search-filters-bar.tsx, packages/app-market/src/components/apps-browse/apps-browse.tsx, packages/app-market/src/components/apps-browse/filtered-apps.tsx, packages/app-market/src/core/config.ts
=> feat: #7677 app market collections deep linking

packages/app-marketplace-admin/src/components/apps-market-manager/app-browse-upsert-modal.tsx
=> fix: #7712 cms search fix

packages/admin-portal/src/components/apps/apps-table.tsx, packages/admin-portal/src/components/apps/filter-form.tsx, packages/admin-portal/src/components/apps/index.tsx, packages/admin-portal/src/components/statistics/index.tsx
=> feat: #7684 admin apps page

packages/admin-portal/src/components/developers/apps-table.tsx, packages/admin-portal/src/components/developers/developers-table.tsx, packages/admin-portal/src/components/developers/filter-form.tsx, packages/admin-portal/src/components/developers/members-table.tsx
=> feat: #7685 admin devs page

packages/admin-portal/src/components/subscriptions/__tests__/__snapshots__/filter-form.test.tsx.snap, packages/admin-portal/src/components/subscriptions/__tests__/__snapshots__/index.test.tsx.snap, packages/admin-portal/src/components/subscriptions/filter-form.tsx, packages/admin-portal/src/components/subscriptions/index.tsx
=> feat: #7784 fixes a filter

packages/developer-portal/src/components/apps/edit/__tests__/__snapshots__/app-listing-tab.test.tsx.snap, packages/developer-portal/src/components/apps/edit/__tests__/__snapshots__/edit-page-tabs.test.tsx.snap, packages/developer-portal/src/components/apps/edit/form-schema/form-fields.ts
=> fix: updated form labels for app video fields

packages/app-marketplace-cms/src/cms/public-controller.ts
=> feat: add query params for content fetching

packages/app-market/src/components/apps-detail/__styles__/index.ts
=> fix: #7828 hml fix app market

packages/admin-portal/src/components/approvals/__tests__/__snapshots__/diff-render-html.test.tsx.snap, packages/app-market/src/components/apps-detail/__styles__/index.ts
=> fix: #7828 further list item fix

packages/admin-portal/src/components/developers/__tests__/__snapshots__/members-table.test.tsx.snap, packages/admin-portal/src/components/developers/members-table.tsx, packages/app-market/src/components/apps-detail/apps-detail.tsx, packages/app-market/src/components/settings/__tests__/__snapshots__/filter-form.test.tsx.snap, packages/app-market/src/components/settings/__tests__/__snapshots__/settings-installed.test.tsx.snap, packages/app-market/src/components/settings/__tests__/filter-form.test.tsx, packages/app-market/src/components/settings/filter-form.tsx, packages/app-market/src/components/settings/settings-installed.tsx
=> feat: #7838 app market prod tweaks

packages/admin-portal/src/components/developers/__tests__/__snapshots__/members-table.test.tsx.snap, packages/admin-portal/src/components/developers/members-table.tsx, packages/app-market/src/components/apps-browse/filtered-apps.tsx, packages/developer-portal/src/components/apps/edit/form-schema/validation-schema.ts
=> feat: #7838 app market and admin tweaks

packages/admin-portal/src/core/use-permissions-state.tsx
=> feat: #7866 admin permissions fix

packages/marketplace/src/components/apps-detail/__styles__/index.ts, packages/marketplace/src/components/apps-detail/apps-detail.tsx, packages/utils-react/src/html-renderer/__styles__/index.ts, packages/utils-react/src/rich-text-editor/__styles__/index.css, packages/utils-react/src/rich-text-editor/__tests__/__snapshots__/index.test.tsx.snap, packages/utils-react/src/rich-text-editor/index.tsx
=> fix: #7882 rich text editor fix

packages/developer-portal/src/components/iaas/index.tsx
=> fix: #7883 dev portal pipelines fix

packages/app-marketplace-cms/src/cms/cms-controller.ts
Fix to allow marketing to update the AppMarket CMS
=> fix: cms permissions fix

packages/deployment-service/orm-datasource.ts, packages/deployment-service/ormconfig.json, packages/deployment-service/package.json, packages/deployment-service/src/http.ts, packages/deployment-service/src/local-http.ts, packages/deployment-service/src/pipeline/pipeline-controller.ts, packages/developer-portal/src/components/apps/index.tsx, packages/developer-portal/src/components/iaas/__tests__/__snapshots__/iaas.test.tsx.snap, packages/developer-portal/src/components/iaas/index.tsx
fixes: #7883
- Resolves content-type issue with pusher/auth call
- Removes dupication of pusher/auth call
- Fixes typeorm changes
- local cors issues
- Fixes creation issue where clientId is missing
=> fix: Pusher/auth call issues resolved

packages/marketplace-management/src/components/ui/offices/offices-tab.tsx
=> feat: added office id to table

packages/admin-portal/src/components/apps/__tests__/__snapshots__/apps-table.test.tsx.snap, packages/admin-portal/src/components/apps/__tests__/__snapshots__/index.test.tsx.snap, packages/admin-portal/src/components/apps/apps-table.tsx
=> feat: added column for public field

packages/developer-portal/src/components/apps/index.tsx, packages/developer-portal/src/components/iaas/index.tsx
=> fix: corrected content-type for auth with pusher-js

packages/admin-portal/src/components/installations/__tests__/__snapshots__/index.test.tsx.snap, packages/admin-portal/src/components/installations/index.tsx, packages/admin-portal/src/components/statistics/index.tsx, packages/admin-portal/src/components/subscriptions/index.tsx, packages/admin-portal/src/services/constants.ts, packages/admin-portal/src/services/customers.ts
=> feat: #7892 #7956 subs and installations fixes

packages/marketplace/src/components/apps-browse/__styles__/hero-apps.ts, packages/marketplace/src/components/apps-browse/__tests__/__snapshots__/featured-hero-apps.test.tsx.snap, packages/marketplace/src/components/apps-browse/__tests__/__snapshots__/hero-apps.test.tsx.snap, packages/marketplace/src/components/apps-browse/featured-hero-apps.tsx, packages/marketplace/src/components/apps-detail/__tests__/__snapshots__/apps-detail.test.tsx.snap, packages/marketplace/src/components/apps-detail/apps-detail.tsx, packages/marketplace/src/components/apps-support/apps-support-item.tsx, packages/utils-react/src/desktop-link/__tests__/__snapshots__/index.test.tsx.snap, packages/utils-react/src/desktop-link/__tests__/index.test.tsx, packages/utils-react/src/desktop-link/index.tsx
=> feat: #7951 marketplace enquiry modal

packages/app-marketplace-admin/src/components/apps-market-manager/app-browse-manage-table.tsx, packages/app-marketplace-cms/src/cms/public-controller.ts
=> fix: app market cms fix

packages/app-marketplace-admin/src/components/apps-market-manager/app-browse-upsert-modal.tsx, packages/app-marketplace-cms/src/cms/public-controller.ts
=> fix: app market cms date time fixes

packages/marketplace/src/components/apps-installed/apps-installed.tsx
=> fix: #7994 app market dev id fix

packages/app-marketplace-admin/src/components/apps-market-manager/app-browse-upsert-modal.tsx, packages/app-marketplace-admin/src/components/apps-market-manager/app-browse-upsert.tsx, packages/developer-portal/src/components/apps/edit/__tests__/__snapshots__/app-listing-tab.test.tsx.snap, packages/developer-portal/src/components/apps/edit/__tests__/__snapshots__/edit-page-tabs.test.tsx.snap, packages/developer-portal/src/components/apps/edit/form-schema/form-fields.ts, packages/developer-portal/src/components/apps/edit/form-schema/validation-schema.ts, packages/marketplace/src/components/apps-support/index.tsx, packages/marketplace/src/utils/navigation.ts
=> fix: app market go live fixes

packages/app-marketplace-cms/src/cms/cms-provider.ts, packages/app-marketplace-cms/src/cms/marketplace-app-dto.ts, packages/app-marketplace-cms/src/cms/marketplace-app-model.ts, packages/app-marketplace-cms/src/http.ts, packages/foundations-ts-definitions/marketplace-cms/index.ts
=> fix: correct marketplace cms islive

packages/utils-react/src/desktop-link/__tests__/__snapshots__/index.test.tsx.snap, packages/utils-react/src/desktop-link/__tests__/index.test.tsx, packages/utils-react/src/desktop-link/index.tsx
=> fix: #8005 fix enquire link in AC

packages/marketplace/src/core/__tests__/analytics-banner.test.tsx, packages/marketplace/src/core/analytics-banner.tsx
=> chore: #8009 prevent mixpanel tracking in dev

packages/admin-portal/src/core/index.tsx, packages/app-builder/src/core/index.tsx, packages/app-marketplace-admin/src/core/index.tsx, packages/data-warehouse/src/core/index.tsx, packages/developer-portal/src/core/index.tsx, packages/geo-diary/src/core/index.tsx, packages/insights/src/core/index.tsx, packages/marketplace-management/src/core/index.tsx, packages/marketplace/src/core/index.tsx, packages/new-auth-ui/src/core/index.tsx, packages/payments-client/src/core/index.tsx, packages/react-app-scaffolder/app/templates/react-app/src/core/index.tsx, packages/reapit-connect/src/core/index.tsx, packages/ts-scripts/src/webpack/webpack.config.prod.js
=> feat: #8019 adds cache buster to config json files

packages/developer-portal/src/components/webhooks/state/use-webhooks-state.tsx
=> fix: #7990 #8022 dev portal fixes

packages/app-marketplace-admin/src/components/apps-market-manager/app-browse-upsert-modal.tsx
=> fix: #7998 cms date fix

packages/marketplace/src/core/__tests__/analytics-banner.test.tsx, packages/marketplace/src/core/analytics-banner.tsx
=> fix: mixpanel identifiers updated

packages/marketplace/src/components/apps-detail/app-install-success-modal.tsx, packages/marketplace/src/components/apps-detail/apps-detail.tsx, packages/marketplace/src/components/apps-installed/apps-installed.tsx, packages/marketplace/src/components/apps-support/apps-support-item.tsx, packages/marketplace/src/utils/navigation.ts
=> feat: add a few more fields to mixpanel

packages/marketplace/src/core/__tests__/__snapshots__/analytics-banner.test.tsx.snap, packages/marketplace/src/core/__tests__/analytics-banner.test.tsx, packages/marketplace/src/core/analytics-banner.tsx
=> fix: #8046 fix mixpanel identify users

packages/admin-portal/src/components/subscriptions/__tests__/__snapshots__/create-subscriptions.test.tsx.snap, packages/admin-portal/src/components/subscriptions/create-subscriptions.tsx
=> fix: #8049 admin portal subs fix

packages/cli/src/abstract.command.ts, packages/cli/src/commands/check-version.ts
=> fix: don't require config for update command

packages/marketplace/src/core/analytics-banner.tsx, packages/marketplace/src/core/use-apps-browse-state.tsx
=> fix: #8109 user email downcase

packages/rc-mfa-config/src/components/admin/__tests__/__snapshots__/download-users-csv.test.tsx.snap, packages/rc-mfa-config/src/components/admin/__tests__/__snapshots__/index.test.tsx.snap, packages/rc-mfa-config/src/components/admin/__tests__/download-users-csv.test.tsx, packages/rc-mfa-config/src/components/admin/download-users-csv.tsx, packages/rc-mfa-config/src/components/admin/index.tsx
=> feat: #8151 download user csv

packages/developer-portal/src/components/apps/pipeline/pipeline-environment-update-table-row.tsx, packages/developer-portal/src/components/apps/pipeline/pipeline-environment.tsx
=> fix: corrected pipeline env validation

packages/developer-portal/src/core/private-route-wrapper.tsx
=> fix: #8022 dev portal internal redirect bug

packages/marketplace-management/src/components/ui/apps/__tests__/__snapshots__/app-installation-confirmation-modal.test.tsx.snap, packages/marketplace-management/src/components/ui/apps/__tests__/__snapshots__/app-referrals-confirm.test.tsx.snap, packages/marketplace-management/src/components/ui/apps/__tests__/__snapshots__/app-referrals-display.test.tsx.snap, packages/marketplace-management/src/components/ui/apps/__tests__/app-referrals-display.test.tsx, packages/marketplace-management/src/components/ui/apps/app-installation-confirmation-modal.tsx, packages/marketplace-management/src/components/ui/apps/app-referrals-confirm.tsx, packages/marketplace-management/src/components/ui/apps/app-referrals-display.tsx
=> feat: #8187 tweaks to referrals

packages/connect-session/README.md
=> chore: update-connect-session-readme

packages/payments-service/cdk/cdk-stack.ts, packages/payments-service/package.json, packages/payments-service/src/client-config/dto.ts, packages/payments-service/src/client-config/index.ts, packages/payments-service/src/client-config/model.ts, packages/payments-service/src/client-config/module.ts, packages/payments-service/src/client-config/private-controller.ts, packages/payments-service/src/client-config/provider.ts, packages/payments-service/src/client-config/public-controller.ts, packages/payments-service/src/client-config/session-guard.ts, packages/payments-service/src/core/app.ts, packages/payments-service/src/core/ses-client.ts, packages/payments-service/src/payment-receipt/module.ts, packages/payments-service/src/payment-receipt/provider.ts, packages/payments-service/src/payment-request/provider.ts, packages/payments-service/src/session/provider.ts
=> feat: #8228 adds payments config endpoint

packages/admin-portal/src/components/installations/__tests__/__snapshots__/index.test.tsx.snap, packages/admin-portal/src/components/installations/__tests__/index.test.tsx, packages/admin-portal/src/components/installations/index.tsx, packages/admin-portal/src/components/statistics/index.tsx, packages/admin-portal/src/tests/__stubs__/installations.ts, packages/developer-portal/src/components/analytics/installations/__tests__/installations-by-app-chart.test.tsx, packages/developer-portal/src/components/analytics/installations/installations-by-app-chart.tsx, packages/developer-portal/src/components/apps/installations/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/installations/__tests__/download-installations-csv.test.tsx, packages/developer-portal/src/components/apps/installations/download-installations-csv.tsx, packages/developer-portal/src/components/apps/installations/index.tsx, packages/developer-portal/src/components/webhooks/state/use-webhooks-state.tsx, packages/developer-portal/src/tests/__stubs__/installations.ts, packages/marketplace-management/src/components/ui/apps/app-card.tsx, packages/marketplace/src/components/settings/__tests__/__snapshots__/settings-installed.test.tsx.snap, packages/marketplace/src/components/settings/__tests__/settings-installed.test.tsx, packages/marketplace/src/components/settings/settings-installed.tsx, packages/marketplace/src/tests/__stubs__/installations.ts, packages/payments-portal/tsconfig.json
=> feat: #8392 #8059 improves installations handling

packages/developer-portal/src/components/analytics/page/__tests__/__snapshots__/controls.test.tsx.snap, packages/developer-portal/src/components/analytics/page/controls.tsx, packages/developer-portal/src/components/apps/new/permissions-options-content.tsx, packages/developer-portal/src/components/webhooks/webhooks-manage.tsx
fixes: #8312 
fixes: #8391 
fixes: #8365
=> feat: #8312 #8391 #8365 dev portal enhancements

packages/elements/src/components/pagination/__styles__/index.ts, packages/elements/src/components/pagination/__tests__/__snapshots__/pagination.test.tsx.snap, packages/elements/src/components/pagination/__tests__/pagination.test.tsx, packages/elements/src/components/pagination/pagination.stories.mdx, packages/elements/src/components/pagination/pagination.tsx, packages/elements/src/storybook/changelog.stories.mdx
=> feat: #8324 adds pagination start end buttons

packages/connect-session/package.json, packages/connect-session/src/browser/__tests__/index.test.ts, packages/connect-session/src/browser/index.ts, yarn.lock
=> feat: #8204 connect session nonce

packages/security-header-lambda/serverless.yml
=> feat: #8479 update security header lambda

packages/payments-client/src/components/admin/index.tsx, packages/payments-client/src/components/payments/__tests__/__snapshots__/index.test.tsx.snap, packages/payments-client/src/components/payments/__tests__/__snapshots__/payment-request-modal.test.tsx.snap, packages/payments-client/src/components/payments/index.tsx, packages/payments-client/src/components/payments/payment-request-modal.tsx, packages/payments-client/src/components/payments/payments-filter-controls.tsx, packages/payments-service/src/payment-receipt/__tests__/__snapshots__/provider.test.ts.snap, packages/payments-service/src/payment-receipt/template.ts, packages/payments-service/src/payment-request/__tests__/__snapshots__/provider.test.ts.snap, packages/payments-service/src/payment-request/template.ts, packages/use-reapit-data/src/use-reapit-get.ts
=> fix: #8483 payments qa fixes

packages/security-header-lambda/src/index.ts
=> fix: #8502 3d secure frame header policy added

packages/payments-client/src/components/payment/__tests__/__snapshots__/payment.test.tsx.snap, packages/payments-portal/src/components/payment/__tests__/__snapshots__/payment.test.tsx.snap, packages/payments-portal/src/components/payment/queries.ts, packages/payments-ui/src/payment-page/__tests__/__snapshots__/index.test.tsx.snap, packages/payments-ui/src/payment-page/__tests__/__snapshots__/payment-page-content.test.tsx.snap, packages/payments-ui/src/payment-page/index.tsx
=> fix: #8533 final qa tweak

packages/security-header-lambda/src/index.ts
=> fix: #8533 fixes image headers

packages/payments-client/src/components/admin/__tests__/__snapshots__/index.test.tsx.snap, packages/payments-client/src/components/admin/__tests__/index.test.tsx, packages/payments-client/src/components/admin/index.tsx, packages/payments-portal/src/components/payment/queries.ts, packages/rc-mfa-config/src/components/nav/__tests__/__snapshots__/index.test.tsx.snap, packages/rc-mfa-config/src/components/nav/index.tsx, packages/rc-mfa-config/src/core/__tests__/__snapshots__/router.test.tsx.snap, packages/security-header-lambda/src/index.ts
=> fix: #8533 payments qa tweaks

packages/geo-diary/src/components/pages/appointment/__tests__/__snapshots__/appointment.test.tsx.snap, packages/geo-diary/src/components/ui/appointment-time/__tests__/__snapshots__/appointment-time.test.tsx.snap, packages/geo-diary/src/components/ui/appointment-time/appointment-time.tsx, packages/geo-diary/src/components/ui/cancel-confirm-modal/__tests__/index.test.tsx, packages/geo-diary/src/components/ui/cancel-confirm-modal/index.tsx, packages/geo-diary/src/components/ui/follow-up-notes-modal/__tests__/index.test.tsx, packages/geo-diary/src/components/ui/follow-up-notes-modal/index.tsx, packages/graphql-server/src/resolvers/appointments/__tests__/api.test.ts, packages/graphql-server/src/resolvers/appointments/api.ts
=> fix: #8363 geo diary cache policy

packages/admin-portal/src/components/subscriptions/index.tsx
=> fix: #8485 admin filtering

packages/developer-portal/src/core/private-route-wrapper.tsx, packages/marketplace/src/core/__tests__/router.test.tsx, packages/marketplace/src/core/private-route-wrapper.tsx, packages/marketplace/src/core/router.tsx
=> feat: #8559 block app market access

packages/admin-portal/src/components/customers/__tests__/__snapshots__/org-groups-table.test.tsx.snap, packages/admin-portal/src/components/customers/org-groups-table.tsx, packages/admin-portal/src/components/statistics/__tests__/index.test.tsx, packages/admin-portal/src/components/statistics/index.tsx
=> feat: #8398 export office groups

packages/cli/src/commands/pipeline/create.ts, packages/cli/src/commands/pipeline/edit.ts, packages/cli/src/commands/release/repo.ts, packages/cli/src/commands/release/zip.ts, packages/deployment-service/cdk/cdk.ts, packages/deployment-service/src/pipeline-runner/pipeline-runner-controller.ts, packages/deployment-service/src/pipeline/__test__/pipeline-controller.test.ts, packages/deployment-service/src/pipeline/pipeline-controller.ts
=> fix: iaas repairs

packages/marketplace-management/src/components/ui/users/__tests_/edit-user-group.test.tsx, packages/marketplace-management/src/components/ui/users/edit-user-group.tsx
=> feat: #8703 mm app user search

packages/developer-portal/src/components/desktop/__styles__/styles.tsx
=> fix: #8735 desktop subscribe button

packages/utils-nest/package.json
=> fix: remove public param for publish

packages/ts-scripts/package.json
=> feat: made ts-scripts package public

packages/ts-bundler/package.json
=> feat: made ts-bundler public

packages/elements/src/storybook/changelog.stories.mdx
=> feat: #8789 update changelog for elements

packages/elements/src/components/layout/__styles__/index.ts, packages/elements/src/storybook/changelog.stories.mdx
=> feat: #8789 fixes safari bug when scrolling

packages/utils-nest/package.json
=> fix: made nestjs-utils public

packages/utils-common/src/validators/__tests__/index.test.ts, packages/utils-common/src/validators/index.ts
=> fix: allow left and right single quotation mark

packages/payments-service/tsconfig.json, packages/utils-nest/package.json, packages/utils-nest/tsconfig.json
=> fix: package main issues in local and built

packages/marketplace-management/src/components/ui/offices/__tests__/__snapshots__/offices-groups-tab.test.tsx.snap, packages/marketplace-management/src/components/ui/offices/__tests__/offices-groups-tab.test.tsx, packages/marketplace-management/src/components/ui/offices/offices-groups-tab.tsx
=> feat: #8778 adds office group filtering

packages/admin-portal/src/components/developers/__tests__/__snapshots__/developers-table.test.tsx.snap, packages/admin-portal/src/components/developers/__tests__/__snapshots__/index.test.tsx.snap, packages/admin-portal/src/components/developers/__tests__/__snapshots__/invite-member-modal-form.test.tsx.snap, packages/admin-portal/src/components/developers/__tests__/__snapshots__/members-table.test.tsx.snap, packages/admin-portal/src/components/developers/__tests__/developers-table.test.tsx, packages/admin-portal/src/components/developers/__tests__/invite-member-modal-form.test.tsx, packages/admin-portal/src/components/developers/__tests__/members-table.test.tsx, packages/admin-portal/src/components/developers/developers-table.tsx, packages/admin-portal/src/components/developers/invite-member-modal-form.tsx, packages/admin-portal/src/components/developers/members-table.tsx, packages/admin-portal/src/components/developers/validation-schema.ts, packages/use-reapit-data/src/update-actions.ts
=> feat: #8712 #8767 updates to admin portal

packages/developer-portal/src/components/settings/members/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/settings/members/__tests__/__snapshots__/member-update-controls.test.tsx.snap, packages/developer-portal/src/components/settings/members/index.tsx, packages/developer-portal/src/components/settings/members/member-update-controls.tsx, packages/foundations-ts-definitions/types/marketplace-schema.ts
=> feat: #8489 main admin dev portal

packages/developer-portal/src/components/apps/detail/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/new/config.tsx, packages/developer-portal/src/components/apps/page/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/utils/__tests__/handle-default-form-values.test.ts, packages/developer-portal/src/tests/__stubs__/apps.ts
=> fix: #8880 images scope no longer valid

packages/deployment-service/src/pipeline/pipeline-dto.ts
=> fix: increased outdir validation length

packages/deployment-service/src/pipeline/pipeline-dto.ts
=> fix: increased outdir length validation

packages/admin-portal/serverless.yml, packages/app-builder/serverless.yml, packages/app-marketplace-admin/cdk-stack.ts, packages/data-warehouse/serverless.yml, packages/developer-portal/serverless.yml, packages/elements/serverless.yml, packages/geo-diary/serverless.yml, packages/insights/serverless.yml, packages/marketplace-management/serverless.yml, packages/marketplace/serverless.yml, packages/new-auth-ui/cdk-stack.ts, packages/payments-client/cdk-stack.ts, packages/payments-portal/cdk-stack.ts, packages/rc-mfa-config/serverless.yml, packages/react-app-scaffolder/app/templates/_serverless.yml, packages/reapit-connect/serverless.yml
=> feat: #8234 react apps build refactor

packages/ts-scripts/src/cdk/components/site.ts
=> fix: #8950 release workflows, make bucket more secure

packages/utils-nest/src/auth/token-provider.ts
=> fix: added condition for not authorization header set

packages/deployment-service/package.json, packages/deployment-service/src/codebuild/codebuild-executor-workflow.ts, packages/developer-portal/src/components/apps/pipeline/__tests__/pipeline-configure.test.tsx, packages/developer-portal/src/components/apps/pipeline/pipeline-configure.tsx, packages/developer-portal/src/utils/yup.ts, packages/ts-scripts/src/cdk/components/codebuild-project.ts, yarn.lock
=> fix: package manager selection

packages/rc-mfa-config/cdk-stack.ts
=> feat: #7350 missing cdk config

packages/developer-portal/cdk-stack.ts
=> fix: corrected condition to prevent failure of cert lookup

packages/admin-portal/cdk-stack.ts, packages/app-builder/cdk-stack.ts, packages/app-marketplace-admin/cdk-stack.ts, packages/data-warehouse/cdk-stack.ts, packages/developer-portal/cdk-stack.ts, packages/elements/cdk-stack.ts, packages/geo-diary/cdk-stack.ts, packages/insights/cdk-stack.ts, packages/marketplace-management/cdk-stack.ts, packages/marketplace/cdk-stack.ts, packages/payments-client/cdk-stack.ts, packages/payments-portal/cdk-stack.ts, packages/rc-mfa-config/cdk-stack.ts, packages/reapit-connect/cdk-stack.ts
=> feat: #7350 adds catch on build errors

packages/elements/src/components/tabs/__styles__/index.ts, packages/use-reapit-data/src/use-reapit-update.ts
=> feat: #7350 catch use reapit data error, fix scrollbar elements

packages/admin-portal/cdk-stack.ts, packages/app-builder/cdk-stack.ts, packages/app-marketplace-admin/cdk-stack.ts, packages/data-warehouse/cdk-stack.ts, packages/developer-portal/cdk-stack.ts, packages/elements/cdk-stack.ts, packages/geo-diary/cdk-stack.ts, packages/insights/cdk-stack.ts, packages/marketplace-management/cdk-stack.ts, packages/marketplace/cdk-stack.ts, packages/payments-client/cdk-stack.ts, packages/payments-portal/cdk-stack.ts, packages/rc-mfa-config/cdk-stack.ts, packages/reapit-connect/cdk-stack.ts
=> feat: #7350 fixes cdk deploy

packages/deployment-service/src/codebuild/codebuild-executor-workflow.ts
=> fix: added command for node-linker to be node_modules

packages/developer-portal/src/components/apps/detail/__tests__/index.test.tsx, packages/developer-portal/src/components/apps/detail/index.tsx, packages/developer-portal/src/components/apps/edit/__tests__/__snapshots__/ac-integration-tab.test.tsx.snap, packages/developer-portal/src/components/apps/edit/__tests__/ac-integration-tab.test.tsx, packages/developer-portal/src/components/apps/edit/ac-integration-tab.tsx, packages/developer-portal/src/components/apps/edit/form-schema/form-fields.ts, packages/developer-portal/src/components/apps/edit/form-schema/validation-schema.ts, packages/developer-portal/src/components/apps/installations/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/apps/installations/__tests__/__snapshots__/offices-table.test.tsx.snap, packages/developer-portal/src/components/apps/installations/__tests__/index.test.tsx, packages/developer-portal/src/components/apps/installations/__tests__/offices-table.test.tsx, packages/developer-portal/src/components/apps/installations/index.tsx, packages/developer-portal/src/components/apps/installations/offices-table.tsx, packages/developer-portal/src/components/apps/utils/__tests__/handle-default-form-values.test.ts, packages/developer-portal/src/components/apps/utils/format-form-values.ts, packages/developer-portal/src/components/apps/utils/handle-default-form-values.ts, packages/developer-portal/src/core/router.tsx, packages/developer-portal/src/tests/__stubs__/apps.ts, packages/developer-portal/src/tests/__stubs__/installations.ts, packages/foundations-ts-definitions/types/marketplace-schema.ts, packages/foundations-ts-definitions/types/platform-schema.ts, packages/use-reapit-data/src/__tests__/use-reapit-update.test.tsx, packages/use-reapit-data/src/api-constants.ts, packages/use-reapit-data/src/update-actions.ts, packages/use-reapit-data/src/use-reapit-update.ts
fixes: #9024 
fixes: #8937 
fixes: #8935 
fixes: #8475
=> feat: #9024 #8937 #8935 #8475 dev portal updates

packages/security-header-lambda/cdk/cdk-stack.ts, packages/security-header-lambda/cdk/consts.ts, packages/security-header-lambda/package.json, yarn.lock
=> fix: corrected path location and changed export const of cfn value

packages/cognito-custom-mail-lambda/src/mailer/templates/admin-user-invite.mjml, packages/cognito-custom-mail-lambda/src/mailer/templates/confirm-registration.mjml, packages/cognito-custom-mail-lambda/src/mailer/templates/forgot-password.mjml
Revert inadvertent commit to master
=> task: Revert changes to email templates

packages/cognito-custom-mail-lambda/src/mailer/templates/admin-user-invite.mjml, packages/cognito-custom-mail-lambda/src/mailer/templates/confirm-registration.mjml, packages/cognito-custom-mail-lambda/src/mailer/templates/forgot-password.mjml
fixes: #9027 Updated Email templates with prefix "Temporary" for temporary password update email and updated service desk content.
=> chore: Tweak email Template contents

packages/admin-portal/src/components/subscriptions/__tests__/index.test.tsx, packages/admin-portal/src/components/subscriptions/index.tsx
=> fix: #9120 fixes subs cancel

packages/developer-portal/src/tests/__stubs__/pipeline.ts
=> fix: #8353 fixes sonar bug

.github/ISSUE_TEMPLATE/analytics-schema.md
Update the labels to use needs-triage instead of backend
=> task: Update analytics-schema.md

packages/elements/src/storybook/changelog.stories.mdx, packages/elements/src/storybook/concepts.stories.mdx, packages/elements/src/storybook/welcome.tsx
=> fix: corrected spelling of across

packages/marketplace/src/components/carousel/__styles__/index.ts
=> fix: #9092 fixes app market carousel

packages/marketplace/src/components/apps-browse/featured-hero-apps.tsx, packages/marketplace/src/components/apps-browse/hero-apps.tsx
=> fix: #9261 app market back btn

packages/rc-mfa-config/cdk-stack.ts
=> fix: hosted zone construct name

packages/rc-mfa-config/cdk-stack.ts, packages/ts-scripts/src/cdk/components/stack.ts
=> fix: crossRegionReferences

packages/rc-mfa-config/cdk-stack.ts, packages/rc-service/cdk-stack.ts, packages/ts-scripts/src/cdk/components/multi-region-site.ts, packages/ts-scripts/src/cdk/components/site.ts, packages/ts-scripts/src/cdk/index.ts
=> feat: rc-service-app anz zone

packages/rc-service/cdk-stack.ts
=> feat: rc service app - create cert and add domain to cloudfront

packages/rc-mfa-config/src/core/connect-session.tsx, packages/rc-mfa-config/src/types/env.d.ts, packages/rc-service/src/core/connect-session.tsx, packages/rc-service/src/types/env.d.ts, packages/use-reapit-data/src/api-constants.ts, packages/use-reapit-data/src/api-regions.ts
=> feat: Adapt FE apps based on domainMappings config value

packages/ts-scripts/src/cdk/components/codebuild-project.ts
=> feat: increased the max ram of codebuild resource

packages/developer-portal/src/components/analytics/installations/index.tsx
=> fix: #9214 analytics filter

packages/deployment-service/cdk/lib/cdk-stack.ts, packages/deployment-service/cdk/lib/create-lambda.ts, packages/deployment-service/src/github/github-webhook-controller.ts, packages/deployment-service/src/http.ts, packages/deployment-service/src/sqs.ts
=> fix: corrected crypto issue by making body a string for verify

packages/developer-portal/src/components/desktop/developer-edition-modal.tsx, packages/rc-service/src/components/users/index.tsx, packages/rc-service/src/components/users/user-content.tsx
=> feat: #9339 #9391 updates

packages/cognito-custom-mail-lambda/src/mailer/custom-mailer.ts
=> fix: remove userpool id check

packages/connect-session/src/browser/index.ts
=> fix: #9511 connect session refresh issue

packages/deployment-service/src/codebuild/source-provider.ts
=> fix: added branch to github pull

packages/connect-session/package.json
=> chore: move snyk to dev dep

packages/payments-client/src/components/payment/__tests__/__snapshots__/payment.test.tsx.snap, packages/payments-portal/src/components/payment/__tests__/__snapshots__/payment.test.tsx.snap, packages/payments-service/src/payment-receipt/__tests__/__snapshots__/provider.test.ts.snap, packages/payments-service/src/payment-receipt/template.ts, packages/payments-service/src/payment-request/__tests__/__snapshots__/provider.test.ts.snap, packages/payments-service/src/payment-request/template.ts, packages/payments-ui/src/payment-page/__tests__/__snapshots__/index.test.tsx.snap, packages/payments-ui/src/payment-page/__tests__/__snapshots__/payment-form.test.tsx.snap, packages/payments-ui/src/payment-page/__tests__/__snapshots__/payment-page-content.test.tsx.snap, packages/payments-ui/src/payment-page/payment-form.tsx
=> feat: #9250 #9639 payments text changes

packages/admin-portal/src/components/usage/__tests__/__snapshots__/usage-table.test.tsx.snap, packages/admin-portal/src/components/usage/usage-table.tsx, packages/foundations-ts-definitions/traffic-schema/marketplace-traffic-event-schema.ts
=> feat: petes changes for admin portal

packages/developer-portal/src/components/login/__tests__/__snapshots__/select-role.test.tsx.snap, packages/developer-portal/src/components/login/select-role.tsx
=> feat: updated register select roles page

packages/rc-service/src/components/users/index.tsx, packages/use-reapit-data/src/use-reapit-get.ts, packages/use-reapit-data/src/use-reapit-update.ts
=> feat: #9416 #9745 fixes desktop bug, adds mfa filter

packages/utils-nest/src/auth/guards/access-token-provider.ts
=> refactor: added condition to change platform prod url

packages/developer-portal/src/components/login/__tests__/__snapshots__/select-role.test.tsx.snap, packages/developer-portal/src/components/login/select-role.tsx, packages/developer-portal/src/types/env.d.ts
=> refactor: #9753 feature flag previously made changes for additional releases

docker-compose.yml, packages/rc-service/src/components/orgs/__tests__/__snapshots__/index.test.tsx.snap, packages/rc-service/src/components/orgs/index.tsx, packages/rc-service/src/components/users/index.tsx
- Added result count to user/orgs tables
- Fixed message on orgs table when no search results
- Added rc-service app to docker-compose
=> feat: 9812 Add total search results count

docker-compose.yml, packages/developer-portal/src/components/apps/edit/form-schema/validation-schema.ts
- Updated app edit validation schema so that Launch URI is no longer required for an app revision if the app is no listed
- NB I couldn't see any tests around the validation rules, let me know if I've just missed them. Thanks
=> feat: 9766 Launch URI no longer required for unlisted app

docker-compose.yml, packages/rc-mfa-config/src/components/admin/__tests__/__snapshots__/index.test.tsx.snap, packages/rc-mfa-config/src/components/admin/index.tsx
Update to display user count on MFA screen
=> feat: 9829 - Add 'Total Users' count on MFA App

packages/developer-portal/package.json
=> feat: #9760 dev portal release patch

packages/rc-mfa-config/src/components/home/index.tsx
=> chore: crudely change docs link for anz

packages/app-marketplace-admin/src/components/apps-market-manager/__tests__/app-browse-manage-table.test.tsx, packages/app-marketplace-admin/src/components/apps-market-manager/app-browse-manage-table.tsx
=> fix: corrected issue where duplicate indexes cannot be resolved

packages/elements/src/components/nav/__styles__/index.ts
=> fix: border hidden nav fix

packages/elements/package.json, packages/elements/src/components/tabs/__tests__/__snapshots__/tabs.test.tsx.snap, packages/elements/src/components/tabs/__tests__/tabs.test.tsx, packages/elements/src/components/tabs/tabs.stories.mdx, packages/elements/src/components/tabs/tabs.tsx
=> feat: #9990 add controlled option to tabs

packages/rc-mfa-config/cdk-stack.ts, packages/rc-service/cdk-stack.ts
⚠️  Only merge once https://github.com/reapit/devops-infrastructure-core/pull/533 is merged
=> chore: rc apps - do full anz deployment

packages/deployment-service/src/codebuild/codebuild-executor-workflow.ts
=> fix: added mv command for hidden files and folders

packages/app-marketplace-admin/src/components/apps-market-manager/app-browse.styles.ts
=> fix: remove tag colour as it's been resolved in elements

packages/elements/src/components/input/__styles__/index.ts, packages/payments-client/src/components/payment/__tests__/__snapshots__/payment.test.tsx.snap, packages/payments-portal/src/components/payment/__tests__/__snapshots__/payment.test.tsx.snap, packages/payments-service/cdk/cdk.ts, packages/payments-service/src/opayo/dto.ts, packages/payments-ui/src/payment-page/__tests__/__snapshots__/index.test.tsx.snap, packages/payments-ui/src/payment-page/__tests__/__snapshots__/payment-form.test.tsx.snap, packages/payments-ui/src/payment-page/__tests__/__snapshots__/payment-page-content.test.tsx.snap, packages/payments-ui/src/payment-page/__tests__/payment-handlers.test.ts, packages/payments-ui/src/payment-page/index.tsx, packages/payments-ui/src/payment-page/payment-form.tsx, packages/payments-ui/src/payment-page/payment-handlers.ts, packages/payments-ui/src/payment-page/payment-validation-schema.ts
=> fix: #10083 payments app timeout patch

packages/rc-mfa-config/src/components/nav/__tests__/__snapshots__/index.test.tsx.snap, packages/rc-mfa-config/src/components/nav/index.tsx, packages/rc-mfa-config/src/core/__tests__/__snapshots__/router.test.tsx.snap, packages/rc-service/src/components/nav/__tests__/__snapshots__/index.test.tsx.snap, packages/rc-service/src/components/nav/index.tsx
=> feat: #10247 hides app switcher in aus

packages/marketplace/src/components/nav/nav.tsx, packages/marketplace/src/components/settings/__tests__/__snapshots__/index.test.tsx.snap, packages/marketplace/src/components/settings/__tests__/__snapshots__/settings-installed.test.tsx.snap, packages/marketplace/src/components/settings/__tests__/__snapshots__/settings-profile.test.tsx.snap, packages/marketplace/src/components/settings/__tests__/index.test.tsx, packages/marketplace/src/components/settings/index.tsx, packages/marketplace/src/components/settings/settings-installed.tsx, packages/marketplace/src/components/settings/settings-profile.tsx
=> fix: #10370 show profile dropdown

packages/geo-diary/src/components/pages/appointment/__tests__/__snapshots__/appointment.test.tsx.snap, packages/geo-diary/src/components/ui/appointment-list/__tests__/__snapshots__/appointment-list.test.tsx.snap, packages/geo-diary/src/components/ui/appointment-tile/__tests__/__snapshots__/appointment-items.test.tsx.snap, packages/geo-diary/src/components/ui/appointment-tile/__tests__/__snapshots__/appointment-tile.test.tsx.snap, packages/geo-diary/src/components/ui/appointment-tile/__tests__/__snapshots__/attendee-item.test.tsx.snap, packages/geo-diary/src/components/ui/appointment-tile/__tests__/__snapshots__/landlord-item.test.tsx.snap, packages/geo-diary/src/components/ui/appointment-tile/__tests__/__snapshots__/property-item.test.tsx.snap, packages/geo-diary/src/components/ui/appointment-tile/__tests__/__snapshots__/vendor-item.test.tsx.snap, packages/geo-diary/src/components/ui/appointment-tile/attendee-item.tsx, packages/geo-diary/src/components/ui/appointment-tile/landlord-item.tsx, packages/geo-diary/src/components/ui/appointment-tile/property-item.tsx, packages/geo-diary/src/components/ui/appointment-tile/vendor-item.tsx, packages/geo-diary/src/components/ui/my-location/__styles__/styles.ts, packages/geo-diary/src/components/ui/my-location/my-location.tsx, packages/geo-diary/src/core/error-boundary/__tests__/__snapshots__/index.test.tsx.snap, packages/geo-diary/src/core/error-boundary/index.tsx, packages/geo-diary/src/core/private-route-wrapper.tsx
=> fix: geo diary icons

packages/marketplace/src/components/settings/index.tsx, packages/marketplace/src/components/settings/settings-installed.tsx
=> fix: #10396 fixed permission check

packages/cognito-custom-mail-lambda/src/mailer/templates/admin-user-invite.mjml, packages/cognito-custom-mail-lambda/src/mailer/templates/confirm-registration.mjml, packages/cognito-custom-mail-lambda/src/mailer/templates/forgot-password.mjml
- Replace logo
- Fix font color on footer text
- Fix border rounding
- Fix font weight on button text
=> chore: Updated templates following feedback from ANZ

packages/marketplace/src/components/settings/settings-installed.tsx
=> fix: #10396 permissions check on installs

packages/payments-portal/src/components/payment/__styles__/index.ts
=> fix: #10521 payments portal scroll fix

packages/admin-portal/src/components/approvals/__tests__/__snapshots__/index.test.tsx.snap, packages/admin-portal/src/components/approvals/index.tsx, packages/foundations-ts-definitions/types/marketplace-schema.ts
Update to display the user who created the revision on the approvals screen.
=> feat: #10485 - Include Created By on approvals list

packages/foundations-ts-definitions/scripts/create-index-file.js, packages/foundations-ts-definitions/scripts/fetch-definitions.js, packages/foundations-ts-definitions/scripts/format-code.js, packages/foundations-ts-definitions/types/organisations-schema.ts, packages/rc-mfa-config/src/components/admin/__tests__/__snapshots__/fetch-authenticators.test.tsx.snap, packages/rc-mfa-config/src/components/admin/__tests__/__snapshots__/index.test.tsx.snap, packages/rc-mfa-config/src/components/admin/fetch-authenticators.tsx
=> fix: #10663 mfa and definitions fixes

packages/rc-service/src/components/users/index.tsx
=> refactor: renamed newly added negotiator labels

packages/rc-service/src/components/users/index.tsx
=> feat: added filters and column for first login date

packages/developer-portal/src/components/apps/new/__tests__/index.test.tsx, packages/developer-portal/src/components/apps/new/index.tsx
=> feat: #10782 default category for web feed

packages/admin-portal/src/components/statistics/index.tsx, packages/developer-portal/src/components/apps/new/__tests__/index.test.tsx
=> feat: added fixed consumption to installations csv download

packages/developer-portal/src/components/apps/detail/index.tsx
- Removes links to unpublished code examples
fixes: #10218
=> chore: #10218 Remove unpublished example project links

packages/ts-scripts/src/cdk/components/rds-database.ts
=> refactor: upgraded cluster size to medium preempt aurora version bump

packages/ts-scripts/src/cdk/components/rds-database.ts
=> refactor: changed image version

packages/data-warehouse/package.json, packages/data-warehouse/src/components/accounts/__tests__/__snapshots__/account-progress-bar.test.tsx.snap, packages/data-warehouse/src/components/accounts/__tests__/__snapshots__/account-provision-modal.test.tsx.snap, packages/data-warehouse/src/components/accounts/__tests__/__snapshots__/account-update-modal.test.tsx.snap, packages/data-warehouse/src/components/accounts/__tests__/__snapshots__/accounts-table.test.tsx.snap, packages/data-warehouse/src/components/accounts/__tests__/__snapshots__/accounts.test.tsx.snap, packages/data-warehouse/src/components/data/__tests__/__snapshots__/data-sets-table.test.tsx.snap, packages/data-warehouse/src/components/data/__tests__/__snapshots__/data.test.tsx.snap, packages/data-warehouse/src/components/data/__tests__/__snapshots__/shares-table.test.tsx.snap, packages/data-warehouse/src/components/error-boundary/__tests__/__snapshots__/index.test.tsx.snap, packages/data-warehouse/src/components/nav/__tests__/__snapshots__/index.test.tsx.snap, packages/data-warehouse/src/components/network/__tests__/__snapshots__/index.test.tsx.snap, packages/data-warehouse/src/components/network/__tests__/__snapshots__/ip-create-modal.test.tsx.snap, packages/data-warehouse/src/components/network/__tests__/__snapshots__/ip-table.test.tsx.snap, packages/data-warehouse/src/components/network/__tests__/__snapshots__/network.test.tsx.snap, packages/data-warehouse/src/components/network/__tests__/__snapshots__/rule-create-modal.test.tsx.snap, packages/data-warehouse/src/components/network/__tests__/__snapshots__/rules-table.test.tsx.snap, packages/data-warehouse/src/components/network/__tests__/__snapshots__/use-network-state.test.tsx.snap, packages/data-warehouse/src/core/__tests__/__snapshots__/app.test.tsx.snap, packages/data-warehouse/src/core/__tests__/__snapshots__/private-route-wrapper.test.tsx.snap, packages/data-warehouse/src/core/__tests__/__snapshots__/router.test.tsx.snap, packages/data-warehouse/src/core/__tests__/__snapshots__/use-global-state.test.tsx.snap, yarn.lock
=> fix: #11294 revert elements version

packages/data-warehouse/src/components/network/__tests__/__snapshots__/index.test.tsx.snap, packages/data-warehouse/src/components/network/__tests__/__snapshots__/network.test.tsx.snap, packages/data-warehouse/src/components/network/network.tsx
=> fix: resolve typo

packages/payments-ui/src/payment-page/__tests__/__snapshots__/payment-form.test.tsx.snap, packages/payments-ui/src/payment-page/payment-form.tsx, packages/ts-scripts/src/authorizer/index.ts
=> fix: #11357 minor payments fixes

packages/data-warehouse/src/components/network/ip-create-modal.tsx, packages/data-warehouse/src/components/network/rule-create-modal.tsx
=> fix: #11386 dw ui fix

packages/data-warehouse/src/components/network/__tests__/__snapshots__/index.test.tsx.snap, packages/data-warehouse/src/components/network/__tests__/__snapshots__/network.test.tsx.snap, packages/data-warehouse/src/components/network/__tests__/__snapshots__/rules-table.test.tsx.snap, packages/data-warehouse/src/components/network/network.tsx, packages/data-warehouse/src/components/network/rule-create-modal.tsx, packages/data-warehouse/src/components/network/rules-table.tsx
fixes: #11397
- validation rules tweaked to match the backend
- I Use PowerBI button moved to Nav bar instead of on each table row
=> chore: 11397 update validation and move button

packages/utils-authorizer/src/index.ts
=> fix: added id token to cognito verifier

packages/utils-authorizer/src/index.ts
=> refactor: aws docs 'null for both is fine'

packages/deployment-service/cdk/lib/cdk-stack.ts, packages/graphql-server/cdk-stack.ts
=> fix: revert to cognito authorizer

packages/app-marketplace-cms/cdk/cdk-stack.ts, packages/app-marketplace-cms/cdk/cdk.ts, packages/app-marketplace-cms/package.json, packages/app-marketplace-cms/src/cms/marketplace-app-model.ts, packages/app-marketplace-cms/tsup.config.js, packages/deployment-service/cdk/lib/cdk-stack.ts, packages/graphql-server/cdk-stack.ts, packages/utils-authorizer/src/index.ts, yarn.lock
=> feat: Rplt 108 refactor cognito authorizer usage

packages/app-marketplace-cms/cdk/cdk-stack.ts
=> fix: corrected marketplace config

packages/deployment-service/cdk/lib/cdk-stack.ts
=> fix: conditional authorizer to remove from api http lambda

packages/cognito-custom-mail-lambda/src/mailer/custom-mailer.ts
- adds handling for using a custom return url for new user signups specifically for user's using Console Cloud.
=> feat: rplt-394 add custom redirect for console product

packages/utils-nest/package.json, yarn.lock
=> fix: removed nestjs packages from dev deps utils-nest

packages/graphql-server/package.json
=> fix: fixed bundle

packages/deployment-service/cdk/lib/create-S3-bucket.ts
=> fix: public access roles for dpeloyment service s3

packages/deployment-service/cdk/lib/create-S3-bucket.ts
=> fix: remove block all

packages/deployment-service/cdk/lib/create-S3-bucket.ts
=> fix: remove public access

packages/ts-scripts/src/cdk/components/rds-database.ts
=> fix: bump database version

packages/deployment-service/cdk/lib/cdk-stack.ts
=> fix: remove migration script for deployment to dev

packages/deployment-service/src/pipeline-runner/module.ts, packages/deployment-service/src/pipeline-runner/secret.pipeline.controller.ts, packages/deployment-service/src/pipeline/pipeline-provider.ts
=> feat: added secret controller for fixes

packages/developer-portal/src/components/apps/page/__tests__/__snapshots__/submit-review-modal.test.tsx.snap, packages/developer-portal/src/components/apps/page/submit-review-modal.tsx
- alters the email address on the account information required modal
=> chore: rplt-584 update email address on review modal

packages/payments-service/src/core/authorizer.ts
=> fix: rplt-591 authoriser tweaks

packages/developer-portal/src/components/apps/page/index.tsx
=> feat: disable pipelines

packages/deployment-service/cdk/lib/cdk-stack.ts
- Enables step to correct the policies on the IaaS S3 buckets
=> chore: enable step two in IaaS production fixes

packages/deployment-service/cdk/lib/cdk-stack.ts
- enables next step of iaas production fixes
=> chore: step 3 of iaas production fix

packages/deployment-service/cdk/lib/cdk-stack.ts
Enable step 4 of iaas production fixes to update the S3 bucket permissions
=> chore: iaas final step

packages/developer-portal/src/components/apps/page/index.tsx, packages/developer-portal/src/components/iaas/index.tsx
- Revert changes made as part of IaaS maintenance
=> chore: revert changes and remove notice

packages/data-warehouse/src/components/accounts/account-provision-modal.tsx, packages/data-warehouse/src/components/accounts/account-update-modal.tsx
=> feat: data warehouse password validation changes RPLT 749

.github/labeler.yml
=> fix: removes a line of text to test codacy

packages/admin-portal/README.md
=> fix: fix: removes a line of text to test codacy 

packages/developer-portal/src/components/apps/pipeline/pipeline-configure.tsx, packages/developer-portal/src/components/register/__tests__/__snapshots__/index.test.tsx.snap, packages/developer-portal/src/components/register/form/second-form.tsx
=> feat: #823 rplt https to website field

packages/developer-portal/src/constants/routes.ts
=> feat: change url for developer/register

packages/security-header-lambda/serverless.yml
=> feat: remove aml checklist

packages/developer-portal/src/components/apps/pipeline/dns/dns-step-three.tsx
=> feat: certificate human readable

packages/developer-portal/src/components/apps/pipeline/dns/dns-step-three.tsx, packages/developer-portal/src/components/apps/pipeline/dns/dns-step-two.tsx
=> feat: added polling functions for status updates

packages/deployment-service/cdk/lib/cdk-stack.ts, packages/ts-scripts/src/cdk/components/rds-database.ts
=> feat: added bastion to iaas

packages/ts-scripts/src/cdk/components/rds-database.ts
=> fix: correct ebs device name on bastion

packages/ts-scripts/src/cdk/components/rds-database.ts
=> refactor: changed port accessible to security group

packages/ts-bundler/src/get-context.ts, packages/ts-bundler/src/ts-bundler.ts
=> chore: remove monorepo namespace req from ts-bundler

packages/deployment-service/src/dns/dns.controller.ts
=> fix: remove certificate error when dns verified

packages/security-header-lambda/package.json
=> chore: trigger lambda build

packages/cognito-custom-mail-lambda/package.json
=> fix: undo forced merged changes

packages/deployment-service/src/custom-class-serialiser-interceptor.ts
=> fix: resolve undefined for non credentials requests

packages/rc-service/src/components/users/view-organisations.tsx
- Introduces Close button to modal that displays user organisations
=> feat: rplt-970 added close button to modal

packages/developer-portal/src/components/apps/pipeline/dns/index.tsx, packages/developer-portal/src/components/apps/pipeline/index.tsx
- Removes beta banner for iaas
- Tweaks a sentence when user is not permitted to setup custom dns
=> feat: rplt-1041 remove iaas beta banner, tweak wording

packages/cognito-custom-mail-lambda/package.json
- enables devops release on mailer package so we can release to anz
=> ci: enable devops release

packages/cognito-custom-mail-lambda/package.json
=> ci: disable devops release

packages/rc-service/src/components/users/__tests__/__snapshots__/index.test.tsx.snap, packages/rc-service/src/components/users/__tests__/edit-user-groups.test.tsx, packages/rc-service/src/components/users/active-authenticator.tsx, packages/rc-service/src/components/users/authenticator-modal.tsx, packages/rc-service/src/components/users/delete-authenticator.tsx, packages/rc-service/src/components/users/edit-user-groups.tsx, packages/rc-service/src/components/users/index.tsx, packages/rc-service/src/components/users/office-groups-modal.tsx, packages/rc-service/src/components/users/reset-password-modal.tsx, packages/rc-service/src/components/users/supression-list-modal.tsx, packages/rc-service/src/components/users/update-user-name.tsx
=> feat: RPLT-1270 rc service app tweaks

packages/rc-service/src/components/users/__tests__/__snapshots__/user-content.test.tsx.snap, packages/rc-service/src/components/users/__tests__/user-content.test.tsx, packages/rc-service/src/components/users/user-content.tsx, packages/rc-service/src/tests/__stubs__/users.ts
=> feat: org type display chip next to org name

packages/marketplace-management/src/components/ui/users/__tests_/__snapshots__/edit-user.test.tsx.snap, packages/marketplace-management/src/components/ui/users/__tests_/edit-user.test.tsx, packages/marketplace-management/src/components/ui/users/edit-user.tsx
=> fix: MMA only does things with groups on the whitelist
